const MultiLanguage = 
{
  "pt-BR": {
    "Advance": "Avançar",
    "Africa": "África",
    "Age": "Idade",
    "Albania": "Albânia",
    "Algeria": "Argélia",
    "America": "América",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antígua e Barbuda",
    "Argentina": "Argentina",
    "Argentina Cup": "Copa da Argentina",
    "Argentina League": "Liga da Argentina",
    "Argentina Supercup": "Supercopa Argentina",
    "Armenia": "Armênia",
    "Asia": "Ásia",
    "Assists": "Assistências",
    "Attack": "Ataque",
    "Attacking midfielder": "Meio-campista ofensivo",
    "Audience": "Público",
    "Australia": "Austrália",
    "Australia Cup": "Copa da Austrália",
    "Australia League": "Liga da Austrália",
    "Australia Supercup": "Supercopa da Austrália",
    "Austria": "Áustria",
    "Automatic selection": "Seleção automática",
    "Average": "Média",
    "Away": "Fora",
    "Azerbaijan": "Azerbaijão",
    "Back": "Voltar",
    "Background color": "Cor de fundo",
    "Bahrain": "Bahrein",
    "Balanced": "Equilibrado",
    "Ball Possession": "Posse de bola",
    "Barbados": "Barbados",
    "Belarus": "Bielorrússia",
    "Belgium": "Bélgica",
    "BeNe": "BeNe",
    "BeNe Cup": "Copa BeNe",
    "BeNe League": "Liga BeNe",
    "BeNe Supercup": "Supercopa BeNe",
    "Benin": "Benin",
    "Bermuda": "Bermudas",
    "Billion": "Bilhão",
    "Billions": "Bilhões",
    "Board of Directors": "Diretoria",
    "Bolivia": "Bolívia",
    "Bosnia and Herzegovina": "Bósnia e Herzegovina",
    "Brazil": "Brasil",
    "Brazil Cup": "Copa do Brasil",
    "Brazil League": "Liga do Brasil",
    "Brazil Supercup": "Supercopa do Brasil",
    "British Isles": "Ilhas Britânicas",
    "British Isles Cup": "Copa das Ilhas Britânicas",
    "British Isles League": "Liga das Ilhas Britânicas",
    "British Isles Supercup": "Supercopa das Ilhas Britânicas",
    "Bronze": "Bronze",
    "Bulgaria": "Bulgária",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Buy": "Comprar",
    "Cabo Verde": "Cabo Verde",
    "Calendar": "Calendário",
    "CAM": "MEI",
    "Cameroon": "Camarões",
    "Canada": "Canadá",
    "Cancel": "Cancelar",
    "Capacity": "Capacidade",
    "Category": "Categoria",
    "CB": "ZAG",
    "CDM": "VOL",
    "Central African Republic": "República Centro-Africana",
    "Centre Europe": "Europa Central",
    "Centre Europe Cup": "Copa da Europa Central",
    "Centre Europe League": "Liga da Europa Central",
    "Centre Europe Supercup": "Supertaça da Europa Central",
    "Centre forward": "Centroavante",
    "Centre midfielder": "Meio-campista Central",
    "Centre-back": "Zagueiro",
    "CF": "SA",
    "Chad": "Chade",
    "Champions": "Campeões",
    "Championship": "Campeonato",
    "Championships": "Campeonatos",
    "Chile": "Chile",
    "China PR": "China PR",
    "Chinese Taipei": "Taipei Chinês",
    "Choose your club": "Escolha seu clube",
    "Classification": "Classificação",
    "Close": "Fechar",
    "Club": "Clube",
    "Clubs": "Clubes",
    "CM": "MC",
    "Coach": "Treinador",
    "Colombia": "Colômbia",
    "Colors": "Cores",
    "Comoros": "Comores",
    "CON": "CON",
    "Congo": "Congo",
    "Congo DR": "RD Congo",
    "Continue": "Continuar",
    "Costa Rica": "Costa Rica",
    "Côte d'Ivoire": "Costa do Marfim",
    "Country": "País",
    "Creating game...": "Criando jogo...",
    "Croatia": "Croácia",
    "Cuba": "Cuba",
    "Cup": "Copa",
    "Curacao": "Curaçao",
    "Cyprus": "Chipre",
    "Czechia": "Tchéquia",
    "Date": "Data",
    "Defense": "Defesa",
    "Defensive": "Defensivo",
    "Defensive midfielder": "Volante",
    "Delete": "Excluir",
    "Denmark": "Dinamarca",
    "Diamond": "Diamante",
    "Division": "Divisão",
    "Dominican Republic": "República Dominicana",
    "Draws": "Empates",
    "Eastern Europe": "Europa Oriental",
    "Eastern Europe Cup": "Copa da Europa Oriental",
    "Eastern Europe League": "Liga da Europa Oriental",
    "Eastern Europe Supercup": "Supercopa da Europa Oriental",
    "Ecuador": "Equador",
    "Egypt": "Egito",
    "El Salvador": "El Salvador",
    "End of the match": "Fim da partida",
    "Energy": "Energia",
    "England": "Inglaterra",
    "England Cup": "Copa da Inglaterra",
    "England League": "Liga da Inglaterra",
    "England Supercup": "Supercopa da Inglaterra",
    "Equatorial Guinea": "Guiné Equatorial",
    "Error": "Erro",
    "Estonia": "Estônia",
    "Eurasia": "Eurásia",
    "Eurasia Cup": "Copa da Eurásia",
    "Eurasia League": "Liga da Eurásia",
    "Eurasia Supercup": "Supercopa da Eurásia",
    "Europe": "Europa",
    "Event": "Evento",
    "Exit Game": "Sair do jogo",
    "Expand": "Expandir",
    "False 9": "Falso 9",
    "Faroe Islands": "Ilhas Faroé",
    "Fiji": "Fiji",
    "Final": "Final",
    "Finances": "Finanças",
    "Finland": "Finlândia",
    "Flat": "Plano",
    "For Sale": "À venda",
    "Formation": "Formação",
    "Foul": "Falta",
    "Fouls": "Faltas",
    "France": "França",
    "France Cup": "Copa da França",
    "France League": "Liga da França",
    "France Supercup": "Supercopa da França",
    "Free Kick Taker": "Batedor de falta",
    "Full screen": "Tela cheia",
    "Gabon": "Gabão",
    "Gambia": "Gâmbia",
    "Game": "Jogo",
    "Game deleted with success": "Jogo excluído com sucesso",
    "Georgia": "Geórgia",
    "Germany": "Alemanha",
    "Germany Cup": "Copa da Alemanha",
    "Germany League": "Liga da Alemanha",
    "Germany Supercup": "Supercopa da Alemanha",
    "Ghana": "Gana",
    "Gibraltar": "Gibraltar",
    "GK": "GOL",
    "Goal": "Gol",
    "Goalkeeper": "Goleiro",
    "Goals": "Gols",
    "Goals against": "Gols contra",
    "Goals difference": "Saldo de gols",
    "Gold": "Ouro",
    "Greece": "Grécia",
    "Grenada": "Granada",
    "Group": "Grupo",
    "Guatemala": "Guatemala",
    "Guinea": "Guiné",
    "Guinea-Bissau": "Guiné-Bissau",
    "Guyana": "Guiana",
    "Haiti": "Haiti",
    "History": "História",
    "Holding": "Contenção",
    "Home": "Início",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungary": "Hungria",
    "Iceland": "Islândia",
    "Income": "Renda",
    "India": "Índia",
    "Indochina": "Indochina",
    "Indochina Cup": "Copa da Indochina",
    "Indochina League": "Liga da Indochina",
    "Indochina Supercup": "Supercopa da Indochina",
    "Indonesia": "Indonésia",
    "Injured player": "Jogador lesionado",
    "International": "Internacional",
    "Invalid value": "Valor inválido",
    "Iran": "Irã",
    "Iraq": "Iraque",
    "Israel": "Israel",
    "Italy": "Itália",
    "Italy Cup": "Copa da Itália",
    "Italy League": "Liga da Itália",
    "Italy Supercup": "Supercopa da Itália",
    "Jamaica": "Jamaica",
    "Japan": "Japão",
    "Jordan": "Jordânia",
    "Kazakhstan": "Cazaquistão",
    "Kenya": "Quênia",
    "Korea Republic": "Coreia do Sul",
    "Korea-Japan": "Coreia-Japão",
    "Korea-Japan Cup": "Copa Coreia-Japão",
    "Korea-Japan League": "Liga Coreia-Japão",
    "Korea-Japan Supercup": "Supercopa Coreia-Japão",
    "Kosovo": "Kosovo",
    "Kyrgyz Republic": "República do Quirguistão",
    "Latvia": "Letônia",
    "LB": "LE",
    "League": "Liga",
    "Lebanon": "Líbano",
    "Left": "Esquerda",
    "Left midfielder": "Meia-esquerda",
    "Left wing-back": "Ala-esquerdo",
    "Left winger": "Ponta-esquerda",
    "Left-back": "Lateral Esquerdo",
    "LF": "MAE",
    "Liberia": "Libéria",
    "Libya": "Líbia",
    "Lineup": "Escalação",
    "Lithuania": "Lituânia",
    "LM": "ME",
    "Load": "Carregar",
    "Load Game": "Carregar jogo",
    "Load more": "Carregue mais",
    "Loading game...": "Carregando o jogo...",
    "Logo": "Logotipo",
    "Losses": "Derrotas",
    "Luxembourg": "Luxemburgo",
    "LW": "PE",
    "LWB": "ADE",
    "Madagascar": "Madagascar",
    "Make an offer": "Fazer oferta",
    "Malawi": "Malaui",
    "Mali": "Mali",
    "Malta": "Malta",
    "Market Value": "Valor de mercado",
    "Match": "Partida",
    "Matchday": "Rodada",
    "Matches": "Partidas",
    "Mauritania": "Mauritânia",
    "Maximum": "Máximo",
    "Messages": "Mensagens",
    "Mexico": "México",
    "Midfield": "Meio-campo",
    "Million": "Milhão",
    "Millions": "Milhões",
    "Minimum": "Mínimo",
    "Moldova": "Moldávia",
    "Money": "Dinheiro",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Morocco": "Marrocos",
    "Mozambique": "Moçambique",
    "Name": "Nome",
    "Namibia": "Namíbia",
    "Narrow": "Estreito",
    "National": "Nacional",
    "Nationality": "Nacionalidade",
    "Nepal": "Nepal",
    "Netherlands": "Holanda",
    "New Game": "Novo jogo",
    "New Zealand": "Nova Zelândia",
    "Nigeria": "Nigéria",
    "No": "Não",
    "North America": "América do Norte",
    "North America Cup": "Copa da América do Norte",
    "North America League": "Liga da América do Norte",
    "North America Supercup": "Supercopa da América do Norte",
    "North Macedonia": "Macedônia do Norte",
    "Northern Ireland": "Irlanda do Norte",
    "Norway": "Noruega",
    "Offensive": "Ofensivo",
    "Offer": "Proposta",
    "Offer (in millions of $)": "Proposta (em milhões de $)",
    "Offer (in thousands of $)": "Proposta (em milhares de $)",
    "Offside": "Impedimento",
    "Options": "Opções",
    "Out until": "Fora até",
    "OV": "OV",
    "Overall": "Overall",
    "Palestine": "Palestina",
    "Panama": "Panamá",
    "Paraguay": "Paraguai",
    "Passes": "Passes",
    "Penalty": "Pênalti",
    "Penalty Taker": "Marcador de pênaltis",
    "Peru": "Peru",
    "Philippines": "Filipinas",
    "Play": "Jogar",
    "Player": "Jogador",
    "Players": "Jogadores",
    "Playing Style": "Estilo de jogo",
    "Points": "Pontos",
    "Poland": "Polônia",
    "Portugal": "Portugal",
    "Portugal Cup": "Copa de Portugal",
    "Portugal League": "Liga de Portugal",
    "Portugal Supercup": "Supercopa de Portugal",
    "POS": "POS",
    "Position": "Posição",
    "Preferred Side": "Lado preferido",
    "Processing...": "Em processamento...",
    "Puerto Rico": "Porto Rico",
    "Quarter-finals": "Quartas de final",
    "Raffoot": "Raffoot",
    "Ranking": "Classificação",
    "RB": "LD",
    "Red card": "Cartão vermelho",
    "Referee": "Árbitro",
    "Republic of Ireland": "República da Irlanda",
    "Reset": "Reset",
    "RF": "MAD",
    "Right": "Direita",
    "Right midfielder": "Meia-direita",
    "Right wing-back": "Ala-direito",
    "Right winger": "Ponta-direita",
    "Right-back": "Lateral Direito",
    "RM": "MD",
    "Romania": "Romênia",
    "Round of 16": "Rodadas de 16",
    "Round of 32": "Rodadas de 32",
    "Round of 64": "Rodada de 64",
    "Russia": "Rússia",
    "RW": "PD",
    "Rwanda": "Ruanda",
    "RWB": "ADD",
    "Saint Kitts and Nevis": "São Cristóvão e Nevis",
    "Saint Lucia": "Santa Lúcia",
    "São Tomé and Príncipe": "São Tomé e Príncipe",
    "Saudi Arabia": "Arábia Saudita",
    "Saudi Arabia Cup": "Copa da Arábia Saudita",
    "Saudi Arabia League": "Liga da Arábia Saudita",
    "Saudi Arabia Supercup": "Supercopa da Arábia Saudita",
    "Save Changes": "Salvar alterações",
    "Save Game": "Salvar jogo",
    "Scandinavia": "Escandinávia",
    "Scandinavia Cup": "Copa da Escandinávia",
    "Scandinavia League": "Liga Escandinávia",
    "Scandinavia Supercup": "Supercopa da Escandinávia",
    "Scotland": "Escócia",
    "Search": "Procurar",
    "Search Players": "Pesquisar jogadores",
    "Sector": "Setor",
    "Semifinals": "Semifinais",
    "Send": "Enviar",
    "Senegal": "Senegal",
    "Serbia": "Sérvia",
    "Shots on goal": "Chutes a gol",
    "Showing {0} of {1}": "Mostrando {0} de {1}",
    "Sierra Leone": "Serra Leoa",
    "Silver": "Prata",
    "Slovakia": "Eslováquia",
    "Slovenia": "Eslovênia",
    "Somalia": "Somália",
    "South Africa": "África do Sul",
    "South America": "América do Sul",
    "South America Cup": "Copa Sul-Americana",
    "South America League": "Liga Sul-Americana",
    "South America Supercup": "Supercopa Sul-Americana",
    "South Sudan": "Sudão do Sul",
    "Spain": "Espanha",
    "Spain Cup": "Copa da Espanha",
    "Spain League": "Liga da Espanha",
    "Spain Supercup": "Supercopa da Espanha",
    "Squad": "Elenco",
    "Sri Lanka": "Sri Lanka",
    "ST": "ATA",
    "Stadium": "Estádio",
    "Standings": "Tabelas",
    "Star": "Estrela",
    "Start Game": "Começar o jogo",
    "Start of the match": "Início da partida",
    "Starting game...": "Começando o jogo...",
    "Statistics": "Estatisticas",
    "Striker": "Atacante",
    "Sudan": "Sudão",
    "Supercup": "Supertaça",
    "Supporters": "Torcedores",
    "Suriname": "Suriname",
    "Suspended": "Suspenso",
    "Sweden": "Suécia",
    "Switzerland": "Suíça",
    "Syria": "Síria",
    "Tackles": "Desarmes",
    "Tanzania": "Tanzânia",
    "Text color": "Cor do texto",
    "Thailand": "Tailândia",
    "Thousand": "Mil",
    "Ticket Price": "Preço do bilhete",
    "Time": "Tempo",
    "Togo": "Togo",
    "Top Scorers": "Artilheiros",
    "Total": "Total",
    "Transfer Window": "Janela de transferência",
    "Trinidad and Tobago": "Trinidad e Tobago",
    "Trust": "Confiança",
    "Tunisia": "Tunísia",
    "Türkiye": "Turquia",
    "Type": "Tipo",
    "Uganda": "Uganda",
    "Ukraine": "Ucrânia",
    "Uniform": "Uniforme",
    "United Arab Emirates": "Emirados Árabes Unidos",
    "United States": "Estados Unidos",
    "Uruguay": "Uruguai",
    "Uzbekistan": "Uzbequistão",
    "Value greater than the money available": "Valor maior que o dinheiro disponível",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Wage": "Salário",
    "Wales": "País de Gales",
    "Wide": "Largo",
    "Window mode": "Modo janela",
    "Wins": "Vitórias",
    "World": "Mundo",
    "World Cup": "Copa do Mundo",
    "Year": "Ano",
    "Yellow Card": "Cartão amarelo",
    "Yellow Cards": "Cartões amarelos",
    "Yes": "Sim",
    "Zambia": "Zâmbia",
    "Zimbabwe": "Zimbábue"
  }
};