const MultiLanguage = 
{
  "de": {
    "CAM": "ZOM",
    "CB": "IV",
    "CDM": "ZDM",
    "CF": "MS",
    "CM": "ZM",
    "GK": "TW",
    "LB": "LV",
    "LF": "LS",
    "LM": "LM",
    "LW": "LF",
    "LWB": "LAV",
    "RB": "RV",
    "RF": "RS",
    "RM": "RM",
    "RW": "RF",
    "RWB": "RAV",
    "ST": "ST"
  },
  "en": {
    "CAM": "CAM",
    "CB": "CB",
    "CDM": "CDM",
    "CF": "CF",
    "CM": "CM",
    "GK": "GK",
    "LB": "LB",
    "LF": "LF",
    "LM": "LM",
    "LW": "LW",
    "LWB": "LWB",
    "RB": "RB",
    "RF": "RF",
    "RM": "RM",
    "RW": "RW",
    "RWB": "RWB",
    "ST": "ST"
  },
  "es": {
    "CAM": "MCO",
    "CB": "DFC",
    "CDM": "MCD",
    "CF": "SD",
    "CM": "MC",
    "GK": "POR",
    "LB": "LI",
    "LF": "SDI",
    "LM": "MI",
    "LW": "EI",
    "LWB": "CAI",
    "RB": "LD",
    "RF": "SDD",
    "RM": "MD",
    "RW": "ED",
    "RWB": "CAD",
    "ST": "DC"
  },
  "fr": {
    "CAM": "MOC",
    "CB": "DC",
    "CDM": "MDC",
    "CF": "AT",
    "CM": "MC",
    "GK": "G",
    "LB": "DG",
    "LF": "AVG",
    "LM": "MG",
    "LW": "AG",
    "LWB": "DLG",
    "RB": "DD",
    "RF": "AVD",
    "RM": "MD",
    "RW": "AD",
    "RWB": "DLD",
    "ST": "BU"
  },
  "it": {
    "CAM": "COC",
    "CB": "DC",
    "CDM": "CDC",
    "CF": "AT",
    "CM": "CC",
    "GK": "POR",
    "LB": "TS",
    "LF": "ATS",
    "LM": "ES",
    "LW": "AS",
    "LWB": "ASA",
    "RB": "TD",
    "RF": "ATD",
    "RM": "ED",
    "RW": "AD",
    "RWB": "ADA",
    "ST": "ATT"
  },
  "nl": {
    "CAM": "CAM",
    "CB": "CV",
    "CDM": "CVM",
    "CF": "CA",
    "CM": "CM",
    "GK": "DM",
    "LB": "LA",
    "LF": "LV",
    "LM": "LM",
    "LW": "LVA",
    "LWB": "LVV",
    "RB": "RA",
    "RF": "RV",
    "RM": "RM",
    "RW": "RVA",
    "RWB": "RVV",
    "ST": "SP"
  },
  "pt-BR": {
    "Afghanistan": "Afeganistão",
    "Age": "Idade",
    "Albania": "Albânia",
    "Algeria": "Argélia",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antígua e Barbuda",
    "Argentina": "Argentina",
    "Argentina Cup": "Copa Argentina",
    "Argentina League": "Liga Argentina",
    "Argentina Supercup": "Supercopa da Argentina",
    "Armenia": "Armênia",
    "Assists": "Assistências",
    "Attacking midfielder": "Meia-atacante",
    "Audience": "Público",
    "Australia": "Austrália",
    "Austria": "Áustria",
    "Away": "Fora",
    "Azerbaijan": "Azerbaijão",
    "Back": "Voltar",
    "Ball possession": "Posse de bola",
    "Belarus": "Bielorrússia",
    "Belgium": "Bélgica",
    "BeNe": "BeNe",
    "BeNe Cup": "Copa BeNe",
    "BeNe League": "Liga BeNe",
    "BeNe Supercup": "BeNe Supercopa",
    "Benin": "Benim",
    "Bermuda": "Bermudas",
    "Board of directors": "Diretoria",
    "Bolivia": "Bolívia",
    "Bosnia and Herzegovina": "Bósnia e Herzegovina",
    "Brazil": "Brasil",
    "Brazil Cup": "Copa do brasil",
    "Brazil League": "Liga Brasil",
    "Brazil Supercup": "Supercopa do Brasil",
    "British Isles": "Ilhas britânicas",
    "British Isles Cup": "Copa das Ilhas Britânicas",
    "British Isles League": "Liga das Ilhas Britânicas",
    "British Isles Supercup": "Supercopa das Ilhas Britânicas",
    "Bronze": "Bronze",
    "Bulgaria": "Bulgária",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Calendar": "Calendário",
    "CAM": "MEI",
    "Cameroon": "Camarões",
    "Canada": "Canadá",
    "Cancel": "Cancelar",
    "Capacity": "Capacidade",
    "Cape Verde Islands": "Ilhas de Cabo Verde",
    "Category": "Categoria",
    "CB": "ZAG",
    "CDM": "VOL",
    "Central African Republic": "República Centro-Africana",
    "Central Europe": "A Europa Central",
    "Central Europe Cup": "Copa da Europa Central",
    "Central Europe League": "Liga da Europa Central",
    "Central Europe Supercup": "Supercopa da Europa Central",
    "Centre forward": "Centroavante",
    "Centre midfielder": "Meia central",
    "Centre-back": "Zagueiro",
    "CF": "SA",
    "Chad": "Chade",
    "Champions": "Campeões",
    "Champions Cup": "Copa dos campeões",
    "Chile": "Chile",
    "China PR": "China PR",
    "Chinese Taipei": "Taipei Chinês",
    "Choose your club": "Escolha seu clube",
    "Classification tables": "Tabelas de classificação",
    "Club": "Clube",
    "Clubs": "Clubes",
    "CM": "MC",
    "Coach": "Treinador",
    "Colombia": "Colômbia",
    "Comoros": "Comores",
    "CON": "CON",
    "Conference Cup": "Copa da Conferência",
    "Congo": "Congo",
    "Congo DR": "República Democrática do Congo",
    "Contract": "Contrato",
    "Costa Rica": "Costa Rica",
    "Côte d'Ivoire": "Costa do Marfim",
    "Country": "País",
    "Creating game...": "Criando jogo...",
    "Croatia": "Croácia",
    "Cuba": "Cuba",
    "Cup": "Copa",
    "Curacao": "Curaçao",
    "Cyprus": "Chipre",
    "Czech Republic": "República Tcheca",
    "Date": "Data",
    "Defensive midfielder": "Volante",
    "Delete": "Excluir",
    "Denmark": "Dinamarca",
    "Division": "Divisão",
    "Dominican Republic": "República Dominicana",
    "Eastern Europe": "Europa Oriental",
    "Eastern Europe Cup": "Copa do Leste Europeu",
    "Eastern Europe League": "Liga da Europa Oriental",
    "Eastern Europe Supercup": "Supercopa do Leste Europeu",
    "Ecuador": "Equador",
    "Egypt": "Egito",
    "El Salvador": "El Salvador",
    "End of contract": "Fim de contrato",
    "Energy": "Energia",
    "England": "Inglaterra",
    "England Cup": "Copa da Inglaterra",
    "England League": "Liga da Inglaterra",
    "England Supercup": "Supercopa da Inglaterra",
    "Equatorial Guinea": "Guiné Equatorial",
    "Error": "Erro",
    "Estonia": "Estônia",
    "Eurasia": "Eurásia",
    "Eurasia Cup": "Copa da Eurásia",
    "Eurasia League": "Liga da Eurásia",
    "Eurasia Supercup": "Supercopa da Eurásia",
    "Expand": "Expandir",
    "Faroe Islands": "Ilhas Faroé",
    "Fiji": "Fiji",
    "Final": "Final",
    "Finances": "Finanças",
    "Finland": "Finlândia",
    "For sale": "À venda",
    "Formation": "Formação",
    "France": "França",
    "France Cup": "Copa da França",
    "France League": "Liga da França",
    "France Supercup": "Supercopa da França",
    "Free kick": "Tiro livre",
    "Free kick taker": "Cobrador de falta",
    "Gabon": "Gabão",
    "Gambia": "Gâmbia",
    "Game": "Jogo",
    "Game deleted with success": "Jogo deletado com sucesso",
    "Georgia": "Geórgia",
    "Germany": "Alemanha",
    "Germany Cup": "Copa da alemanha",
    "Germany League": "Liga Alemã",
    "Germany Supercup": "Supercopa da Alemanha",
    "Ghana": "Gana",
    "Gibraltar": "Gibraltar",
    "GK": "GOL",
    "Goal": "Gol",
    "Goalkeeper": "Goleiro",
    "Goals": "Gols",
    "Gold": "Ouro",
    "Greece": "Grécia",
    "Grenada": "Granada",
    "Group": "Grupo",
    "Guatemala": "Guatemala",
    "Guinea": "Guiné",
    "Guinea Bissau": "Guiné-Bissau",
    "Guyana": "Guiana",
    "Haiti": "Haiti",
    "History": "História",
    "Home": "Casa",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungary": "Hungria",
    "Iceland": "Islândia",
    "Income": "Renda",
    "India": "Índia",
    "Indonesia": "Indonésia",
    "International Supercup": "Supercopa Internacional",
    "Iran": "Irã",
    "Iraq": "Iraque",
    "Israel": "Israel",
    "Italy": "Itália",
    "Italy Cup": "Copa Itália",
    "Italy League": "Liga Itália",
    "Italy Supercup": "Supercopa da Itália",
    "Jamaica": "Jamaica",
    "Japan": "Japão",
    "Jordan": "Jordânia",
    "Kazakhstan": "Cazaquistão",
    "Kenya": "Quênia",
    "Korea DPR": "Coreia do Norte",
    "Korea Republic": "Coreia do Sul",
    "Kosovo": "Kosovo",
    "Latvia": "Letônia",
    "LB": "LE",
    "League": "Liga",
    "Lebanon": "Líbano",
    "Left": "Esquerda",
    "Left midfielder": "Meio-campista esquerdo",
    "Left wing-back": "Lateral-esquerdo",
    "Left winger": "Lateral esquerdo",
    "Left-back": "Lateral-esquerdo",
    "LF": "MAE",
    "Liberia": "Libéria",
    "Libya": "Líbia",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituânia",
    "LM": "ME",
    "Load game": "Carregar jogo",
    "Loading game...": "Carregando o jogo...",
    "Luxembourg": "Luxemburgo",
    "LW": "PE",
    "LWB": "ADE",
    "Madagascar": "Madagáscar",
    "Malawi": "Malauí",
    "Mali": "Mali",
    "Malta": "Malta",
    "Market value": "Valor de mercado",
    "Matches": "Partidas",
    "Mauritania": "Mauritânia",
    "Mauritius": "Maurício",
    "Mexico": "México",
    "Moldova": "Moldávia",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Morocco": "Marrocos",
    "Mozambique": "Moçambique",
    "Name": "Nome",
    "Namibia": "Namíbia",
    "Nationality": "Nacionalidade",
    "Netherlands": "Holanda",
    "New game": "Novo jogo",
    "New Zealand": "Nova Zelândia",
    "Nigeria": "Nigéria",
    "No": "Não",
    "North America": "América do Norte",
    "North America Cup": "Copa América do Norte",
    "North America League": "Liga Norte-Americana",
    "North America Supercup": "Supercopa da América do Norte",
    "North Macedonia": "Macedônia do Norte",
    "Northern Ireland": "Irlanda do Norte",
    "Norway": "Noruega",
    "Offside": "Impedimento",
    "OV": "OV",
    "Overall": "Overall",
    "Palestine": "Palestina",
    "Panama": "Panamá",
    "Paraguay": "Paraguai",
    "Penalty": "Pênalti",
    "Penalty taker": "Cobrador de pênalti",
    "Peru": "Peru",
    "Philippines": "Filipinas",
    "Play": "Jogar",
    "Players": "Jogadores de futebol",
    "Poland": "Polônia",
    "Portugal": "Portugal",
    "Portugal Cup": "Taça de Portugal",
    "Portugal League": "Liga portuguesa",
    "Portugal Supercup": "Supertaça de Portugal",
    "POS": "POS",
    "Position": "Posição",
    "Preferred side": "Lado preferido",
    "Processing...": "Em processamento...",
    "Puerto Rico": "Porto Rico",
    "Quarter-finals": "Quartas de final",
    "Raffoot": "Raffoot",
    "Ranking": "Classificação",
    "RB": "LD",
    "Referee": "Árbitro de futebol",
    "Renew contract": "Renovar contrato",
    "Republic of Ireland": "República da Irlanda",
    "Rest of the World": "Resto do mundo",
    "Rest of the World Cup": "Resto da Copa do Mundo",
    "Rest of the World League": "Resto da Liga Mundial",
    "Rest of the World Supercup": "Resto da Supercopa do Mundo",
    "RF": "MAD",
    "Right": "Direito",
    "Right midfielder": "Meio-campista direito",
    "Right wing-back": "Lateral direito",
    "Right winger": "Ponta direita",
    "Right-back": "Lateral-direito",
    "RM": "MD",
    "Romania": "Romênia",
    "Round of 16": "Rodada de 16",
    "Round of 32": "Rodada de 32",
    "Round of 64": "Rodada de 64",
    "Russia": "Rússia",
    "RW": "PD",
    "RWB": "ADD",
    "Saint Kitts and Nevis": "São Cristóvão e Nevis",
    "Saint Lucia": "Santa Lúcia",
    "São Tomé e Príncipe": "São Tomé e Príncipe",
    "Saudi Arabia": "Arábia Saudita",
    "Save game": "Salvar jogo",
    "Scandinavia": "Escandinávia",
    "Scandinavia Cup": "Copa da Escandinávia",
    "Scandinavia League": "Liga da Escandinávia",
    "Scandinavia Supercup": "Supercopa da Escandinávia",
    "Scotland": "Escócia",
    "Search": "Procurar",
    "Search players": "Procurar jogadores",
    "Semifinals": "Semifinais",
    "Senegal": "Senegal",
    "Serbia": "Sérvia",
    "Sierra Leone": "Serra Leoa",
    "Silver": "Prata",
    "Slovakia": "Eslováquia",
    "Slovenia": "Eslovênia",
    "South Africa": "África do Sul",
    "South America": "América do Sul",
    "South America Cup": "Copa Sul-Americana",
    "South America League": "Liga Sul-Americana",
    "South America Supercup": "Supercopa da América do Sul",
    "South Sudan": "Sudão do Sul",
    "Spain": "Espanha",
    "Spain Cup": "Copa da Espanha",
    "Spain League": "Liga da Espanha",
    "Spain Supercup": "Supercopa da Espanha",
    "Squad": "Esquadrão",
    "ST": "ATA",
    "Stadium": "Estádio",
    "Star": "Estrela",
    "Start game": "Começar o jogo",
    "Starting game...": "Começando o jogo...",
    "Statistics": "Estatisticas",
    "Striker": "Atacante",
    "Sudan": "Sudão",
    "Supercup": "Supercopa",
    "Suriname": "Suriname",
    "Sweden": "Suécia",
    "Switzerland": "Suíça",
    "Syria": "Síria",
    "Tajikistan": "Tadjiquistão",
    "Tanzania": "Tanzânia",
    "Thailand": "Tailândia",
    "Ticket price": "Preço do bilhete",
    "Togo": "Togo",
    "Top scorers": "Artilheiros",
    "Trinidad and Tobago": "Trinidad e Tobago",
    "Trust": "Confiança",
    "Tunisia": "Tunísia",
    "Turkey": "Turquia",
    "Uganda": "Uganda",
    "Ukraine": "Ucrânia",
    "United Arab Emirates": "Emirados Árabes Unidos",
    "United States": "Estados Unidos",
    "Uruguay": "Uruguai",
    "Uzbekistan": "Uzbequistão",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnã",
    "Wage": "Salário",
    "Wales": "País de Gales",
    "World": "Mundo",
    "Year": "Ano",
    "Yes": "Sim",
    "Zambia": "Zâmbia",
    "Zimbabwe": "Zimbábue"
  }
};