class ColorManager {
	static setClubsColors() {
		Context.game.clubs.find(c => c.name === "Adelaide United" && c.country.name === "Australia").setColors('rgb(151,44,56)', 'white');
		Context.game.clubs.find(c => c.name === "AGF" && c.country.name === "Denmark").setColors('rgb(201,189,189)', 'black');
		Context.game.clubs.find(c => c.name === "AaB" && c.country.name === "Denmark").setColors('rgb(217,129,132)', 'black');
		Context.game.clubs.find(c => c.name === "AEK Athens" && c.country.name === "Greece").setColors('rgb(133,111,44)', 'white');
		Context.game.clubs.find(c => c.name === "Abha" && c.country.name === "Saudi Arabia").setColors('rgb(161,183,201)', 'black');
		Context.game.clubs.find(c => c.name === "AFC Wimbledon" && c.country.name === "England").setColors('rgb(72,106,146)', 'white');
		Context.game.clubs.find(c => c.name === "Aalesund" && c.country.name === "Norway").setColors('rgb(197,87,58)', 'white');
		Context.game.clubs.find(c => c.name === "Aberdeen" && c.country.name === "Scotland").setColors('rgb(145,47,57)', 'white');
		Context.game.clubs.find(c => c.name === "Adana Demirspor" && c.country.name === "Turkey").setColors('rgb(57,99,149)', 'white');
		Context.game.clubs.find(c => c.name === "AFC Bournemouth" && c.country.name === "England").setColors('rgb(128,46,50)', 'white');
		Context.game.clubs.find(c => c.name === "Academia Puerto Cabello" && c.country.name === "Venezuela").setColors('rgb(151,90,91)', 'white');
		Context.game.clubs.find(c => c.name === "Accrington Stanley" && c.country.name === "England").setColors('rgb(190,49,63)', 'white');
		Context.game.clubs.find(c => c.name === "1860 München" && c.country.name === "Germany").setColors('rgb(186,195,203)', 'black');
		Context.game.clubs.find(c => c.name === "Al Fateh" && c.country.name === "Saudi Arabia").setColors('rgb(45,65,123)', 'white');
		Context.game.clubs.find(c => c.name === "Al Adalah" && c.country.name === "Saudi Arabia").setColors('rgb(194,195,198)', 'black');
		Context.game.clubs.find(c => c.name === "Al Khaleej" && c.country.name === "Saudi Arabia").setColors('rgb(216,193,37)', 'black');
		Context.game.clubs.find(c => c.name === "Al Ettifaq" && c.country.name === "Saudi Arabia").setColors('rgb(61,129,95)', 'white');
		Context.game.clubs.find(c => c.name === "Al Hilal" && c.country.name === "Saudi Arabia").setColors('rgb(57,65,151)', 'white');
		Context.game.clubs.find(c => c.name === "Ajaccio" && c.country.name === "France").setColors('rgb(167,126,129)', 'black');
		Context.game.clubs.find(c => c.name === "AIK" && c.country.name === "Sweden").setColors('rgb(59,58,48)', 'white');
		Context.game.clubs.find(c => c.name === "Al Batin" && c.country.name === "Saudi Arabia").setColors('rgb(98,168,224)', 'black');
		Context.game.clubs.find(c => c.name === "Al Ain" && c.country.name === "United Arab Emirates").setColors('rgb(59,51,67)', 'white');
		Context.game.clubs.find(c => c.name === "Al Ittihad" && c.country.name === "Saudi Arabia").setColors('rgb(127,114,53)', 'white');
		Context.game.clubs.find(c => c.name === "Al Feiha" && c.country.name === "Saudi Arabia").setColors('rgb(202,79,42)', 'white');
		Context.game.clubs.find(c => c.name === "Ajax" && c.country.name === "Netherlands").setColors('rgb(163,102,112)', 'white');
		Context.game.clubs.find(c => c.name === "Al Nassr" && c.country.name === "Saudi Arabia").setColors('rgb(191,190,107)', 'black');
		Context.game.clubs.find(c => c.name === "Al Raed" && c.country.name === "Saudi Arabia").setColors('rgb(146,62,66)', 'white');
		Context.game.clubs.find(c => c.name === "Al Shabab" && c.country.name === "Saudi Arabia").setColors('rgb(197,192,190)', 'black');
		Context.game.clubs.find(c => c.name === "Al Wahda" && c.country.name === "Saudi Arabia").setColors('rgb(189,57,59)', 'white');
		Context.game.clubs.find(c => c.name === "Al Taawon" && c.country.name === "Saudi Arabia").setColors('rgb(208,186,40)', 'black');
		Context.game.clubs.find(c => c.name === "Alanyaspor" && c.country.name === "Turkey").setColors('rgb(89,83,55)', 'white');
		Context.game.clubs.find(c => c.name === "Al Tai" && c.country.name === "Saudi Arabia").setColors('rgb(165,170,175)', 'black');
		Context.game.clubs.find(c => c.name === "Aldosivi" && c.country.name === "Argentina").setColors('rgb(128,157,67)', 'black');
		Context.game.clubs.find(c => c.name === "Amiens SC" && c.country.name === "France").setColors('rgb(192,189,190)', 'black');
		Context.game.clubs.find(c => c.name === "América Mineiro" && c.country.name === "Brazil").setColors('rgb(46,99,64)', 'white');
		Context.game.clubs.find(c => c.name === "Albacete" && c.country.name === "Spain").setColors('rgb(196,190,190)', 'black');
		Context.game.clubs.find(c => c.name === "Almería" && c.country.name === "Spain").setColors('rgb(201,103,104)', 'black');
		Context.game.clubs.find(c => c.name === "Anderlecht" && c.country.name === "Belgium").setColors('rgb(67,54,111)', 'white');
		Context.game.clubs.find(c => c.name === "Alianza Lima" && c.country.name === "Peru").setColors('rgb(131,131,146)', 'black');
		Context.game.clubs.find(c => c.name === "Angers SCO" && c.country.name === "France").setColors('rgb(83,81,80)', 'white');
		Context.game.clubs.find(c => c.name === "Annecy" && c.country.name === "France").setColors('rgb(105,36,41)', 'white');
		Context.game.clubs.find(c => c.name === "Ascoli" && c.country.name === "Italy").setColors('rgb(126,125,125)', 'white');
		Context.game.clubs.find(c => c.name === "Antwerp" && c.country.name === "Belgium").setColors('rgb(172,54,58)', 'white');
		Context.game.clubs.find(c => c.name === "Athletico Paranaense" && c.country.name === "Brazil").setColors('rgb(140,52,52)', 'white');
		Context.game.clubs.find(c => c.name === "Argentinos Juniors" && c.country.name === "Argentina").setColors('rgb(203,81,77)', 'white');
		Context.game.clubs.find(c => c.name === "Arsenal de Sarandi" && c.country.name === "Argentina").setColors('rgb(154,154,173)', 'black');
		Context.game.clubs.find(c => c.name === "Atlanta United" && c.country.name === "United States").setColors('rgb(87,49,50)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Mineiro" && c.country.name === "Brazil").setColors('rgb(118,116,114)', 'white');
		Context.game.clubs.find(c => c.name === "Arouca" && c.country.name === "Portugal").setColors('rgb(205,192,44)', 'black');
		Context.game.clubs.find(c => c.name === "Atalanta" && c.country.name === "Italy").setColors('rgb(67,89,105)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Tucumán" && c.country.name === "Argentina").setColors('rgb(171,194,210)', 'black');
		Context.game.clubs.find(c => c.name === "Audax Italiano" && c.country.name === "Chile").setColors('rgb(59,118,88)', 'white');
		Context.game.clubs.find(c => c.name === "Ankaragücü" && c.country.name === "Turkey").setColors('rgb(115,111,59)', 'white');
		Context.game.clubs.find(c => c.name === "Antalyaspor" && c.country.name === "Turkey").setColors('rgb(206,132,133)', 'black');
		Context.game.clubs.find(c => c.name === "Aston Villa" && c.country.name === "England").setColors('rgb(102,64,91)', 'white');
		Context.game.clubs.find(c => c.name === "ATK Mohun Bagan" && c.country.name === "India").setColors('rgb(114,103,91)', 'white');
		Context.game.clubs.find(c => c.name === "APOEL" && c.country.name === "Cyprus").setColors('rgb(149,144,95)', 'black');
		Context.game.clubs.find(c => c.name === "Argeş" && c.country.name === "Romania").setColors('rgb(88,59,116)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Madrid" && c.country.name === "Spain").setColors('rgb(190,129,133)', 'black');
		Context.game.clubs.find(c => c.name === "Atlético Nacional" && c.country.name === "Colombia").setColors('rgb(135,159,145)', 'black');
		Context.game.clubs.find(c => c.name === "AS Eupen" && c.country.name === "Belgium").setColors('rgb(215,215,213)', 'black');
		Context.game.clubs.find(c => c.name === "Arsenal" && c.country.name === "England").setColors('rgb(167,63,72)', 'white');
		Context.game.clubs.find(c => c.name === "Aucas" && c.country.name === "Ecuador").setColors('rgb(205,166,46)', 'black');
		Context.game.clubs.find(c => c.name === "Athletic Club" && c.country.name === "Spain").setColors('rgb(181,109,113)', 'white');
		Context.game.clubs.find(c => c.name === "Austin" && c.country.name === "United States").setColors('rgb(41,97,62)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Klagenfurt" && c.country.name === "Austria").setColors('rgb(102,47,141)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Wien" && c.country.name === "Austria").setColors('rgb(76,54,113)', 'white');
		Context.game.clubs.find(c => c.name === "AZ Alkmaar" && c.country.name === "Netherlands").setColors('rgb(178,44,44)', 'white');
		Context.game.clubs.find(c => c.name === "Barcelona Guayaquil" && c.country.name === "Ecuador").setColors('rgb(213,169,39)', 'black');
		Context.game.clubs.find(c => c.name === "Barrow" && c.country.name === "England").setColors('rgb(127,162,183)', 'black');
		Context.game.clubs.find(c => c.name === "Barnsley" && c.country.name === "England").setColors('rgb(190,42,57)', 'white');
		Context.game.clubs.find(c => c.name === "Bastia" && c.country.name === "France").setColors('rgb(62,72,122)', 'white');
		Context.game.clubs.find(c => c.name === "Benevento" && c.country.name === "Italy").setColors('rgb(175,113,43)', 'white');
		Context.game.clubs.find(c => c.name === "Birmingham City" && c.country.name === "England").setColors('rgb(54,85,141)', 'white');
		Context.game.clubs.find(c => c.name === "Bayreuth" && c.country.name === "Germany").setColors('rgb(222,178,46)', 'black');
		Context.game.clubs.find(c => c.name === "Blackpool" && c.country.name === "England").setColors('rgb(210,93,52)', 'white');
		Context.game.clubs.find(c => c.name === "Bengaluru" && c.country.name === "India").setColors('rgb(74,68,125)', 'white');
		Context.game.clubs.find(c => c.name === "Boavista" && c.country.name === "Portugal").setColors('rgb(127,121,120)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Lustenau" && c.country.name === "Austria").setColors('rgb(59,162,97)', 'black');
		Context.game.clubs.find(c => c.name === "Auxerre" && c.country.name === "France").setColors('rgb(191,194,200)', 'black');
		Context.game.clubs.find(c => c.name === "Banfield" && c.country.name === "Argentina").setColors('rgb(114,137,127)', 'black');
		Context.game.clubs.find(c => c.name === "Bari 1908" && c.country.name === "Italy").setColors('rgb(204,187,188)', 'black');
		Context.game.clubs.find(c => c.name === "Barracas Central" && c.country.name === "Argentina").setColors('rgb(208,145,145)', 'black');
		Context.game.clubs.find(c => c.name === "Basel" && c.country.name === "Switzerland").setColors('rgb(130,63,101)', 'white');
		Context.game.clubs.find(c => c.name === "Benfica" && c.country.name === "Portugal").setColors('rgb(213,46,57)', 'white');
		Context.game.clubs.find(c => c.name === "Bodø / Glimt" && c.country.name === "Norway").setColors('rgb(197,153,78)', 'black');
		Context.game.clubs.find(c => c.name === "Blackburn Rovers" && c.country.name === "England").setColors('rgb(138,152,185)', 'black');
		Context.game.clubs.find(c => c.name === "Beşiktaş" && c.country.name === "Turkey").setColors('rgb(208,206,205)', 'black');
		Context.game.clubs.find(c => c.name === "Boca Juniors" && c.country.name === "Argentina").setColors('rgb(97,105,114)', 'white');
		Context.game.clubs.find(c => c.name === "Blooming" && c.country.name === "Bolivia").setColors('rgb(83,118,173)', 'white');
		Context.game.clubs.find(c => c.name === "Bayer 04 Leverkusen" && c.country.name === "Germany").setColors('rgb(164,53,65)', 'white');
		Context.game.clubs.find(c => c.name === "Beijing Guoan" && c.country.name === "China PR").setColors('rgb(47,70,48)', 'white');
		Context.game.clubs.find(c => c.name === "Bolívar" && c.country.name === "Bolivia").setColors('rgb(83,132,185)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Dortmund" && c.country.name === "Germany").setColors('rgb(161,138,39)', 'black');
		Context.game.clubs.find(c => c.name === "Bolton Wanderers" && c.country.name === "England").setColors('rgb(192,192,190)', 'black');
		Context.game.clubs.find(c => c.name === "Botoşani" && c.country.name === "Romania").setColors('rgb(202,199,201)', 'black');
		Context.game.clubs.find(c => c.name === "Borussia Mönchengladbach" && c.country.name === "Germany").setColors('rgb(174,182,177)', 'black');
		Context.game.clubs.find(c => c.name === "Bragantino" && c.country.name === "Brazil").setColors('rgb(212,195,196)', 'black');
		Context.game.clubs.find(c => c.name === "Bohemians" && c.country.name === "Republic of Ireland").setColors('rgb(90,54,54)', 'white');
		Context.game.clubs.find(c => c.name === "Brescia" && c.country.name === "Italy").setColors('rgb(74,111,159)', 'white');
		Context.game.clubs.find(c => c.name === "Brøndby" && c.country.name === "Denmark").setColors('rgb(208,177,43)', 'black');
		Context.game.clubs.find(c => c.name === "Burnley" && c.country.name === "England").setColors('rgb(119,85,102)', 'white');
		Context.game.clubs.find(c => c.name === "Brighton & Hove Albion" && c.country.name === "England").setColors('rgb(117,146,173)', 'black');
		Context.game.clubs.find(c => c.name === "Bristol City" && c.country.name === "England").setColors('rgb(181,70,75)', 'white');
		Context.game.clubs.find(c => c.name === "Cádiz" && c.country.name === "Spain").setColors('rgb(218,205,51)', 'black');
		Context.game.clubs.find(c => c.name === "Bologna" && c.country.name === "Italy").setColors('rgb(104,55,64)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Dortmund II" && c.country.name === "Germany").setColors('rgb(161,139,41)', 'black');
		Context.game.clubs.find(c => c.name === "Bordeaux" && c.country.name === "France").setColors('rgb(79,80,85)', 'white');
		Context.game.clubs.find(c => c.name === "Bradford City" && c.country.name === "England").setColors('rgb(163,91,55)', 'white');
		Context.game.clubs.find(c => c.name === "Botafogo" && c.country.name === "Brazil").setColors('rgb(106,106,106)', 'white');
		Context.game.clubs.find(c => c.name === "Cagliari" && c.country.name === "Italy").setColors('rgb(121,50,74)', 'white');
		Context.game.clubs.find(c => c.name === "Brentford" && c.country.name === "England").setColors('rgb(192,118,121)', 'black');
		Context.game.clubs.find(c => c.name === "Brisbane Roar" && c.country.name === "Australia").setColors('rgb(172,79,43)', 'white');
		Context.game.clubs.find(c => c.name === "Bristol Rovers" && c.country.name === "England").setColors('rgb(111,126,153)', 'white');
		Context.game.clubs.find(c => c.name === "Burgos" && c.country.name === "Spain").setColors('rgb(205,205,204)', 'black');
		Context.game.clubs.find(c => c.name === "Brest" && c.country.name === "France").setColors('rgb(200,55,59)', 'white');
		Context.game.clubs.find(c => c.name === "Cardiff City" && c.country.name === "England").setColors('rgb(41,74,159)', 'white');
		Context.game.clubs.find(c => c.name === "Caen" && c.country.name === "France").setColors('rgb(87,75,104)', 'white');
		Context.game.clubs.find(c => c.name === "Celtic" && c.country.name === "Scotland").setColors('rgb(126,152,132)', 'black');
		Context.game.clubs.find(c => c.name === "Burton Albion" && c.country.name === "England").setColors('rgb(213,195,37)', 'black');
		Context.game.clubs.find(c => c.name === "Cerro Porteño" && c.country.name === "Paraguay").setColors('rgb(120,62,111)', 'white');
		Context.game.clubs.find(c => c.name === "Cambridge United" && c.country.name === "England").setColors('rgb(202,131,55)', 'black');
		Context.game.clubs.find(c => c.name === "Changchun Yatai" && c.country.name === "China PR").setColors('rgb(172,56,67)', 'white');
		Context.game.clubs.find(c => c.name === "Chelsea" && c.country.name === "England").setColors('rgb(59,70,114)', 'white');
		Context.game.clubs.find(c => c.name === "Chicago Fire" && c.country.name === "United States").setColors('rgb(47,54,80)', 'white');
		Context.game.clubs.find(c => c.name === "Coventry City" && c.country.name === "England").setColors('rgb(142,169,187)', 'black');
		Context.game.clubs.find(c => c.name === "Columbus Crew" && c.country.name === "United States").setColors('rgb(209,187,36)', 'black');
		Context.game.clubs.find(c => c.name === "Central Coast Mariners" && c.country.name === "Australia").setColors('rgb(163,134,64)', 'black');
		Context.game.clubs.find(c => c.name === "Cittadella" && c.country.name === "Italy").setColors('rgb(159,45,73)', 'white');
		Context.game.clubs.find(c => c.name === "Colchester United" && c.country.name === "England").setColors('rgb(148,154,191)', 'black');
		Context.game.clubs.find(c => c.name === "Crewe Alexandra" && c.country.name === "England").setColors('rgb(199,45,45)', 'white');
		Context.game.clubs.find(c => c.name === "Carlisle United" && c.country.name === "England").setColors('rgb(49,54,73)', 'white');
		Context.game.clubs.find(c => c.name === "Dallas" && c.country.name === "United States").setColors('rgb(151,59,84)', 'white');
		Context.game.clubs.find(c => c.name === "César Vallejo" && c.country.name === "Peru").setColors('rgb(227,101,62)', 'black');
		Context.game.clubs.find(c => c.name === "Cangzhou Mighty Lions" && c.country.name === "China PR").setColors('rgb(46,76,147)', 'white');
		Context.game.clubs.find(c => c.name === "Charlotte" && c.country.name === "United States").setColors('rgb(76,144,188)', 'black');
		Context.game.clubs.find(c => c.name === "Cheltenham Town" && c.country.name === "England").setColors('rgb(184,46,63)', 'white');
		Context.game.clubs.find(c => c.name === "Central Cordoba SdE" && c.country.name === "Argentina").setColors('rgb(133,134,137)', 'black');
		Context.game.clubs.find(c => c.name === "Colo-Colo" && c.country.name === "Chile").setColors('rgb(197,193,193)', 'black');
		Context.game.clubs.find(c => c.name === "Casa Pia" && c.country.name === "Portugal").setColors('rgb(50,49,47)', 'white');
		Context.game.clubs.find(c => c.name === "Crystal Palace" && c.country.name === "England").setColors('rgb(120,65,85)', 'white');
		Context.game.clubs.find(c => c.name === "Chindia Târgovişte" && c.country.name === "Romania").setColors('rgb(176,71,74)', 'white');
		Context.game.clubs.find(c => c.name === "Cracovia Kraków" && c.country.name === "Poland").setColors('rgb(193,121,123)', 'black');
		Context.game.clubs.find(c => c.name === "Como" && c.country.name === "Italy").setColors('rgb(83,140,178)', 'black');
		Context.game.clubs.find(c => c.name === "CF Montréal" && c.country.name === "United States").setColors('rgb(53,54,55)', 'white');
		Context.game.clubs.find(c => c.name === "Damac" && c.country.name === "Saudi Arabia").setColors('rgb(179,46,46)', 'white');
		Context.game.clubs.find(c => c.name === "Clermont" && c.country.name === "France").setColors('rgb(147,40,64)', 'white');
		Context.game.clubs.find(c => c.name === "Caracas" && c.country.name === "Venezuela").setColors('rgb(166,61,47)', 'white');
		Context.game.clubs.find(c => c.name === "Charlton Athletic" && c.country.name === "England").setColors('rgb(180,58,60)', 'white');
		Context.game.clubs.find(c => c.name === "Chengdu Rongcheng" && c.country.name === "China PR").setColors('rgb(149,53,62)', 'white');
		Context.game.clubs.find(c => c.name === "Cercle Brugge" && c.country.name === "Belgium").setColors('rgb(61,84,66)', 'white');
		Context.game.clubs.find(c => c.name === "Celta de Vigo" && c.country.name === "Spain").setColors('rgb(117,163,175)', 'black');
		Context.game.clubs.find(c => c.name === "Cienciano" && c.country.name === "Peru").setColors('rgb(185,51,49)', 'white');
		Context.game.clubs.find(c => c.name === "Corinthians" && c.country.name === "Brazil").setColors('rgb(206,205,203)', 'black');
		Context.game.clubs.find(c => c.name === "Crawley Town" && c.country.name === "England").setColors('rgb(173,53,54)', 'white');
		Context.game.clubs.find(c => c.name === "Colón" && c.country.name === "Argentina").setColors('rgb(121,67,64)', 'white');
		Context.game.clubs.find(c => c.name === "CFR Cluj" && c.country.name === "Romania").setColors('rgb(115,46,45)', 'white');
		Context.game.clubs.find(c => c.name === "Danubio" && c.country.name === "Uruguay").setColors('rgb(155,155,154)', 'black');
		Context.game.clubs.find(c => c.name === "Daegu" && c.country.name === "Korea Republic").setColors('rgb(132,178,198)', 'black');
		Context.game.clubs.find(c => c.name === "Club Brugge" && c.country.name === "Belgium").setColors('rgb(42,82,122)', 'white');
		Context.game.clubs.find(c => c.name === "DC United" && c.country.name === "United States").setColors('rgb(61,58,58)', 'white');
		Context.game.clubs.find(c => c.name === "Chaves" && c.country.name === "Portugal").setColors('rgb(76,82,139)', 'white');
		Context.game.clubs.find(c => c.name === "Delfin" && c.country.name === "Ecuador").setColors('rgb(72,82,145)', 'white');
		Context.game.clubs.find(c => c.name === "Chennaiyin" && c.country.name === "India").setColors('rgb(57,62,140)', 'white');
		Context.game.clubs.find(c => c.name === "Cincinnati" && c.country.name === "United States").setColors('rgb(54,73,117)', 'white');
		Context.game.clubs.find(c => c.name === "Cosenza" && c.country.name === "Italy").setColors('rgb(115,49,59)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Cuenca" && c.country.name === "Ecuador").setColors('rgb(154,73,68)', 'white');
		Context.game.clubs.find(c => c.name === "Cremonese" && c.country.name === "Italy").setColors('rgb(176,77,87)', 'white');
		Context.game.clubs.find(c => c.name === "Dalian Professional" && c.country.name === "China PR").setColors('rgb(47,150,206)', 'black');
		Context.game.clubs.find(c => c.name === "Darmstadt 98" && c.country.name === "Germany").setColors('rgb(50,72,115)', 'white');
		Context.game.clubs.find(c => c.name === "Colorado Rapids" && c.country.name === "United States").setColors('rgb(83,52,59)', 'white');
		Context.game.clubs.find(c => c.name === "Cobresal" && c.country.name === "Chile").setColors('rgb(200,150,140)', 'black');
		Context.game.clubs.find(c => c.name === "Derry City" && c.country.name === "Republic of Ireland").setColors('rgb(204,76,79)', 'white');
		Context.game.clubs.find(c => c.name === "Defensa y Justicia" && c.country.name === "Argentina").setColors('rgb(214,185,62)', 'black');
		Context.game.clubs.find(c => c.name === "Deportes Tolima" && c.country.name === "Colombia").setColors('rgb(187,116,88)', 'black');
		Context.game.clubs.find(c => c.name === "Doncaster Rovers" && c.country.name === "England").setColors('rgb(196,129,133)', 'black');
		Context.game.clubs.find(c => c.name === "Dundee United" && c.country.name === "Scotland").setColors('rgb(205,92,40)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Pereira" && c.country.name === "Colombia").setColors('rgb(190,115,44)', 'black');
		Context.game.clubs.find(c => c.name === "Elversberg" && c.country.name === "Germany").setColors('rgb(185,184,181)', 'black');
		Context.game.clubs.find(c => c.name === "Eintracht Braunschweig" && c.country.name === "Germany").setColors('rgb(159,152,81)', 'black');
		Context.game.clubs.find(c => c.name === "FC Köln" && c.country.name === "Germany").setColors('rgb(198,118,119)', 'black');
		Context.game.clubs.find(c => c.name === "Dijon" && c.country.name === "France").setColors('rgb(171,60,65)', 'white');
		Context.game.clubs.find(c => c.name === "Espanyol" && c.country.name === "Spain").setColors('rgb(98,143,195)', 'black');
		Context.game.clubs.find(c => c.name === "Fatih Karagümrük" && c.country.name === "Turkey").setColors('rgb(99,41,48)', 'white');
		Context.game.clubs.find(c => c.name === "Everton" && c.country.name === "England").setColors('rgb(48,79,120)', 'white');
		Context.game.clubs.find(c => c.name === "FC Bayern München" && c.country.name === "Germany").setColors('rgb(196,54,55)', 'white');
		Context.game.clubs.find(c => c.name === "Defensor Sporting" && c.country.name === "Uruguay").setColors('rgb(109,86,149)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Alavés" && c.country.name === "Spain").setColors('rgb(128,145,169)', 'black');
		Context.game.clubs.find(c => c.name === "Drogheda United" && c.country.name === "Republic of Ireland").setColors('rgb(155,77,96)', 'white');
		Context.game.clubs.find(c => c.name === "Dynamo Dresden" && c.country.name === "Germany").setColors('rgb(186,130,51)', 'black');
		Context.game.clubs.find(c => c.name === "Deportivo Táchira" && c.country.name === "Venezuela").setColors('rgb(140,119,60)', 'white');
		Context.game.clubs.find(c => c.name === "Eintracht Frankfurt" && c.country.name === "Germany").setColors('rgb(199,198,197)', 'black');
		Context.game.clubs.find(c => c.name === "Dinamo Zagreb" && c.country.name === "Croatia").setColors('rgb(56,65,115)', 'white');
		Context.game.clubs.find(c => c.name === "FC Twente" && c.country.name === "Netherlands").setColors('rgb(218,76,79)', 'white');
		Context.game.clubs.find(c => c.name === "Emelec" && c.country.name === "Ecuador").setColors('rgb(76,90,140)', 'white');
		Context.game.clubs.find(c => c.name === "Estoril" && c.country.name === "Portugal").setColors('rgb(206,167,46)', 'black');
		Context.game.clubs.find(c => c.name === "FC Andorra" && c.country.name === "Spain").setColors('rgb(144,111,102)', 'white');
		Context.game.clubs.find(c => c.name === "FC Cartagena" && c.country.name === "Spain").setColors('rgb(119,118,117)', 'white');
		Context.game.clubs.find(c => c.name === "Excelsior" && c.country.name === "Netherlands").setColors('rgb(62,50,50)', 'white');
		Context.game.clubs.find(c => c.name === "FC Volendam" && c.country.name === "Netherlands").setColors('rgb(175,112,73)', 'white');
		Context.game.clubs.find(c => c.name === "Degerfors" && c.country.name === "Sweden").setColors('rgb(210,62,66)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Binacional" && c.country.name === "Peru").setColors('rgb(70,137,220)', 'black');
		Context.game.clubs.find(c => c.name === "DSC Arminia Bielefeld" && c.country.name === "Germany").setColors('rgb(53,77,124)', 'white');
		Context.game.clubs.find(c => c.name === "Dynamo Kyiv" && c.country.name === "Ukraine").setColors('rgb(171,179,196)', 'black');
		Context.game.clubs.find(c => c.name === "Derby County" && c.country.name === "England").setColors('rgb(181,180,179)', 'black');
		Context.game.clubs.find(c => c.name === "Djurgården" && c.country.name === "Sweden").setColors('rgb(75,114,143)', 'white');
		Context.game.clubs.find(c => c.name === "Elche" && c.country.name === "Spain").setColors('rgb(198,201,196)', 'black');
		Context.game.clubs.find(c => c.name === "FC Augsburg" && c.country.name === "Germany").setColors('rgb(164,90,88)', 'white');
		Context.game.clubs.find(c => c.name === "Estudiantes" && c.country.name === "Argentina").setColors('rgb(205,124,125)', 'black');
		Context.game.clubs.find(c => c.name === "Empoli" && c.country.name === "Italy").setColors('rgb(51,104,155)', 'white');
		Context.game.clubs.find(c => c.name === "FC Union Berlin" && c.country.name === "Germany").setColors('rgb(199,106,106)', 'black');
		Context.game.clubs.find(c => c.name === "FC Emmen" && c.country.name === "Netherlands").setColors('rgb(213,123,131)', 'black');
		Context.game.clubs.find(c => c.name === "Exeter City" && c.country.name === "England").setColors('rgb(205,107,107)', 'black');
		Context.game.clubs.find(c => c.name === "FCSB" && c.country.name === "Romania").setColors('rgb(230,59,71)', 'white');
		Context.game.clubs.find(c => c.name === "Fenerbahçe" && c.country.name === "Turkey").setColors('rgb(139,138,83)', 'black');
		Context.game.clubs.find(c => c.name === "Fiorentina" && c.country.name === "Italy").setColors('rgb(74,52,95)', 'white');
		Context.game.clubs.find(c => c.name === "East Bengal" && c.country.name === "India").setColors('rgb(201,93,48)', 'white');
		Context.game.clubs.find(c => c.name === "Forest Green Rovers" && c.country.name === "England").setColors('rgb(116,149,63)', 'black');
		Context.game.clubs.find(c => c.name === "Freiburg II" && c.country.name === "Germany").setColors('rgb(167,76,80)', 'white');
		Context.game.clubs.find(c => c.name === "Dundalk" && c.country.name === "Republic of Ireland").setColors('rgb(187,184,183)', 'black');
		Context.game.clubs.find(c => c.name === "FC Utrecht" && c.country.name === "Netherlands").setColors('rgb(186,133,136)', 'black');
		Context.game.clubs.find(c => c.name === "Erzgebirge Aue" && c.country.name === "Germany").setColors('rgb(81,64,119)', 'white');
		Context.game.clubs.find(c => c.name === "Estudiantes Mérida" && c.country.name === "Venezuela").setColors('rgb(190,143,148)', 'black');
		Context.game.clubs.find(c => c.name === "Famalicão" && c.country.name === "Portugal").setColors('rgb(196,196,196)', 'black');
		Context.game.clubs.find(c => c.name === "Ferencváros" && c.country.name === "Hungary").setColors('rgb(138,153,143)', 'black');
		Context.game.clubs.find(c => c.name === "FC Barcelona" && c.country.name === "Spain").setColors('rgb(78,56,84)', 'white');
		Context.game.clubs.find(c => c.name === "Elfsborg" && c.country.name === "Sweden").setColors('rgb(197,147,33)', 'black');
		Context.game.clubs.find(c => c.name === "FC Groningen" && c.country.name === "Netherlands").setColors('rgb(146,176,153)', 'black');
		Context.game.clubs.find(c => c.name === "Flamengo" && c.country.name === "Brazil").setColors('rgb(126,55,58)', 'white');
		Context.game.clubs.find(c => c.name === "Galatasaray" && c.country.name === "Turkey").setColors('rgb(157,90,58)', 'white');
		Context.game.clubs.find(c => c.name === "Fortaleza" && c.country.name === "Brazil").setColors('rgb(125,86,116)', 'white');
		Context.game.clubs.find(c => c.name === "Frosinone" && c.country.name === "Italy").setColors('rgb(166,152,56)', 'black');
		Context.game.clubs.find(c => c.name === "Gangwon" && c.country.name === "Korea Republic").setColors('rgb(227,99,70)', 'black');
		Context.game.clubs.find(c => c.name === "Genoa" && c.country.name === "Italy").setColors('rgb(119,57,61)', 'white');
		Context.game.clubs.find(c => c.name === "Feyenoord" && c.country.name === "Netherlands").setColors('rgb(176,120,123)', 'black');
		Context.game.clubs.find(c => c.name === "Giresunspor" && c.country.name === "Turkey").setColors('rgb(105,139,130)', 'white');
		Context.game.clubs.find(c => c.name === "Gil Vicente" && c.country.name === "Portugal").setColors('rgb(191,48,50)', 'white');
		Context.game.clubs.find(c => c.name === "Fleetwood Town" && c.country.name === "England").setColors('rgb(182,84,90)', 'white');
		Context.game.clubs.find(c => c.name === "Guangzhou" && c.country.name === "China PR").setColors('rgb(168,56,60)', 'white');
		Context.game.clubs.find(c => c.name === "Godoy Cruz" && c.country.name === "Argentina").setColors('rgb(72,106,176)', 'white');
		Context.game.clubs.find(c => c.name === "Häcken" && c.country.name === "Sweden").setColors('rgb(105,93,45)', 'white');
		Context.game.clubs.find(c => c.name === "Grasshopper" && c.country.name === "Switzerland").setColors('rgb(130,139,170)', 'black');
		Context.game.clubs.find(c => c.name === "HamKam" && c.country.name === "Norway").setColors('rgb(221,228,224)', 'black');
		Context.game.clubs.find(c => c.name === "Harrogate Town" && c.country.name === "England").setColors('rgb(200,158,60)', 'black');
		Context.game.clubs.find(c => c.name === "Fortuna Düsseldorf" && c.country.name === "Germany").setColors('rgb(147,47,55)', 'white');
		Context.game.clubs.find(c => c.name === "FSV Mainz 05" && c.country.name === "Germany").setColors('rgb(174,44,55)', 'white');
		Context.game.clubs.find(c => c.name === "Gaziantep F.K." && c.country.name === "Turkey").setColors('rgb(123,47,57)', 'white');
		Context.game.clubs.find(c => c.name === "Gent" && c.country.name === "Belgium").setColors('rgb(119,131,163)', 'white');
		Context.game.clubs.find(c => c.name === "Finn Harps" && c.country.name === "Republic of Ireland").setColors('rgb(50,111,189)', 'white');
		Context.game.clubs.find(c => c.name === "Fluminense" && c.country.name === "Brazil").setColors('rgb(111,86,93)', 'white');
		Context.game.clubs.find(c => c.name === "Girona" && c.country.name === "Spain").setColors('rgb(185,99,102)', 'white');
		Context.game.clubs.find(c => c.name === "Gillingham" && c.country.name === "England").setColors('rgb(53,108,169)', 'white');
		Context.game.clubs.find(c => c.name === "Grenoble Foot 38" && c.country.name === "France").setColors('rgb(60,96,155)', 'white');
		Context.game.clubs.find(c => c.name === "Guangzhou City" && c.country.name === "China PR").setColors('rgb(153,172,183)', 'black');
		Context.game.clubs.find(c => c.name === "Hajduk Split" && c.country.name === "Croatia").setColors('rgb(227,219,220)', 'black');
		Context.game.clubs.find(c => c.name === "Fortuna Sittard" && c.country.name === "Netherlands").setColors('rgb(218,208,36)', 'black');
		Context.game.clubs.find(c => c.name === "Hammarby" && c.country.name === "Sweden").setColors('rgb(211,218,209)', 'black');
		Context.game.clubs.find(c => c.name === "Hartberg" && c.country.name === "Austria").setColors('rgb(66,92,142)', 'white');
		Context.game.clubs.find(c => c.name === "Fulham" && c.country.name === "England").setColors('rgb(206,204,202)', 'black');
		Context.game.clubs.find(c => c.name === "Goiás" && c.country.name === "Brazil").setColors('rgb(46,76,74)', 'white');
		Context.game.clubs.find(c => c.name === "General Caballero JLM" && c.country.name === "Paraguay").setColors('rgb(210,68,73)', 'white');
		Context.game.clubs.find(c => c.name === "Hartlepool United" && c.country.name === "England").setColors('rgb(137,148,174)', 'black');
		Context.game.clubs.find(c => c.name === "Henan" && c.country.name === "China PR").setColors('rgb(133,48,57)', 'white');
		Context.game.clubs.find(c => c.name === "Gimcheon Sangmu" && c.country.name === "Korea Republic").setColors('rgb(162,66,75)', 'white');
		Context.game.clubs.find(c => c.name === "Getafe" && c.country.name === "Spain").setColors('rgb(43,72,152)', 'white');
		Context.game.clubs.find(c => c.name === "Huddersfield Town" && c.country.name === "England").setColors('rgb(114,142,177)', 'black');
		Context.game.clubs.find(c => c.name === "Grimsby Town" && c.country.name === "England").setColors('rgb(126,124,123)', 'white');
		Context.game.clubs.find(c => c.name === "Go Ahead Eagles" && c.country.name === "Netherlands").setColors('rgb(201,108,42)', 'black');
		Context.game.clubs.find(c => c.name === "Guaraní" && c.country.name === "Paraguay").setColors('rgb(112,97,40)', 'white');
		Context.game.clubs.find(c => c.name === "Hallescher FC" && c.country.name === "Germany").setColors('rgb(202,39,48)', 'white');
		Context.game.clubs.find(c => c.name === "Hannover 96" && c.country.name === "Germany").setColors('rgb(176,62,64)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente del Valle" && c.country.name === "Ecuador").setColors('rgb(45,46,50)', 'white');
		Context.game.clubs.find(c => c.name === "Górnik Zabrze" && c.country.name === "Poland").setColors('rgb(188,187,188)', 'black');
		Context.game.clubs.find(c => c.name === "Ingolstadt" && c.country.name === "Germany").setColors('rgb(120,40,51)', 'white');
		Context.game.clubs.find(c => c.name === "Genk" && c.country.name === "Belgium").setColors('rgb(46,89,174)', 'white');
		Context.game.clubs.find(c => c.name === "Hatayspor" && c.country.name === "Turkey").setColors('rgb(166,131,133)', 'black');
		Context.game.clubs.find(c => c.name === "Hermannstadt" && c.country.name === "Romania").setColors('rgb(202,201,199)', 'black');
		Context.game.clubs.find(c => c.name === "Huesca" && c.country.name === "Spain").setColors('rgb(100,56,78)', 'white');
		Context.game.clubs.find(c => c.name === "Guabirá" && c.country.name === "Bolivia").setColors('rgb(186,39,48)', 'white');
		Context.game.clubs.find(c => c.name === "Gimnasia La Plata" && c.country.name === "Argentina").setColors('rgb(184,184,192)', 'black');
		Context.game.clubs.find(c => c.name === "Inter" && c.country.name === "Italy").setColors('rgb(53,61,94)', 'white');
		Context.game.clubs.find(c => c.name === "Goa" && c.country.name === "India").setColors('rgb(229,105,54)', 'black');
		Context.game.clubs.find(c => c.name === "Hansa Rostock" && c.country.name === "Germany").setColors('rgb(49,70,110)', 'white');
		Context.game.clubs.find(c => c.name === "Guingamp" && c.country.name === "France").setColors('rgb(168,38,40)', 'white');
		Context.game.clubs.find(c => c.name === "Granada" && c.country.name === "Spain").setColors('rgb(179,106,119)', 'white');
		Context.game.clubs.find(c => c.name === "GIF Sundsvall" && c.country.name === "Sweden").setColors('rgb(47,78,153)', 'white');
		Context.game.clubs.find(c => c.name === "Hamburger SV" && c.country.name === "Germany").setColors('rgb(174,178,183)', 'black');
		Context.game.clubs.find(c => c.name === "Independiente Medellín" && c.country.name === "Colombia").setColors('rgb(132,45,47)', 'white');
		Context.game.clubs.find(c => c.name === "Hertha BSC" && c.country.name === "Germany").setColors('rgb(139,144,161)', 'black');
		Context.game.clubs.find(c => c.name === "Haugesund" && c.country.name === "Norway").setColors('rgb(176,191,204)', 'black');
		Context.game.clubs.find(c => c.name === "Jahn Regensburg" && c.country.name === "Germany").setColors('rgb(210,196,191)', 'black');
		Context.game.clubs.find(c => c.name === "Hull City" && c.country.name === "England").setColors('rgb(120,80,47)', 'white');
		Context.game.clubs.find(c => c.name === "Kaizer Chiefs" && c.country.name === "South Africa").setColors('rgb(191,136,57)', 'black');
		Context.game.clubs.find(c => c.name === "Inter Miami" && c.country.name === "United States").setColors('rgb(187,151,172)', 'black');
		Context.game.clubs.find(c => c.name === "Konyaspor" && c.country.name === "Turkey").setColors('rgb(102,141,128)', 'black');
		Context.game.clubs.find(c => c.name === "Lille" && c.country.name === "France").setColors('rgb(164,63,72)', 'white');
		Context.game.clubs.find(c => c.name === "Lugano" && c.country.name === "Switzerland").setColors('rgb(83,70,70)', 'white');
		Context.game.clubs.find(c => c.name === "LASK Linz" && c.country.name === "Austria").setColors('rgb(156,146,122)', 'black');
		Context.game.clubs.find(c => c.name === "Mechelen" && c.country.name === "Belgium").setColors('rgb(190,131,55)', 'black');
		Context.game.clubs.find(c => c.name === "Leeds United" && c.country.name === "England").setColors('rgb(191,191,190)', 'black');
		Context.game.clubs.find(c => c.name === "Hearts" && c.country.name === "Scotland").setColors('rgb(83,56,62)', 'white');
		Context.game.clubs.find(c => c.name === "Málaga" && c.country.name === "Spain").setColors('rgb(102,161,193)', 'black');
		Context.game.clubs.find(c => c.name === "Hibernian" && c.country.name === "Scotland").setColors('rgb(75,119,90)', 'white');
		Context.game.clubs.find(c => c.name === "Middlesbrough" && c.country.name === "England").setColors('rgb(205,67,83)', 'white');
		Context.game.clubs.find(c => c.name === "Huracán" && c.country.name === "Argentina").setColors('rgb(203,196,197)', 'black');
		Context.game.clubs.find(c => c.name === "Jamshedpur" && c.country.name === "India").setColors('rgb(142,64,74)', 'white');
		Context.game.clubs.find(c => c.name === "Internacional" && c.country.name === "Brazil").setColors('rgb(200,59,66)', 'white');
		Context.game.clubs.find(c => c.name === "Kalmar" && c.country.name === "Sweden").setColors('rgb(224,65,77)', 'white');
		Context.game.clubs.find(c => c.name === "Lillestrøm" && c.country.name === "Norway").setColors('rgb(222,195,32)', 'black');
		Context.game.clubs.find(c => c.name === "Laval" && c.country.name === "France").setColors('rgb(194,104,61)', 'white');
		Context.game.clubs.find(c => c.name === "Korona Kielce" && c.country.name === "Poland").setColors('rgb(217,102,45)', 'black');
		Context.game.clubs.find(c => c.name === "Lugo" && c.country.name === "Spain").setColors('rgb(187,110,112)', 'black');
		Context.game.clubs.find(c => c.name === "Hebei" && c.country.name === "China PR").setColors('rgb(159,54,44)', 'white');
		Context.game.clubs.find(c => c.name === "Meizhou Hakka" && c.country.name === "China PR").setColors('rgb(144,53,61)', 'white');
		Context.game.clubs.find(c => c.name === "Leganés" && c.country.name === "Spain").setColors('rgb(168,188,215)', 'black');
		Context.game.clubs.find(c => c.name === "HJK" && c.country.name === "Finland").setColors('rgb(158,154,175)', 'black');
		Context.game.clubs.find(c => c.name === "Midtjylland" && c.country.name === "Denmark").setColors('rgb(52,45,44)', 'white');
		Context.game.clubs.find(c => c.name === "Hyderabad" && c.country.name === "India").setColors('rgb(188,159,35)', 'black');
		Context.game.clubs.find(c => c.name === "Mallorca" && c.country.name === "Spain").setColors('rgb(133,42,44)', 'white');
		Context.game.clubs.find(c => c.name === "Ipswich Town" && c.country.name === "England").setColors('rgb(58,69,116)', 'white');
		Context.game.clubs.find(c => c.name === "Jeju United" && c.country.name === "Korea Republic").setColors('rgb(235,120,61)', 'black');
		Context.game.clubs.find(c => c.name === "Karlsruher SC" && c.country.name === "Germany").setColors('rgb(45,66,124)', 'white');
		Context.game.clubs.find(c => c.name === "Luton Town" && c.country.name === "England").setColors('rgb(184,82,70)', 'white');
		Context.game.clubs.find(c => c.name === "Lincoln City" && c.country.name === "England").setColors('rgb(192,115,123)', 'black');
		Context.game.clubs.find(c => c.name === "Lazio" && c.country.name === "Italy").setColors('rgb(103,201,210)', 'black');
		Context.game.clubs.find(c => c.name === "Heidenheim" && c.country.name === "Germany").setColors('rgb(147,57,84)', 'white');
		Context.game.clubs.find(c => c.name === "Kortrijk" && c.country.name === "Belgium").setColors('rgb(197,56,61)', 'white');
		Context.game.clubs.find(c => c.name === "Holstein Kiel" && c.country.name === "Germany").setColors('rgb(95,99,137)', 'white');
		Context.game.clubs.find(c => c.name === "Legia Warszawa" && c.country.name === "Poland").setColors('rgb(202,202,201)', 'black');
		Context.game.clubs.find(c => c.name === "Melbourne City" && c.country.name === "Australia").setColors('rgb(112,150,179)', 'black');
		Context.game.clubs.find(c => c.name === "IFK Göteborg" && c.country.name === "Sweden").setColors('rgb(106,107,170)', 'white');
		Context.game.clubs.find(c => c.name === "Miedź Legnica" && c.country.name === "Poland").setColors('rgb(49,67,156)', 'white');
		Context.game.clubs.find(c => c.name === "Malmö FF" && c.country.name === "Sweden").setColors('rgb(104,167,214)', 'black');
		Context.game.clubs.find(c => c.name === "İstanbul Başakşehir" && c.country.name === "Turkey").setColors('rgb(217,87,48)', 'white');
		Context.game.clubs.find(c => c.name === "Jeonbuk Motors" && c.country.name === "Korea Republic").setColors('rgb(58,108,79)', 'white');
		Context.game.clubs.find(c => c.name === "Kasımpaşa" && c.country.name === "Turkey").setColors('rgb(105,108,116)', 'white');
		Context.game.clubs.find(c => c.name === "Luzern" && c.country.name === "Switzerland").setColors('rgb(72,59,82)', 'white');
		Context.game.clubs.find(c => c.name === "LDU Quito" && c.country.name === "Ecuador").setColors('rgb(190,190,187)', 'black');
		Context.game.clubs.find(c => c.name === "Hellas Verona" && c.country.name === "Italy").setColors('rgb(49,70,106)', 'white');
		Context.game.clubs.find(c => c.name === "Liverpool" && c.country.name === "England").setColors('rgb(149,44,47)', 'white');
		Context.game.clubs.find(c => c.name === "Horsens" && c.country.name === "Denmark").setColors('rgb(169,139,49)', 'black');
		Context.game.clubs.find(c => c.name === "Melbourne Victory" && c.country.name === "Australia").setColors('rgb(43,50,59)', 'white');
		Context.game.clubs.find(c => c.name === "Kristiansund" && c.country.name === "Norway").setColors('rgb(67,69,86)', 'white');
		Context.game.clubs.find(c => c.name === "İstanbulspor" && c.country.name === "Turkey").setColors('rgb(198,172,30)', 'black');
		Context.game.clubs.find(c => c.name === "Incheon United" && c.country.name === "Korea Republic").setColors('rgb(57,70,130)', 'white');
		Context.game.clubs.find(c => c.name === "Leicester City" && c.country.name === "England").setColors('rgb(66,94,144)', 'white');
		Context.game.clubs.find(c => c.name === "Milan" && c.country.name === "Italy").setColors('rgb(84,43,42)', 'white');
		Context.game.clubs.find(c => c.name === "Mamelodi Sundowns" && c.country.name === "South Africa").setColors('rgb(212,186,39)', 'black');
		Context.game.clubs.find(c => c.name === "Kayserispor" && c.country.name === "Turkey").setColors('rgb(184,76,45)', 'white');
		Context.game.clubs.find(c => c.name === "Helsingborg" && c.country.name === "Sweden").setColors('rgb(221,38,44)', 'white');
		Context.game.clubs.find(c => c.name === "Jerv" && c.country.name === "Norway").setColors('rgb(224,168,80)', 'black');
		Context.game.clubs.find(c => c.name === "Lyngby" && c.country.name === "Denmark").setColors('rgb(78,90,140)', 'white');
		Context.game.clubs.find(c => c.name === "Houston Dynamo" && c.country.name === "United States").setColors('rgb(184,70,49)', 'white');
		Context.game.clubs.find(c => c.name === "Liverpool" && c.country.name === "Uruguay").setColors('rgb(56,82,124)', 'white');
		Context.game.clubs.find(c => c.name === "Le Havre" && c.country.name === "France").setColors('rgb(88,118,139)', 'white');
		Context.game.clubs.find(c => c.name === "Melgar" && c.country.name === "Peru").setColors('rgb(119,43,46)', 'white');
		Context.game.clubs.find(c => c.name === "Jagiellonia Białystok" && c.country.name === "Poland").setColors('rgb(194,95,74)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente" && c.country.name === "Argentina").setColors('rgb(205,36,36)', 'white');
		Context.game.clubs.find(c => c.name === "Millonarios" && c.country.name === "Colombia").setColors('rgb(54,77,146)', 'white');
		Context.game.clubs.find(c => c.name === "KV Oostende" && c.country.name === "Belgium").setColors('rgb(166,67,61)', 'white');
		Context.game.clubs.find(c => c.name === "Lens" && c.country.name === "France").setColors('rgb(208,144,46)', 'black');
		Context.game.clubs.find(c => c.name === "Manchester City" && c.country.name === "England").setColors('rgb(105,153,193)', 'black');
		Context.game.clubs.find(c => c.name === "Kerala Blasters" && c.country.name === "India").setColors('rgb(201,185,50)', 'black');
		Context.game.clubs.find(c => c.name === "Milton Keynes Dons" && c.country.name === "England").setColors('rgb(186,185,184)', 'black');
		Context.game.clubs.find(c => c.name === "Monagas" && c.country.name === "Venezuela").setColors('rgb(81,66,80)', 'white');
		Context.game.clubs.find(c => c.name === "Junior" && c.country.name === "Colombia").setColors('rgb(186,130,140)', 'black');
		Context.game.clubs.find(c => c.name === "Lecce" && c.country.name === "Italy").setColors('rgb(199,102,55)', 'white');
		Context.game.clubs.find(c => c.name === "Macarthur" && c.country.name === "Australia").setColors('rgb(143,139,113)', 'black');
		Context.game.clubs.find(c => c.name === "Livingston" && c.country.name === "Scotland").setColors('rgb(200,162,37)', 'black');
		Context.game.clubs.find(c => c.name === "Nantes" && c.country.name === "France").setColors('rgb(219,190,57)', 'black');
		Context.game.clubs.find(c => c.name === "Meppen" && c.country.name === "Germany").setColors('rgb(67,101,160)', 'white');
		Context.game.clubs.find(c => c.name === "Millwall" && c.country.name === "England").setColors('rgb(57,61,82)', 'white');
		Context.game.clubs.find(c => c.name === "Newcastle United" && c.country.name === "England").setColors('rgb(127,133,136)', 'black');
		Context.game.clubs.find(c => c.name === "LA Galaxy" && c.country.name === "United States").setColors('rgb(188,187,187)', 'black');
		Context.game.clubs.find(c => c.name === "Levante" && c.country.name === "Spain").setColors('rgb(77,46,65)', 'white');
		Context.game.clubs.find(c => c.name === "Manchester United" && c.country.name === "England").setColors('rgb(188,48,68)', 'white');
		Context.game.clubs.find(c => c.name === "Minnesota United" && c.country.name === "United States").setColors('rgb(66,67,68)', 'white');
		Context.game.clubs.find(c => c.name === "Montpellier" && c.country.name === "France").setColors('rgb(74,65,77)', 'white');
		Context.game.clubs.find(c => c.name === "Kilmarnock" && c.country.name === "Scotland").setColors('rgb(83,120,173)', 'white');
		Context.game.clubs.find(c => c.name === "Napoli" && c.country.name === "Italy").setColors('rgb(50,106,191)', 'white');
		Context.game.clubs.find(c => c.name === "Juventus" && c.country.name === "Italy").setColors('rgb(148,147,147)', 'black');
		Context.game.clubs.find(c => c.name === "Metropolitanos" && c.country.name === "Venezuela").setColors('rgb(75,72,140)', 'white');
		Context.game.clubs.find(c => c.name === "Lorient" && c.country.name === "France").setColors('rgb(195,101,44)', 'white');
		Context.game.clubs.find(c => c.name === "Magallanes" && c.country.name === "Chile").setColors('rgb(141,181,204)', 'black');
		Context.game.clubs.find(c => c.name === "Lech Poznań" && c.country.name === "Poland").setColors('rgb(47,73,129)', 'white');
		Context.game.clubs.find(c => c.name === "Newell's Old Boys" && c.country.name === "Argentina").setColors('rgb(113,53,52)', 'white');
		Context.game.clubs.find(c => c.name === "Northampton Town" && c.country.name === "England").setColors('rgb(172,147,146)', 'black');
		Context.game.clubs.find(c => c.name === "Lanús" && c.country.name === "Argentina").setColors('rgb(124,66,77)', 'white');
		Context.game.clubs.find(c => c.name === "Leyton Orient" && c.country.name === "England").setColors('rgb(155,42,46)', 'white');
		Context.game.clubs.find(c => c.name === "Mioveni" && c.country.name === "Romania").setColors('rgb(204,178,84)', 'black');
		Context.game.clubs.find(c => c.name === "Monza" && c.country.name === "Italy").setColors('rgb(195,65,72)', 'white');
		Context.game.clubs.find(c => c.name === "Mansfield Town" && c.country.name === "England").setColors('rgb(184,129,55)', 'black');
		Context.game.clubs.find(c => c.name === "Nashville SC" && c.country.name === "United States").setColors('rgb(196,193,72)', 'black');
		Context.game.clubs.find(c => c.name === "København" && c.country.name === "Denmark").setColors('rgb(198,200,204)', 'black');
		Context.game.clubs.find(c => c.name === "Kaiserslautern" && c.country.name === "Germany").setColors('rgb(169,49,51)', 'white');
		Context.game.clubs.find(c => c.name === "Metz" && c.country.name === "France").setColors('rgb(93,41,41)', 'white');
		Context.game.clubs.find(c => c.name === "Newport County" && c.country.name === "England").setColors('rgb(177,122,50)', 'black');
		Context.game.clubs.find(c => c.name === "Lechia Gdańsk" && c.country.name === "Poland").setColors('rgb(98,142,121)', 'black');
		Context.game.clubs.find(c => c.name === "Magdeburg" && c.country.name === "Germany").setColors('rgb(74,117,183)', 'white');
		Context.game.clubs.find(c => c.name === "NorthEast United" && c.country.name === "India").setColors('rgb(199,196,197)', 'black');
		Context.game.clubs.find(c => c.name === "Morecambe" && c.country.name === "England").setColors('rgb(150,64,69)', 'white');
		Context.game.clubs.find(c => c.name === "Los Angeles FC" && c.country.name === "United States").setColors('rgb(54,53,51)', 'white');
		Context.game.clubs.find(c => c.name === "Mirandés" && c.country.name === "Spain").setColors('rgb(115,46,53)', 'white');
		Context.game.clubs.find(c => c.name === "Marítimo" && c.country.name === "Portugal").setColors('rgb(110,86,70)', 'white');
		Context.game.clubs.find(c => c.name === "Libertad" && c.country.name === "Paraguay").setColors('rgb(153,153,152)', 'black');
		Context.game.clubs.find(c => c.name === "Las Palmas" && c.country.name === "Spain").setColors('rgb(214,185,39)', 'black');
		Context.game.clubs.find(c => c.name === "NEC" && c.country.name === "Netherlands").setColors('rgb(169,53,61)', 'white');
		Context.game.clubs.find(c => c.name === "Paderborn" && c.country.name === "Germany").setColors('rgb(49,66,99)', 'white');
		Context.game.clubs.find(c => c.name === "Olympique Lyonnais" && c.country.name === "France").setColors('rgb(193,182,184)', 'black');
		Context.game.clubs.find(c => c.name === "Ñublense" && c.country.name === "Chile").setColors('rgb(171,55,67)', 'white');
		Context.game.clubs.find(c => c.name === "Nice" && c.country.name === "France").setColors('rgb(78,48,48)', 'white');
		Context.game.clubs.find(c => c.name === "Paris Saint Germain" && c.country.name === "France").setColors('rgb(100,95,108)', 'white');
		Context.game.clubs.find(c => c.name === "Norwich City" && c.country.name === "England").setColors('rgb(208,206,64)', 'black');
		Context.game.clubs.find(c => c.name === "Mjällby" && c.country.name === "Sweden").setColors('rgb(230,202,50)', 'black');
		Context.game.clubs.find(c => c.name === "Motherwell" && c.country.name === "Scotland").setColors('rgb(182,104,58)', 'white');
		Context.game.clubs.find(c => c.name === "Petrolul 52" && c.country.name === "Romania").setColors('rgb(211,192,44)', 'black');
		Context.game.clubs.find(c => c.name === "Queens Park Rangers" && c.country.name === "England").setColors('rgb(130,158,185)', 'black');
		Context.game.clubs.find(c => c.name === "Ponferradina" && c.country.name === "Spain").setColors('rgb(112,119,149)', 'white');
		Context.game.clubs.find(c => c.name === "New England" && c.country.name === "United States").setColors('rgb(59,61,78)', 'white');
		Context.game.clubs.find(c => c.name === "Real Salt Lake" && c.country.name === "United States").setColors('rgb(116,58,67)', 'white');
		Context.game.clubs.find(c => c.name === "Palermo" && c.country.name === "Italy").setColors('rgb(171,127,145)', 'black');
		Context.game.clubs.find(c => c.name === "Oriente Petrolero" && c.country.name === "Bolivia").setColors('rgb(159,176,160)', 'black');
		Context.game.clubs.find(c => c.name === "Nîmes" && c.country.name === "France").setColors('rgb(205,56,68)', 'white');
		Context.game.clubs.find(c => c.name === "Nürnberg" && c.country.name === "Germany").setColors('rgb(83,50,53)', 'white');
		Context.game.clubs.find(c => c.name === "Rapid Bucuresti" && c.country.name === "Romania").setColors('rgb(131,57,77)', 'white');
		Context.game.clubs.find(c => c.name === "Nottingham Forest" && c.country.name === "England").setColors('rgb(177,35,36)', 'white');
		Context.game.clubs.find(c => c.name === "Parma" && c.country.name === "Italy").setColors('rgb(157,156,154)', 'black');
		Context.game.clubs.find(c => c.name === "MSV Duisburg" && c.country.name === "Germany").setColors('rgb(138,136,143)', 'black');
		Context.game.clubs.find(c => c.name === "Modena" && c.country.name === "Italy").setColors('rgb(204,173,43)', 'black');
		Context.game.clubs.find(c => c.name === "Port Vale" && c.country.name === "England").setColors('rgb(181,181,180)', 'black');
		Context.game.clubs.find(c => c.name === "Philadelphia Union" && c.country.name === "United States").setColors('rgb(58,64,64)', 'white');
		Context.game.clubs.find(c => c.name === "New York City" && c.country.name === "United States").setColors('rgb(113,132,160)', 'white');
		Context.game.clubs.find(c => c.name === "Quevilly Rouen" && c.country.name === "France").setColors('rgb(210,46,46)', 'white');
		Context.game.clubs.find(c => c.name === "Real Sociedad" && c.country.name === "Spain").setColors('rgb(135,145,169)', 'black');
		Context.game.clubs.find(c => c.name === "Niort" && c.country.name === "France").setColors('rgb(54,84,148)', 'white');
		Context.game.clubs.find(c => c.name === "Orlando City" && c.country.name === "United States").setColors('rgb(70,66,139)', 'white');
		Context.game.clubs.find(c => c.name === "OB" && c.country.name === "Denmark").setColors('rgb(158,163,195)', 'black');
		Context.game.clubs.find(c => c.name === "Rapid Wien" && c.country.name === "Austria").setColors('rgb(122,152,134)', 'black');
		Context.game.clubs.find(c => c.name === "Palestino" && c.country.name === "Chile").setColors('rgb(149,114,109)', 'white');
		Context.game.clubs.find(c => c.name === "Ried" && c.country.name === "Austria").setColors('rgb(66,87,77)', 'white');
		Context.game.clubs.find(c => c.name === "Mumbai City" && c.country.name === "India").setColors('rgb(83,136,179)', 'white');
		Context.game.clubs.find(c => c.name === "Molde" && c.country.name === "Norway").setColors('rgb(59,84,148)', 'white');
		Context.game.clubs.find(c => c.name === "Patronato" && c.country.name === "Argentina").setColors('rgb(119,61,66)', 'white');
		Context.game.clubs.find(c => c.name === "Portimonense" && c.country.name === "Portugal").setColors('rgb(118,117,117)', 'white');
		Context.game.clubs.find(c => c.name === "Piast Gliwice" && c.country.name === "Poland").setColors('rgb(115,70,109)', 'white');
		Context.game.clubs.find(c => c.name === "New York RB" && c.country.name === "United States").setColors('rgb(163,51,60)', 'white');
		Context.game.clubs.find(c => c.name === "Racing Club" && c.country.name === "Argentina").setColors('rgb(144,179,195)', 'black');
		Context.game.clubs.find(c => c.name === "Odd" && c.country.name === "Norway").setColors('rgb(200,186,186)', 'black');
		Context.game.clubs.find(c => c.name === "Real Valladolid" && c.country.name === "Spain").setColors('rgb(147,127,145)', 'black');
		Context.game.clubs.find(c => c.name === "Nordsjælland" && c.country.name === "Denmark").setColors('rgb(189,51,47)', 'white');
		Context.game.clubs.find(c => c.name === "Orlando Pirates" && c.country.name === "South Africa").setColors('rgb(61,54,56)', 'white');
		Context.game.clubs.find(c => c.name === "Rayo Vallecano" && c.country.name === "Spain").setColors('rgb(189,156,154)', 'black');
		Context.game.clubs.find(c => c.name === "Palmaflor del Trópico" && c.country.name === "Bolivia").setColors('rgb(215,197,65)', 'black');
		Context.game.clubs.find(c => c.name === "Nacional" && c.country.name === "Uruguay").setColors('rgb(216,214,216)', 'black');
		Context.game.clubs.find(c => c.name === "Monaco" && c.country.name === "France").setColors('rgb(190,124,133)', 'black');
		Context.game.clubs.find(c => c.name === "Rio Ave" && c.country.name === "Portugal").setColors('rgb(93,147,134)', 'black');
		Context.game.clubs.find(c => c.name === "Pau" && c.country.name === "France").setColors('rgb(173,155,49)', 'black');
		Context.game.clubs.find(c => c.name === "Portland Timbers" && c.country.name === "United States").setColors('rgb(61,86,74)', 'white');
		Context.game.clubs.find(c => c.name === "Newcastle Jets" && c.country.name === "Australia").setColors('rgb(178,156,115)', 'black');
		Context.game.clubs.find(c => c.name === "Racing Santander" && c.country.name === "Spain").setColors('rgb(198,203,195)', 'black');
		Context.game.clubs.find(c => c.name === "Odisha FC" && c.country.name === "India").setColors('rgb(50,46,52)', 'white');
		Context.game.clubs.find(c => c.name === "Pisa" && c.country.name === "Italy").setColors('rgb(44,53,82)', 'white');
		Context.game.clubs.find(c => c.name === "Norrköping" && c.country.name === "Sweden").setColors('rgb(199,201,203)', 'black');
		Context.game.clubs.find(c => c.name === "Osasuna" && c.country.name === "Spain").setColors('rgb(127,45,53)', 'white');
		Context.game.clubs.find(c => c.name === "RB Leipzig" && c.country.name === "Germany").setColors('rgb(213,190,189)', 'black');
		Context.game.clubs.find(c => c.name === "Real Zaragoza" && c.country.name === "Spain").setColors('rgb(187,189,199)', 'black');
		Context.game.clubs.find(c => c.name === "River Plate" && c.country.name === "Uruguay").setColors('rgb(151,129,132)', 'black');
		Context.game.clubs.find(c => c.name === "Rot-Weiss Essen" && c.country.name === "Germany").setColors('rgb(205,189,185)', 'black');
		Context.game.clubs.find(c => c.name === "Palmeiras" && c.country.name === "Brazil").setColors('rgb(55,111,89)', 'white');
		Context.game.clubs.find(c => c.name === "Peñarol" && c.country.name === "Uruguay").setColors('rgb(123,109,45)', 'white');
		Context.game.clubs.find(c => c.name === "Rionegro Águilas" && c.country.name === "Colombia").setColors('rgb(195,175,124)', 'black');
		Context.game.clubs.find(c => c.name === "San Jose Earthquakes" && c.country.name === "United States").setColors('rgb(46,57,83)', 'white');
		Context.game.clubs.find(c => c.name === "Porto" && c.country.name === "Portugal").setColors('rgb(109,128,163)', 'white');
		Context.game.clubs.find(c => c.name === "OH Leuven" && c.country.name === "Belgium").setColors('rgb(205,201,199)', 'black');
		Context.game.clubs.find(c => c.name === "Radomiak Radom" && c.country.name === "Poland").setColors('rgb(53,90,65)', 'white');
		Context.game.clubs.find(c => c.name === "Sarmiento" && c.country.name === "Argentina").setColors('rgb(71,110,99)', 'white');
		Context.game.clubs.find(c => c.name === "Reading" && c.country.name === "England").setColors('rgb(126,144,174)', 'black');
		Context.game.clubs.find(c => c.name === "Osnabrück" && c.country.name === "Germany").setColors('rgb(106,74,134)', 'white');
		Context.game.clubs.find(c => c.name === "Platense" && c.country.name === "Argentina").setColors('rgb(186,185,183)', 'black');
		Context.game.clubs.find(c => c.name === "RKC Waalwijk" && c.country.name === "Netherlands").setColors('rgb(208,200,46)', 'black');
		Context.game.clubs.find(c => c.name === "Rotherham United" && c.country.name === "England").setColors('rgb(171,62,68)', 'white');
		Context.game.clubs.find(c => c.name === "Reggina" && c.country.name === "Italy").setColors('rgb(108,41,50)', 'white');
		Context.game.clubs.find(c => c.name === "Perth Glory" && c.country.name === "Australia").setColors('rgb(98,60,91)', 'white');
		Context.game.clubs.find(c => c.name === "San Lorenzo" && c.country.name === "Argentina").setColors('rgb(116,58,93)', 'white');
		Context.game.clubs.find(c => c.name === "Panathinaikos" && c.country.name === "Greece").setColors('rgb(123,146,131)', 'black');
		Context.game.clubs.find(c => c.name === "River Plate" && c.country.name === "Argentina").setColors('rgb(192,160,160)', 'black');
		Context.game.clubs.find(c => c.name === "Portsmouth" && c.country.name === "England").setColors('rgb(58,93,153)', 'white');
		Context.game.clubs.find(c => c.name === "Olimpia" && c.country.name === "Paraguay").setColors('rgb(172,172,171)', 'black');
		Context.game.clubs.find(c => c.name === "Sarpsborg 08" && c.country.name === "Norway").setColors('rgb(90,108,175)', 'white');
		Context.game.clubs.find(c => c.name === "Real Betis" && c.country.name === "Spain").setColors('rgb(112,160,131)', 'black');
		Context.game.clubs.find(c => c.name === "Rochdale" && c.country.name === "England").setColors('rgb(56,73,103)', 'white');
		Context.game.clubs.find(c => c.name === "Plymouth Argyle" && c.country.name === "England").setColors('rgb(77,92,86)', 'white');
		Context.game.clubs.find(c => c.name === "Saarbrücken" && c.country.name === "Germany").setColors('rgb(54,58,75)', 'white');
		Context.game.clubs.find(c => c.name === "Oxford United" && c.country.name === "England").setColors('rgb(189,165,103)', 'black');
		Context.game.clubs.find(c => c.name === "Raków Częstochowa" && c.country.name === "Poland").setColors('rgb(125,63,109)', 'white');
		Context.game.clubs.find(c => c.name === "Rennes" && c.country.name === "France").setColors('rgb(194,50,53)', 'white');
		Context.game.clubs.find(c => c.name === "Sandefjord" && c.country.name === "Norway").setColors('rgb(59,74,157)', 'white');
		Context.game.clubs.find(c => c.name === "Seattle Sounders" && c.country.name === "United States").setColors('rgb(79,127,87)', 'white');
		Context.game.clubs.find(c => c.name === "Perugia" && c.country.name === "Italy").setColors('rgb(174,52,55)', 'white');
		Context.game.clubs.find(c => c.name === "PAOK" && c.country.name === "Greece").setColors('rgb(139,138,137)', 'black');
		Context.game.clubs.find(c => c.name === "Preston North End" && c.country.name === "England").setColors('rgb(198,198,202)', 'black');
		Context.game.clubs.find(c => c.name === "Olympique de Marseille" && c.country.name === "France").setColors('rgb(205,204,206)', 'black');
		Context.game.clubs.find(c => c.name === "Sassuolo" && c.country.name === "Italy").setColors('rgb(43,105,72)', 'white');
		Context.game.clubs.find(c => c.name === "Rodez" && c.country.name === "France").setColors('rgb(138,46,41)', 'white');
		Context.game.clubs.find(c => c.name === "Saint-Étienne" && c.country.name === "France").setColors('rgb(43,125,92)', 'white');
		Context.game.clubs.find(c => c.name === "Real Madrid" && c.country.name === "Spain").setColors('rgb(205,204,203)', 'black');
		Context.game.clubs.find(c => c.name === "Randers" && c.country.name === "Denmark").setColors('rgb(132,176,207)', 'black');
		Context.game.clubs.find(c => c.name === "Pogoń Szczecin" && c.country.name === "Poland").setColors('rgb(70,44,53)', 'white');
		Context.game.clubs.find(c => c.name === "Sandhausen" && c.country.name === "Germany").setColors('rgb(198,197,196)', 'black');
		Context.game.clubs.find(c => c.name === "Paços de Ferreira" && c.country.name === "Portugal").setColors('rgb(216,193,31)', 'black');
		Context.game.clubs.find(c => c.name === "RFC Seraing" && c.country.name === "Belgium").setColors('rgb(144,62,62)', 'white');
		Context.game.clubs.find(c => c.name === "Seongnam" && c.country.name === "Korea Republic").setColors('rgb(59,59,59)', 'white');
		Context.game.clubs.find(c => c.name === "Peterborough United" && c.country.name === "England").setColors('rgb(48,97,151)', 'white');
		Context.game.clubs.find(c => c.name === "Paris" && c.country.name === "France").setColors('rgb(42,46,56)', 'white');
		Context.game.clubs.find(c => c.name === "SC Cambuur" && c.country.name === "Netherlands").setColors('rgb(198,190,45)', 'black');
		Context.game.clubs.find(c => c.name === "PSV" && c.country.name === "Netherlands").setColors('rgb(191,138,138)', 'black');
		Context.game.clubs.find(c => c.name === "Shandong Taishan" && c.country.name === "China PR").setColors('rgb(211,105,58)', 'black');
		Context.game.clubs.find(c => c.name === "Roma" && c.country.name === "Italy").setColors('rgb(152,68,74)', 'white');
		Context.game.clubs.find(c => c.name === "Salernitana" && c.country.name === "Italy").setColors('rgb(87,47,48)', 'white');
		Context.game.clubs.find(c => c.name === "Real Oviedo" && c.country.name === "Spain").setColors('rgb(58,66,98)', 'white');
		Context.game.clubs.find(c => c.name === "Rangers" && c.country.name === "Scotland").setColors('rgb(45,75,157)', 'white');
		Context.game.clubs.find(c => c.name === "Santa Clara" && c.country.name === "Portugal").setColors('rgb(180,37,37)', 'white');
		Context.game.clubs.find(c => c.name === "Pohang Steelers" && c.country.name === "Korea Republic").setColors('rgb(116,72,64)', 'white');
		Context.game.clubs.find(c => c.name === "Rheindorf Altach" && c.country.name === "Austria").setColors('rgb(180,179,176)', 'black');
		Context.game.clubs.find(c => c.name === "Silkeborg" && c.country.name === "Denmark").setColors('rgb(192,53,57)', 'white');
		Context.game.clubs.find(c => c.name === "Seoul" && c.country.name === "Korea Republic").setColors('rgb(109,62,61)', 'white');
		Context.game.clubs.find(c => c.name === "St. Gallen" && c.country.name === "Switzerland").setColors('rgb(50,104,66)', 'white');
		Context.game.clubs.find(c => c.name === "Sochaux" && c.country.name === "France").setColors('rgb(172,169,65)', 'black');
		Context.game.clubs.find(c => c.name === "SC Freiburg" && c.country.name === "Germany").setColors('rgb(168,76,79)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting CP" && c.country.name === "Portugal").setColors('rgb(109,152,133)', 'black');
		Context.game.clubs.find(c => c.name === "Salford City" && c.country.name === "England").setColors('rgb(202,49,52)', 'white');
		Context.game.clubs.find(c => c.name === "Stockport County" && c.country.name === "England").setColors('rgb(45,92,148)', 'white');
		Context.game.clubs.find(c => c.name === "Rosario Central" && c.country.name === "Argentina").setColors('rgb(148,149,90)', 'black');
		Context.game.clubs.find(c => c.name === "Shanghai Port" && c.country.name === "China PR").setColors('rgb(150,40,55)', 'white');
		Context.game.clubs.find(c => c.name === "Santa Fe" && c.country.name === "Colombia").setColors('rgb(186,89,90)', 'white');
		Context.game.clubs.find(c => c.name === "Suwon" && c.country.name === "Korea Republic").setColors('rgb(112,55,65)', 'white');
		Context.game.clubs.find(c => c.name === "Ternana" && c.country.name === "Italy").setColors('rgb(110,90,75)', 'white');
		Context.game.clubs.find(c => c.name === "Trabzonspor" && c.country.name === "Turkey").setColors('rgb(112,112,135)', 'white');
		Context.game.clubs.find(c => c.name === "St. Johnstone" && c.country.name === "Scotland").setColors('rgb(58,79,151)', 'white');
		Context.game.clubs.find(c => c.name === "SC Heerenveen" && c.country.name === "Netherlands").setColors('rgb(132,147,191)', 'black');
		Context.game.clubs.find(c => c.name === "Sepsi" && c.country.name === "Romania").setColors('rgb(193,96,104)', 'white');
		Context.game.clubs.find(c => c.name === "Sint-Truiden" && c.country.name === "Belgium").setColors('rgb(176,159,73)', 'black');
		Context.game.clubs.find(c => c.name === "Southampton" && c.country.name === "England").setColors('rgb(183,137,141)', 'black');
		Context.game.clubs.find(c => c.name === "Salzburg" && c.country.name === "Austria").setColors('rgb(208,185,179)', 'black');
		Context.game.clubs.find(c => c.name === "Rosenborg" && c.country.name === "Norway").setColors('rgb(196,195,194)', 'black');
		Context.game.clubs.find(c => c.name === "Stoke City" && c.country.name === "England").setColors('rgb(207,134,137)', 'black');
		Context.game.clubs.find(c => c.name === "Shanghai Shenhua" && c.country.name === "China PR").setColors('rgb(67,71,126)', 'white');
		Context.game.clubs.find(c => c.name === "Santos" && c.country.name === "Brazil").setColors('rgb(214,214,213)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Cristal" && c.country.name === "Peru").setColors('rgb(78,166,212)', 'black');
		Context.game.clubs.find(c => c.name === "The Strongest" && c.country.name === "Bolivia").setColors('rgb(107,89,54)', 'white');
		Context.game.clubs.find(c => c.name === "Suwon Bluewings" && c.country.name === "Korea Republic").setColors('rgb(59,73,162)', 'white');
		Context.game.clubs.find(c => c.name === "Tranmere Rovers" && c.country.name === "England").setColors('rgb(196,198,198)', 'black');
		Context.game.clubs.find(c => c.name === "Schalke 04" && c.country.name === "Germany").setColors('rgb(49,61,117)', 'white');
		Context.game.clubs.find(c => c.name === "St. Mirren" && c.country.name === "Scotland").setColors('rgb(131,127,126)', 'white');
		Context.game.clubs.find(c => c.name === "Sion" && c.country.name === "Switzerland").setColors('rgb(165,55,70)', 'white');
		Context.game.clubs.find(c => c.name === "Servette" && c.country.name === "Switzerland").setColors('rgb(96,53,62)', 'white');
		Context.game.clubs.find(c => c.name === "Ross County" && c.country.name === "Scotland").setColors('rgb(79,50,61)', 'white');
		Context.game.clubs.find(c => c.name === "Sampdoria" && c.country.name === "Italy").setColors('rgb(63,91,143)', 'white');
		Context.game.clubs.find(c => c.name === "SPAL" && c.country.name === "Italy").setColors('rgb(133,168,193)', 'black');
		Context.game.clubs.find(c => c.name === "São Paulo" && c.country.name === "Brazil").setColors('rgb(189,180,179)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Gijón" && c.country.name === "Spain").setColors('rgb(186,106,111)', 'white');
		Context.game.clubs.find(c => c.name === "Sheffield United" && c.country.name === "England").setColors('rgb(195,125,133)', 'black');
		Context.game.clubs.find(c => c.name === "Strasbourg" && c.country.name === "France").setColors('rgb(64,84,149)', 'white');
		Context.game.clubs.find(c => c.name === "Swansea City" && c.country.name === "England").setColors('rgb(202,201,200)', 'black');
		Context.game.clubs.find(c => c.name === "Tromsø" && c.country.name === "Norway").setColors('rgb(194,137,140)', 'black');
		Context.game.clubs.find(c => c.name === "SD Eibar" && c.country.name === "Spain").setColors('rgb(69,54,80)', 'white');
		Context.game.clubs.find(c => c.name === "Tianjin Jinmen Tiger" && c.country.name === "China PR").setColors('rgb(196,200,208)', 'black');
		Context.game.clubs.find(c => c.name === "Udinese" && c.country.name === "Italy").setColors('rgb(128,128,127)', 'white');
		Context.game.clubs.find(c => c.name === "St. Pauli" && c.country.name === "Germany").setColors('rgb(78,67,58)', 'white');
		Context.game.clubs.find(c => c.name === "Sevilla" && c.country.name === "Spain").setColors('rgb(221,218,217)', 'black');
		Context.game.clubs.find(c => c.name === "Vélez Sarsfield" && c.country.name === "Argentina").setColors('rgb(187,189,199)', 'black');
		Context.game.clubs.find(c => c.name === "Sparta Praha" && c.country.name === "Czech Republic").setColors('rgb(136,51,64)', 'white');
		Context.game.clubs.find(c => c.name === "Sirius" && c.country.name === "Sweden").setColors('rgb(64,87,132)', 'white');
		Context.game.clubs.find(c => c.name === "Voluntari" && c.country.name === "Romania").setColors('rgb(90,162,227)', 'black');
		Context.game.clubs.find(c => c.name === "Strømsgodset" && c.country.name === "Norway").setColors('rgb(54,61,82)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting KC" && c.country.name === "United States").setColors('rgb(129,143,171)', 'black');
		Context.game.clubs.find(c => c.name === "Sheffield Wednesday" && c.country.name === "England").setColors('rgb(114,127,172)', 'white');
		Context.game.clubs.find(c => c.name === "Wisła Płock" && c.country.name === "Poland").setColors('rgb(43,79,147)', 'white');
		Context.game.clubs.find(c => c.name === "Troyes" && c.country.name === "France").setColors('rgb(50,81,176)', 'white');
		Context.game.clubs.find(c => c.name === "Swindon Town" && c.country.name === "England").setColors('rgb(163,41,51)', 'white');
		Context.game.clubs.find(c => c.name === "Venezia" && c.country.name === "Italy").setColors('rgb(46,46,43)', 'white');
		Context.game.clubs.find(c => c.name === "Shakhtar Donetsk" && c.country.name === "Ukraine").setColors('rgb(150,86,34)', 'white');
		Context.game.clubs.find(c => c.name === "Stade de Reims" && c.country.name === "France").setColors('rgb(175,78,78)', 'white');
		Context.game.clubs.find(c => c.name === "Ulsan" && c.country.name === "Korea Republic").setColors('rgb(87,84,105)', 'white');
		Context.game.clubs.find(c => c.name === "Tigre" && c.country.name === "Argentina").setColors('rgb(72,50,120)', 'white');
		Context.game.clubs.find(c => c.name === "Sivasspor" && c.country.name === "Turkey").setColors('rgb(150,95,94)', 'white');
		Context.game.clubs.find(c => c.name === "Waldhof Mannheim" && c.country.name === "Germany").setColors('rgb(45,65,90)', 'white');
		Context.game.clubs.find(c => c.name === "Sparta Rotterdam" && c.country.name === "Netherlands").setColors('rgb(211,131,131)', 'black');
		Context.game.clubs.find(c => c.name === "Sturm Graz" && c.country.name === "Austria").setColors('rgb(128,130,136)', 'white');
		Context.game.clubs.find(c => c.name === "Sportivo Ameliano" && c.country.name === "Paraguay").setColors('rgb(153,157,187)', 'black');
		Context.game.clubs.find(c => c.name === "Wolfsberger AC" && c.country.name === "Austria").setColors('rgb(190,188,185)', 'black');
		Context.game.clubs.find(c => c.name === "Shelbourne" && c.country.name === "Republic of Ireland").setColors('rgb(210,46,62)', 'white');
		Context.game.clubs.find(c => c.name === "TSG Hoffenheim" && c.country.name === "Germany").setColors('rgb(47,82,150)', 'white');
		Context.game.clubs.find(c => c.name === "Verl" && c.country.name === "Germany").setColors('rgb(137,132,132)', 'black');
		Context.game.clubs.find(c => c.name === "Ümraniyespor" && c.country.name === "Turkey").setColors('rgb(160,59,56)', 'white');
		Context.game.clubs.find(c => c.name === "Sydney" && c.country.name === "Australia").setColors('rgb(81,139,187)', 'black');
		Context.game.clubs.find(c => c.name === "Shamrock Rovers" && c.country.name === "Republic of Ireland").setColors('rgb(131,149,134)', 'black');
		Context.game.clubs.find(c => c.name === "Stal Mielec" && c.country.name === "Poland").setColors('rgb(193,195,197)', 'black');
		Context.game.clubs.find(c => c.name === "Walsall" && c.country.name === "England").setColors('rgb(197,43,61)', 'white');
		Context.game.clubs.find(c => c.name === "Śląsk Wrocław" && c.country.name === "Poland").setColors('rgb(46,97,63)', 'white');
		Context.game.clubs.find(c => c.name === "Torino" && c.country.name === "Italy").setColors('rgb(118,66,74)', 'white');
		Context.game.clubs.find(c => c.name === "Spezia" && c.country.name === "Italy").setColors('rgb(192,193,191)', 'black');
		Context.game.clubs.find(c => c.name === "Südtirol" && c.country.name === "Italy").setColors('rgb(195,191,189)', 'black');
		Context.game.clubs.find(c => c.name === "SpVgg Greuther Fürth" && c.country.name === "Germany").setColors('rgb(98,168,131)', 'black');
		Context.game.clubs.find(c => c.name === "Wolverhampton Wanderers" && c.country.name === "England").setColors('rgb(218,165,32)', 'black');
		Context.game.clubs.find(c => c.name === "Shenzhen" && c.country.name === "China PR").setColors('rgb(204,109,65)', 'black');
		Context.game.clubs.find(c => c.name === "VfB Oldenburg" && c.country.name === "Germany").setColors('rgb(57,60,85)', 'white');
		Context.game.clubs.find(c => c.name === "Union Saint-Gilloise" && c.country.name === "Belgium").setColors('rgb(192,156,46)', 'black');
		Context.game.clubs.find(c => c.name === "U Craiova 1948" && c.country.name === "Romania").setColors('rgb(40,64,136)', 'white');
		Context.game.clubs.find(c => c.name === "Standard Liège" && c.country.name === "Belgium").setColors('rgb(180,60,66)', 'white');
		Context.game.clubs.find(c => c.name === "Slavia Praha" && c.country.name === "Czech Republic").setColors('rgb(211,120,122)', 'black');
		Context.game.clubs.find(c => c.name === "Warta Poznań" && c.country.name === "Poland").setColors('rgb(37,85,64)', 'white');
		Context.game.clubs.find(c => c.name === "Tacuary" && c.country.name === "Paraguay").setColors('rgb(139,136,130)', 'black');
		Context.game.clubs.find(c => c.name === "Toronto" && c.country.name === "United States").setColors('rgb(87,70,72)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting Braga" && c.country.name === "Portugal").setColors('rgb(200,69,76)', 'white');
		Context.game.clubs.find(c => c.name === "Wrexham" && c.country.name === "England").setColors('rgb(189,39,55)', 'white');
		Context.game.clubs.find(c => c.name === "Sunderland" && c.country.name === "England").setColors('rgb(181,117,127)', 'black');
		Context.game.clubs.find(c => c.name === "Shrewsbury Town" && c.country.name === "England").setColors('rgb(115,112,105)', 'white');
		Context.game.clubs.find(c => c.name === "SSC Farul" && c.country.name === "Romania").setColors('rgb(46,101,172)', 'white');
		Context.game.clubs.find(c => c.name === "VfB Stuttgart" && c.country.name === "Germany").setColors('rgb(218,197,199)', 'black');
		Context.game.clubs.find(c => c.name === "Unión Santa Fe" && c.country.name === "Argentina").setColors('rgb(206,144,144)', 'black');
		Context.game.clubs.find(c => c.name === "UCD" && c.country.name === "Republic of Ireland").setColors('rgb(72,135,177)', 'white');
		Context.game.clubs.find(c => c.name === "Stevenage" && c.country.name === "England").setColors('rgb(140,59,63)', 'white');
		Context.game.clubs.find(c => c.name === "Watford" && c.country.name === "England").setColors('rgb(207,176,33)', 'black');
		Context.game.clubs.find(c => c.name === "Sligo Rovers" && c.country.name === "Republic of Ireland").setColors('rgb(151,48,51)', 'white');
		Context.game.clubs.find(c => c.name === "Talleres Córdoba" && c.country.name === "Argentina").setColors('rgb(132,133,139)', 'black');
		Context.game.clubs.find(c => c.name === "Tottenham Hotspur" && c.country.name === "England").setColors('rgb(227,223,220)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Charleroi" && c.country.name === "Belgium").setColors('rgb(89,88,85)', 'white');
		Context.game.clubs.find(c => c.name === "WSG Tirol" && c.country.name === "Austria").setColors('rgb(143,180,171)', 'black');
		Context.game.clubs.find(c => c.name === "Sutton United" && c.country.name === "England").setColors('rgb(188,154,62)', 'black');
		Context.game.clubs.find(c => c.name === "St Patrick's" && c.country.name === "Republic of Ireland").setColors('rgb(199,71,80)', 'white');
		Context.game.clubs.find(c => c.name === "VfL Bochum 1848" && c.country.name === "Germany").setColors('rgb(38,65,94)', 'white');
		Context.game.clubs.find(c => c.name === "Universidad Católica" && c.country.name === "Chile").setColors('rgb(188,192,198)', 'black');
		Context.game.clubs.find(c => c.name === "UD Ibiza" && c.country.name === "Spain").setColors('rgb(101,141,187)', 'black');
		Context.game.clubs.find(c => c.name === "Wehen Wiesbaden" && c.country.name === "Germany").setColors('rgb(75,49,50)', 'white');
		Context.game.clubs.find(c => c.name === "Tenerife" && c.country.name === "Spain").setColors('rgb(187,191,200)', 'black');
		Context.game.clubs.find(c => c.name === "Toulouse" && c.country.name === "France").setColors('rgb(188,185,193)', 'black');
		Context.game.clubs.find(c => c.name === "Wuhan Three Towns" && c.country.name === "China PR").setColors('rgb(74,86,133)', 'white');
		Context.game.clubs.find(c => c.name === "Universitario" && c.country.name === "Peru").setColors('rgb(186,161,161)', 'black');
		Context.game.clubs.find(c => c.name === "VfL Wolfsburg" && c.country.name === "Germany").setColors('rgb(117,175,91)', 'black');
		Context.game.clubs.find(c => c.name === "Wellington Phoenix" && c.country.name === "Australia").setColors('rgb(145,133,39)', 'black');
		Context.game.clubs.find(c => c.name === "Wuhan Zall" && c.country.name === "China PR").setColors('rgb(222,140,67)', 'black');
		Context.game.clubs.find(c => c.name === "Universitatea Cluj" && c.country.name === "Romania").setColors('rgb(204,201,202)', 'black');
		Context.game.clubs.find(c => c.name === "Viborg" && c.country.name === "Denmark").setColors('rgb(43,79,56)', 'white');
		Context.game.clubs.find(c => c.name === "Werder Bremen" && c.country.name === "Germany").setColors('rgb(119,159,144)', 'black');
		Context.game.clubs.find(c => c.name === "Wycombe Wanderers" && c.country.name === "England").setColors('rgb(54,97,130)', 'white');
		Context.game.clubs.find(c => c.name === "Universitatea Craiova" && c.country.name === "Romania").setColors('rgb(116,135,165)', 'black');
		Context.game.clubs.find(c => c.name === "Viking" && c.country.name === "Norway").setColors('rgb(52,55,75)', 'white');
		Context.game.clubs.find(c => c.name === "West Bromwich Albion" && c.country.name === "England").setColors('rgb(126,130,144)', 'white');
		Context.game.clubs.find(c => c.name === "Young Boys" && c.country.name === "Switzerland").setColors('rgb(186,166,63)', 'black');
		Context.game.clubs.find(c => c.name === "UTA Arad" && c.country.name === "Romania").setColors('rgb(214,54,63)', 'white');
		Context.game.clubs.find(c => c.name === "Viktoria Köln" && c.country.name === "Germany").setColors('rgb(123,46,50)', 'white');
		Context.game.clubs.find(c => c.name === "West Ham United" && c.country.name === "England").setColors('rgb(126,74,89)', 'white');
		Context.game.clubs.find(c => c.name === "Zagłębie Lubin" && c.country.name === "Poland").setColors('rgb(175,71,41)', 'white');
		Context.game.clubs.find(c => c.name === "Valencia" && c.country.name === "Spain").setColors('rgb(204,203,202)', 'black');
		Context.game.clubs.find(c => c.name === "Viktoria Plzeň" && c.country.name === "Czech Republic").setColors('rgb(138,66,92)', 'white');
		Context.game.clubs.find(c => c.name === "Westerlo" && c.country.name === "Belgium").setColors('rgb(207,178,40)', 'black');
		Context.game.clubs.find(c => c.name === "Zhejiang" && c.country.name === "China PR").setColors('rgb(53,105,68)', 'white');
		Context.game.clubs.find(c => c.name === "Valenciennes" && c.country.name === "France").setColors('rgb(198,57,76)', 'white');
		Context.game.clubs.find(c => c.name === "Villarreal" && c.country.name === "Spain").setColors('rgb(206,208,34)', 'black');
		Context.game.clubs.find(c => c.name === "Western Sydney Wanderers" && c.country.name === "Australia").setColors('rgb(93,44,49)', 'white');
		Context.game.clubs.find(c => c.name === "Zulte-Waregem" && c.country.name === "Belgium").setColors('rgb(203,177,177)', 'black');
		Context.game.clubs.find(c => c.name === "Vålerenga" && c.country.name === "Norway").setColors('rgb(61,76,163)', 'white');
		Context.game.clubs.find(c => c.name === "Villarreal II" && c.country.name === "Spain").setColors('rgb(206,207,34)', 'black');
		Context.game.clubs.find(c => c.name === "Western United" && c.country.name === "Australia").setColors('rgb(46,73,60)', 'white');
		Context.game.clubs.find(c => c.name === "Zürich" && c.country.name === "Switzerland").setColors('rgb(196,198,201)', 'black');
		Context.game.clubs.find(c => c.name === "Vitesse" && c.country.name === "Netherlands").setColors('rgb(131,114,46)', 'white');
		Context.game.clubs.find(c => c.name === "Vancouver Whitecaps" && c.country.name === "United States").setColors('rgb(183,181,183)', 'black');
		Context.game.clubs.find(c => c.name === "Widzew Lodz" && c.country.name === "Poland").setColors('rgb(145,51,54)', 'white');
		Context.game.clubs.find(c => c.name === "Zwickau" && c.country.name === "Germany").setColors('rgb(217,88,92)', 'black');
		Context.game.clubs.find(c => c.name === "Varberg BoIS" && c.country.name === "Sweden").setColors('rgb(71,101,83)', 'white');
		Context.game.clubs.find(c => c.name === "Vitória SC" && c.country.name === "Portugal").setColors('rgb(207,205,202)', 'black');
		Context.game.clubs.find(c => c.name === "Wigan Athletic" && c.country.name === "England").setColors('rgb(114,128,157)', 'white');
		Context.game.clubs.find(c => c.name === "Värnamo" && c.country.name === "Sweden").setColors('rgb(222,219,220)', 'black');
		Context.game.clubs.find(c => c.name === "Vizela" && c.country.name === "Portugal").setColors('rgb(94,162,184)', 'black');
		Context.game.clubs.find(c => c.name === "Winterthur" && c.country.name === "Switzerland").setColors('rgb(157,43,44)', 'white');
	}

}