class ColorManager {
	static setClubsColors() {
		Context.game.clubs.find(c => c.name === "1860 München" && c.country.name === "Germany").setColors('rgb(182,193,203)', 'black');
		Context.game.clubs.find(c => c.name === "AaB" && c.country.name === "Denmark").setColors('rgb(221,142,145)', 'black');
		Context.game.clubs.find(c => c.name === "Aalesund" && c.country.name === "Norway").setColors('rgb(201,87,56)', 'white');
		Context.game.clubs.find(c => c.name === "Aberdeen" && c.country.name === "Scotland").setColors('rgb(148,50,60)', 'white');
		Context.game.clubs.find(c => c.name === "Abha" && c.country.name === "Saudi Arabia").setColors('rgb(174,192,206)', 'black');
		Context.game.clubs.find(c => c.name === "Academia Puerto Cabello" && c.country.name === "Venezuela").setColors('rgb(164,94,89)', 'white');
		Context.game.clubs.find(c => c.name === "Accrington Stanley" && c.country.name === "England").setColors('rgb(191,46,60)', 'white');
		Context.game.clubs.find(c => c.name === "Adana Demirspor" && c.country.name === "Turkey").setColors('rgb(51,90,138)', 'white');
		Context.game.clubs.find(c => c.name === "Adelaide United" && c.country.name === "Australia").setColors('rgb(152,42,55)', 'white');
		Context.game.clubs.find(c => c.name === "AEK Athens" && c.country.name === "Greece").setColors('rgb(141,117,50)', 'white');
		Context.game.clubs.find(c => c.name === "AFC Bournemouth" && c.country.name === "England").setColors('rgb(120,49,51)', 'white');
		Context.game.clubs.find(c => c.name === "AFC Wimbledon" && c.country.name === "England").setColors('rgb(58,98,152)', 'white');
		Context.game.clubs.find(c => c.name === "AGF" && c.country.name === "Denmark").setColors('rgb(206,190,190)', 'black');
		Context.game.clubs.find(c => c.name === "AIK" && c.country.name === "Sweden").setColors('rgb(56,55,48)', 'white');
		Context.game.clubs.find(c => c.name === "Ajaccio" && c.country.name === "France").setColors('rgb(160,111,115)', 'white');
		Context.game.clubs.find(c => c.name === "Ajax" && c.country.name === "Netherlands").setColors('rgb(152,73,86)', 'white');
		Context.game.clubs.find(c => c.name === "Al Adalah" && c.country.name === "Saudi Arabia").setColors('rgb(198,202,205)', 'black');
		Context.game.clubs.find(c => c.name === "Al Ain" && c.country.name === "United Arab Emirates").setColors('rgb(61,52,68)', 'white');
		Context.game.clubs.find(c => c.name === "Al Batin" && c.country.name === "Saudi Arabia").setColors('rgb(97,170,227)', 'black');
		Context.game.clubs.find(c => c.name === "Al Ettifaq" && c.country.name === "Saudi Arabia").setColors('rgb(67,135,102)', 'white');
		Context.game.clubs.find(c => c.name === "Al Fateh" && c.country.name === "Saudi Arabia").setColors('rgb(48,65,119)', 'white');
		Context.game.clubs.find(c => c.name === "Al Feiha" && c.country.name === "Saudi Arabia").setColors('rgb(217,80,36)', 'white');
		Context.game.clubs.find(c => c.name === "Al Hilal" && c.country.name === "Saudi Arabia").setColors('rgb(57,64,149)', 'white');
		Context.game.clubs.find(c => c.name === "Al Ittihad" && c.country.name === "Saudi Arabia").setColors('rgb(133,119,55)', 'white');
		Context.game.clubs.find(c => c.name === "Al Khaleej" && c.country.name === "Saudi Arabia").setColors('rgb(219,194,37)', 'black');
		Context.game.clubs.find(c => c.name === "Al Nassr" && c.country.name === "Saudi Arabia").setColors('rgb(230,218,89)', 'black');
		Context.game.clubs.find(c => c.name === "Al Raed" && c.country.name === "Saudi Arabia").setColors('rgb(120,60,64)', 'white');
		Context.game.clubs.find(c => c.name === "Al Shabab" && c.country.name === "Saudi Arabia").setColors('rgb(197,192,190)', 'black');
		Context.game.clubs.find(c => c.name === "Al Taawon" && c.country.name === "Saudi Arabia").setColors('rgb(209,188,41)', 'black');
		Context.game.clubs.find(c => c.name === "Al Tai" && c.country.name === "Saudi Arabia").setColors('rgb(161,167,173)', 'black');
		Context.game.clubs.find(c => c.name === "Al Wahda" && c.country.name === "Saudi Arabia").setColors('rgb(190,51,54)', 'white');
		Context.game.clubs.find(c => c.name === "Alanyaspor" && c.country.name === "Turkey").setColors('rgb(89,80,52)', 'white');
		Context.game.clubs.find(c => c.name === "Albacete" && c.country.name === "Spain").setColors('rgb(202,198,197)', 'black');
		Context.game.clubs.find(c => c.name === "Aldosivi" && c.country.name === "Argentina").setColors('rgb(147,168,62)', 'black');
		Context.game.clubs.find(c => c.name === "Alianza Lima" && c.country.name === "Peru").setColors('rgb(149,146,159)', 'black');
		Context.game.clubs.find(c => c.name === "Almería" && c.country.name === "Spain").setColors('rgb(204,110,110)', 'black');
		Context.game.clubs.find(c => c.name === "América Mineiro" && c.country.name === "Brazil").setColors('rgb(50,102,67)', 'white');
		Context.game.clubs.find(c => c.name === "Amiens SC" && c.country.name === "France").setColors('rgb(189,185,187)', 'black');
		Context.game.clubs.find(c => c.name === "Anderlecht" && c.country.name === "Belgium").setColors('rgb(71,57,117)', 'white');
		Context.game.clubs.find(c => c.name === "Angers SCO" && c.country.name === "France").setColors('rgb(94,92,91)', 'white');
		Context.game.clubs.find(c => c.name === "Ankaragücü" && c.country.name === "Turkey").setColors('rgb(135,128,53)', 'white');
		Context.game.clubs.find(c => c.name === "Annecy" && c.country.name === "France").setColors('rgb(105,38,42)', 'white');
		Context.game.clubs.find(c => c.name === "Antalyaspor" && c.country.name === "Turkey").setColors('rgb(207,130,131)', 'black');
		Context.game.clubs.find(c => c.name === "Antwerp" && c.country.name === "Belgium").setColors('rgb(171,51,55)', 'white');
		Context.game.clubs.find(c => c.name === "APOEL" && c.country.name === "Cyprus").setColors('rgb(144,142,102)', 'black');
		Context.game.clubs.find(c => c.name === "Argentinos Juniors" && c.country.name === "Argentina").setColors('rgb(204,82,78)', 'white');
		Context.game.clubs.find(c => c.name === "Argeş" && c.country.name === "Romania").setColors('rgb(86,58,115)', 'white');
		Context.game.clubs.find(c => c.name === "Arouca" && c.country.name === "Portugal").setColors('rgb(206,193,45)', 'black');
		Context.game.clubs.find(c => c.name === "Arsenal" && c.country.name === "England").setColors('rgb(161,39,50)', 'white');
		Context.game.clubs.find(c => c.name === "Arsenal de Sarandi" && c.country.name === "Argentina").setColors('rgb(154,144,163)', 'black');
		Context.game.clubs.find(c => c.name === "AS Eupen" && c.country.name === "Belgium").setColors('rgb(221,220,219)', 'black');
		Context.game.clubs.find(c => c.name === "Ascoli" && c.country.name === "Italy").setColors('rgb(125,124,123)', 'white');
		Context.game.clubs.find(c => c.name === "Aston Villa" && c.country.name === "England").setColors('rgb(100,49,73)', 'white');
		Context.game.clubs.find(c => c.name === "Atalanta" && c.country.name === "Italy").setColors('rgb(70,95,112)', 'white');
		Context.game.clubs.find(c => c.name === "Athletic Club" && c.country.name === "Spain").setColors('rgb(193,127,130)', 'black');
		Context.game.clubs.find(c => c.name === "Athletico Paranaense" && c.country.name === "Brazil").setColors('rgb(134,54,53)', 'white');
		Context.game.clubs.find(c => c.name === "ATK Mohun Bagan" && c.country.name === "India").setColors('rgb(112,113,97)', 'white');
		Context.game.clubs.find(c => c.name === "Atlanta United" && c.country.name === "United States").setColors('rgb(77,48,47)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Madrid" && c.country.name === "Spain").setColors('rgb(193,132,137)', 'black');
		Context.game.clubs.find(c => c.name === "Atlético Mineiro" && c.country.name === "Brazil").setColors('rgb(127,125,122)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Nacional" && c.country.name === "Colombia").setColors('rgb(135,159,145)', 'black');
		Context.game.clubs.find(c => c.name === "Atlético Tucumán" && c.country.name === "Argentina").setColors('rgb(173,195,211)', 'black');
		Context.game.clubs.find(c => c.name === "Aucas" && c.country.name === "Ecuador").setColors('rgb(205,166,45)', 'black');
		Context.game.clubs.find(c => c.name === "Audax Italiano" && c.country.name === "Chile").setColors('rgb(59,119,89)', 'white');
		Context.game.clubs.find(c => c.name === "Austin" && c.country.name === "United States").setColors('rgb(40,97,62)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Klagenfurt" && c.country.name === "Austria").setColors('rgb(104,47,140)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Lustenau" && c.country.name === "Austria").setColors('rgb(52,161,92)', 'black');
		Context.game.clubs.find(c => c.name === "Austria Wien" && c.country.name === "Austria").setColors('rgb(72,51,115)', 'white');
		Context.game.clubs.find(c => c.name === "Auxerre" && c.country.name === "France").setColors('rgb(196,199,203)', 'black');
		Context.game.clubs.find(c => c.name === "AZ Alkmaar" && c.country.name === "Netherlands").setColors('rgb(178,39,40)', 'white');
		Context.game.clubs.find(c => c.name === "Banfield" && c.country.name === "Argentina").setColors('rgb(131,150,141)', 'black');
		Context.game.clubs.find(c => c.name === "Barcelona Guayaquil" && c.country.name === "Ecuador").setColors('rgb(212,172,41)', 'black');
		Context.game.clubs.find(c => c.name === "Bari 1908" && c.country.name === "Italy").setColors('rgb(208,201,201)', 'black');
		Context.game.clubs.find(c => c.name === "Barnsley" && c.country.name === "England").setColors('rgb(191,38,54)', 'white');
		Context.game.clubs.find(c => c.name === "Barracas Central" && c.country.name === "Argentina").setColors('rgb(207,150,148)', 'black');
		Context.game.clubs.find(c => c.name === "Barrow" && c.country.name === "England").setColors('rgb(102,148,176)', 'black');
		Context.game.clubs.find(c => c.name === "Basel" && c.country.name === "Switzerland").setColors('rgb(133,66,103)', 'white');
		Context.game.clubs.find(c => c.name === "Bastia" && c.country.name === "France").setColors('rgb(65,74,123)', 'white');
		Context.game.clubs.find(c => c.name === "Bayer 04 Leverkusen" && c.country.name === "Germany").setColors('rgb(168,54,66)', 'white');
		Context.game.clubs.find(c => c.name === "Bayreuth" && c.country.name === "Germany").setColors('rgb(224,180,47)', 'black');
		Context.game.clubs.find(c => c.name === "Beijing Guoan" && c.country.name === "China PR").setColors('rgb(42,67,46)', 'white');
		Context.game.clubs.find(c => c.name === "Benevento" && c.country.name === "Italy").setColors('rgb(180,116,45)', 'black');
		Context.game.clubs.find(c => c.name === "Benfica" && c.country.name === "Portugal").setColors('rgb(214,44,55)', 'white');
		Context.game.clubs.find(c => c.name === "Bengaluru" && c.country.name === "India").setColors('rgb(74,70,125)', 'white');
		Context.game.clubs.find(c => c.name === "Beşiktaş" && c.country.name === "Turkey").setColors('rgb(210,208,207)', 'black');
		Context.game.clubs.find(c => c.name === "Birmingham City" && c.country.name === "England").setColors('rgb(52,83,139)', 'white');
		Context.game.clubs.find(c => c.name === "Blackburn Rovers" && c.country.name === "England").setColors('rgb(140,156,189)', 'black');
		Context.game.clubs.find(c => c.name === "Blackpool" && c.country.name === "England").setColors('rgb(214,92,50)', 'white');
		Context.game.clubs.find(c => c.name === "Blooming" && c.country.name === "Bolivia").setColors('rgb(58,101,167)', 'white');
		Context.game.clubs.find(c => c.name === "Boavista" && c.country.name === "Portugal").setColors('rgb(135,128,126)', 'white');
		Context.game.clubs.find(c => c.name === "Boca Juniors" && c.country.name === "Argentina").setColors('rgb(99,106,113)', 'white');
		Context.game.clubs.find(c => c.name === "Bodø / Glimt" && c.country.name === "Norway").setColors('rgb(196,151,74)', 'black');
		Context.game.clubs.find(c => c.name === "Bohemians" && c.country.name === "Republic of Ireland").setColors('rgb(79,56,55)', 'white');
		Context.game.clubs.find(c => c.name === "Bolívar" && c.country.name === "Bolivia").setColors('rgb(83,132,187)', 'white');
		Context.game.clubs.find(c => c.name === "Bologna" && c.country.name === "Italy").setColors('rgb(114,58,66)', 'white');
		Context.game.clubs.find(c => c.name === "Bolton Wanderers" && c.country.name === "England").setColors('rgb(192,194,190)', 'black');
		Context.game.clubs.find(c => c.name === "Bordeaux" && c.country.name === "France").setColors('rgb(75,76,82)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Dortmund" && c.country.name === "Germany").setColors('rgb(147,128,44)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Dortmund II" && c.country.name === "Germany").setColors('rgb(148,129,45)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Mönchengladbach" && c.country.name === "Germany").setColors('rgb(163,174,168)', 'black');
		Context.game.clubs.find(c => c.name === "Botafogo" && c.country.name === "Brazil").setColors('rgb(119,119,118)', 'white');
		Context.game.clubs.find(c => c.name === "Botoşani" && c.country.name === "Romania").setColors('rgb(203,199,202)', 'black');
		Context.game.clubs.find(c => c.name === "Bradford City" && c.country.name === "England").setColors('rgb(179,104,58)', 'white');
		Context.game.clubs.find(c => c.name === "Bragantino" && c.country.name === "Brazil").setColors('rgb(214,203,202)', 'black');
		Context.game.clubs.find(c => c.name === "Brentford" && c.country.name === "England").setColors('rgb(193,125,127)', 'black');
		Context.game.clubs.find(c => c.name === "Brescia" && c.country.name === "Italy").setColors('rgb(78,115,162)', 'white');
		Context.game.clubs.find(c => c.name === "Brest" && c.country.name === "France").setColors('rgb(202,54,58)', 'white');
		Context.game.clubs.find(c => c.name === "Brighton & Hove Albion" && c.country.name === "England").setColors('rgb(139,162,185)', 'black');
		Context.game.clubs.find(c => c.name === "Brisbane Roar" && c.country.name === "Australia").setColors('rgb(198,86,43)', 'white');
		Context.game.clubs.find(c => c.name === "Bristol City" && c.country.name === "England").setColors('rgb(178,43,49)', 'white');
		Context.game.clubs.find(c => c.name === "Bristol Rovers" && c.country.name === "England").setColors('rgb(111,125,152)', 'white');
		Context.game.clubs.find(c => c.name === "Brøndby" && c.country.name === "Denmark").setColors('rgb(222,185,37)', 'black');
		Context.game.clubs.find(c => c.name === "Burgos" && c.country.name === "Spain").setColors('rgb(207,207,207)', 'black');
		Context.game.clubs.find(c => c.name === "Burnley" && c.country.name === "England").setColors('rgb(117,71,86)', 'white');
		Context.game.clubs.find(c => c.name === "Burton Albion" && c.country.name === "England").setColors('rgb(215,198,36)', 'black');
		Context.game.clubs.find(c => c.name === "Cádiz" && c.country.name === "Spain").setColors('rgb(220,207,55)', 'black');
		Context.game.clubs.find(c => c.name === "Caen" && c.country.name === "France").setColors('rgb(98,77,103)', 'white');
		Context.game.clubs.find(c => c.name === "Cagliari" && c.country.name === "Italy").setColors('rgb(124,51,75)', 'white');
		Context.game.clubs.find(c => c.name === "Cambridge United" && c.country.name === "England").setColors('rgb(203,131,57)', 'black');
		Context.game.clubs.find(c => c.name === "Cangzhou Mighty Lions" && c.country.name === "China PR").setColors('rgb(47,78,153)', 'white');
		Context.game.clubs.find(c => c.name === "Caracas" && c.country.name === "Venezuela").setColors('rgb(199,69,51)', 'white');
		Context.game.clubs.find(c => c.name === "Cardiff City" && c.country.name === "England").setColors('rgb(48,80,163)', 'white');
		Context.game.clubs.find(c => c.name === "Carlisle United" && c.country.name === "England").setColors('rgb(46,54,74)', 'white');
		Context.game.clubs.find(c => c.name === "Casa Pia" && c.country.name === "Portugal").setColors('rgb(48,47,44)', 'white');
		Context.game.clubs.find(c => c.name === "Celta de Vigo" && c.country.name === "Spain").setColors('rgb(113,159,173)', 'black');
		Context.game.clubs.find(c => c.name === "Celtic" && c.country.name === "Scotland").setColors('rgb(128,154,134)', 'black');
		Context.game.clubs.find(c => c.name === "Central Coast Mariners" && c.country.name === "Australia").setColors('rgb(192,154,66)', 'black');
		Context.game.clubs.find(c => c.name === "Central Cordoba SdE" && c.country.name === "Argentina").setColors('rgb(124,124,130)', 'white');
		Context.game.clubs.find(c => c.name === "Cercle Brugge" && c.country.name === "Belgium").setColors('rgb(61,88,67)', 'white');
		Context.game.clubs.find(c => c.name === "Cerro Porteño" && c.country.name === "Paraguay").setColors('rgb(130,61,108)', 'white');
		Context.game.clubs.find(c => c.name === "César Vallejo" && c.country.name === "Peru").setColors('rgb(235,107,67)', 'black');
		Context.game.clubs.find(c => c.name === "CF Montréal" && c.country.name === "United States").setColors('rgb(55,55,55)', 'white');
		Context.game.clubs.find(c => c.name === "CFR Cluj" && c.country.name === "Romania").setColors('rgb(120,48,48)', 'white');
		Context.game.clubs.find(c => c.name === "Changchun Yatai" && c.country.name === "China PR").setColors('rgb(178,66,75)', 'white');
		Context.game.clubs.find(c => c.name === "Charlotte" && c.country.name === "United States").setColors('rgb(61,140,191)', 'white');
		Context.game.clubs.find(c => c.name === "Charlton Athletic" && c.country.name === "England").setColors('rgb(184,61,62)', 'white');
		Context.game.clubs.find(c => c.name === "Chaves" && c.country.name === "Portugal").setColors('rgb(87,78,135)', 'white');
		Context.game.clubs.find(c => c.name === "Chelsea" && c.country.name === "England").setColors('rgb(60,71,115)', 'white');
		Context.game.clubs.find(c => c.name === "Cheltenham Town" && c.country.name === "England").setColors('rgb(185,50,66)', 'white');
		Context.game.clubs.find(c => c.name === "Chengdu Rongcheng" && c.country.name === "China PR").setColors('rgb(148,49,58)', 'white');
		Context.game.clubs.find(c => c.name === "Chennaiyin" && c.country.name === "India").setColors('rgb(56,63,139)', 'white');
		Context.game.clubs.find(c => c.name === "Chicago Fire" && c.country.name === "United States").setColors('rgb(45,55,81)', 'white');
		Context.game.clubs.find(c => c.name === "Chindia Târgovişte" && c.country.name === "Romania").setColors('rgb(181,81,83)', 'white');
		Context.game.clubs.find(c => c.name === "Cienciano" && c.country.name === "Peru").setColors('rgb(182,53,50)', 'white');
		Context.game.clubs.find(c => c.name === "Cincinnati" && c.country.name === "United States").setColors('rgb(54,77,129)', 'white');
		Context.game.clubs.find(c => c.name === "Cittadella" && c.country.name === "Italy").setColors('rgb(165,45,71)', 'white');
		Context.game.clubs.find(c => c.name === "Clermont" && c.country.name === "France").setColors('rgb(152,43,65)', 'white');
		Context.game.clubs.find(c => c.name === "Club Brugge" && c.country.name === "Belgium").setColors('rgb(47,83,120)', 'white');
		Context.game.clubs.find(c => c.name === "Cobresal" && c.country.name === "Chile").setColors('rgb(197,155,147)', 'black');
		Context.game.clubs.find(c => c.name === "Colchester United" && c.country.name === "England").setColors('rgb(154,158,193)', 'black');
		Context.game.clubs.find(c => c.name === "Colo-Colo" && c.country.name === "Chile").setColors('rgb(200,198,198)', 'black');
		Context.game.clubs.find(c => c.name === "Colón" && c.country.name === "Argentina").setColors('rgb(130,71,67)', 'white');
		Context.game.clubs.find(c => c.name === "Colorado Rapids" && c.country.name === "United States").setColors('rgb(82,50,57)', 'white');
		Context.game.clubs.find(c => c.name === "Columbus Crew" && c.country.name === "United States").setColors('rgb(216,193,36)', 'black');
		Context.game.clubs.find(c => c.name === "Como" && c.country.name === "Italy").setColors('rgb(78,139,180)', 'white');
		Context.game.clubs.find(c => c.name === "Corinthians" && c.country.name === "Brazil").setColors('rgb(210,209,207)', 'black');
		Context.game.clubs.find(c => c.name === "Cosenza" && c.country.name === "Italy").setColors('rgb(119,53,61)', 'white');
		Context.game.clubs.find(c => c.name === "Coventry City" && c.country.name === "England").setColors('rgb(151,176,192)', 'black');
		Context.game.clubs.find(c => c.name === "Cracovia Kraków" && c.country.name === "Poland").setColors('rgb(199,114,117)', 'black');
		Context.game.clubs.find(c => c.name === "Crawley Town" && c.country.name === "England").setColors('rgb(173,50,52)', 'white');
		Context.game.clubs.find(c => c.name === "Cremonese" && c.country.name === "Italy").setColors('rgb(184,74,84)', 'white');
		Context.game.clubs.find(c => c.name === "Crewe Alexandra" && c.country.name === "England").setColors('rgb(202,43,43)', 'white');
		Context.game.clubs.find(c => c.name === "Crystal Palace" && c.country.name === "England").setColors('rgb(123,63,82)', 'white');
		Context.game.clubs.find(c => c.name === "Daegu" && c.country.name === "Korea Republic").setColors('rgb(117,174,201)', 'black');
		Context.game.clubs.find(c => c.name === "Dalian Professional" && c.country.name === "China PR").setColors('rgb(51,153,208)', 'black');
		Context.game.clubs.find(c => c.name === "Dallas" && c.country.name === "United States").setColors('rgb(152,59,84)', 'white');
		Context.game.clubs.find(c => c.name === "Damac" && c.country.name === "Saudi Arabia").setColors('rgb(187,45,43)', 'white');
		Context.game.clubs.find(c => c.name === "Danubio" && c.country.name === "Uruguay").setColors('rgb(152,152,151)', 'black');
		Context.game.clubs.find(c => c.name === "Darmstadt 98" && c.country.name === "Germany").setColors('rgb(48,76,125)', 'white');
		Context.game.clubs.find(c => c.name === "DC United" && c.country.name === "United States").setColors('rgb(63,61,61)', 'white');
		Context.game.clubs.find(c => c.name === "Defensa y Justicia" && c.country.name === "Argentina").setColors('rgb(224,190,63)', 'black');
		Context.game.clubs.find(c => c.name === "Defensor Sporting" && c.country.name === "Uruguay").setColors('rgb(90,63,138)', 'white');
		Context.game.clubs.find(c => c.name === "Degerfors" && c.country.name === "Sweden").setColors('rgb(211,68,73)', 'white');
		Context.game.clubs.find(c => c.name === "Delfin" && c.country.name === "Ecuador").setColors('rgb(83,91,150)', 'white');
		Context.game.clubs.find(c => c.name === "Deportes Tolima" && c.country.name === "Colombia").setColors('rgb(190,120,93)', 'black');
		Context.game.clubs.find(c => c.name === "Deportivo Alavés" && c.country.name === "Spain").setColors('rgb(122,140,166)', 'black');
		Context.game.clubs.find(c => c.name === "Deportivo Binacional" && c.country.name === "Peru").setColors('rgb(67,135,220)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Cuenca" && c.country.name === "Ecuador").setColors('rgb(177,75,70)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Pereira" && c.country.name === "Colombia").setColors('rgb(194,120,44)', 'black');
		Context.game.clubs.find(c => c.name === "Deportivo Táchira" && c.country.name === "Venezuela").setColors('rgb(156,131,61)', 'black');
		Context.game.clubs.find(c => c.name === "Derby County" && c.country.name === "England").setColors('rgb(182,182,181)', 'black');
		Context.game.clubs.find(c => c.name === "Derry City" && c.country.name === "Republic of Ireland").setColors('rgb(208,78,81)', 'white');
		Context.game.clubs.find(c => c.name === "Dijon" && c.country.name === "France").setColors('rgb(181,64,69)', 'white');
		Context.game.clubs.find(c => c.name === "Dinamo Zagreb" && c.country.name === "Croatia").setColors('rgb(55,64,115)', 'white');
		Context.game.clubs.find(c => c.name === "Djurgården" && c.country.name === "Sweden").setColors('rgb(72,108,137)', 'white');
		Context.game.clubs.find(c => c.name === "Doncaster Rovers" && c.country.name === "England").setColors('rgb(197,131,133)', 'black');
		Context.game.clubs.find(c => c.name === "Drogheda United" && c.country.name === "Republic of Ireland").setColors('rgb(158,62,79)', 'white');
		Context.game.clubs.find(c => c.name === "DSC Arminia Bielefeld" && c.country.name === "Germany").setColors('rgb(52,77,125)', 'white');
		Context.game.clubs.find(c => c.name === "Dundalk" && c.country.name === "Republic of Ireland").setColors('rgb(189,187,186)', 'black');
		Context.game.clubs.find(c => c.name === "Dundee United" && c.country.name === "Scotland").setColors('rgb(214,95,40)', 'black');
		Context.game.clubs.find(c => c.name === "Dynamo Dresden" && c.country.name === "Germany").setColors('rgb(187,130,50)', 'black');
		Context.game.clubs.find(c => c.name === "Dynamo Kyiv" && c.country.name === "Ukraine").setColors('rgb(171,180,197)', 'black');
		Context.game.clubs.find(c => c.name === "East Bengal" && c.country.name === "India").setColors('rgb(206,96,50)', 'white');
		Context.game.clubs.find(c => c.name === "Eintracht Braunschweig" && c.country.name === "Germany").setColors('rgb(157,151,87)', 'black');
		Context.game.clubs.find(c => c.name === "Eintracht Frankfurt" && c.country.name === "Germany").setColors('rgb(201,200,199)', 'black');
		Context.game.clubs.find(c => c.name === "Elche" && c.country.name === "Spain").setColors('rgb(197,203,198)', 'black');
		Context.game.clubs.find(c => c.name === "Elfsborg" && c.country.name === "Sweden").setColors('rgb(203,150,31)', 'black');
		Context.game.clubs.find(c => c.name === "Elversberg" && c.country.name === "Germany").setColors('rgb(185,183,180)', 'black');
		Context.game.clubs.find(c => c.name === "Emelec" && c.country.name === "Ecuador").setColors('rgb(83,97,144)', 'white');
		Context.game.clubs.find(c => c.name === "Empoli" && c.country.name === "Italy").setColors('rgb(55,108,159)', 'white');
		Context.game.clubs.find(c => c.name === "Erzgebirge Aue" && c.country.name === "Germany").setColors('rgb(73,55,113)', 'white');
		Context.game.clubs.find(c => c.name === "Espanyol" && c.country.name === "Spain").setColors('rgb(113,153,198)', 'black');
		Context.game.clubs.find(c => c.name === "Estoril" && c.country.name === "Portugal").setColors('rgb(209,167,44)', 'black');
		Context.game.clubs.find(c => c.name === "Estudiantes" && c.country.name === "Argentina").setColors('rgb(206,126,127)', 'black');
		Context.game.clubs.find(c => c.name === "Estudiantes Mérida" && c.country.name === "Venezuela").setColors('rgb(197,154,155)', 'black');
		Context.game.clubs.find(c => c.name === "Everton" && c.country.name === "England").setColors('rgb(49,80,121)', 'white');
		Context.game.clubs.find(c => c.name === "Excelsior" && c.country.name === "Netherlands").setColors('rgb(60,54,53)', 'white');
		Context.game.clubs.find(c => c.name === "Exeter City" && c.country.name === "England").setColors('rgb(209,124,123)', 'black');
		Context.game.clubs.find(c => c.name === "Famalicão" && c.country.name === "Portugal").setColors('rgb(202,202,202)', 'black');
		Context.game.clubs.find(c => c.name === "Fatih Karagümrük" && c.country.name === "Turkey").setColors('rgb(105,44,51)', 'white');
		Context.game.clubs.find(c => c.name === "FC Andorra" && c.country.name === "Spain").setColors('rgb(171,117,90)', 'white');
		Context.game.clubs.find(c => c.name === "FC Augsburg" && c.country.name === "Germany").setColors('rgb(162,95,92)', 'white');
		Context.game.clubs.find(c => c.name === "FC Barcelona" && c.country.name === "Spain").setColors('rgb(88,59,89)', 'white');
		Context.game.clubs.find(c => c.name === "FC Bayern München" && c.country.name === "Germany").setColors('rgb(197,54,56)', 'white');
		Context.game.clubs.find(c => c.name === "FC Cartagena" && c.country.name === "Spain").setColors('rgb(128,127,126)', 'white');
		Context.game.clubs.find(c => c.name === "FC Emmen" && c.country.name === "Netherlands").setColors('rgb(208,155,159)', 'black');
		Context.game.clubs.find(c => c.name === "FC Groningen" && c.country.name === "Netherlands").setColors('rgb(136,171,144)', 'black');
		Context.game.clubs.find(c => c.name === "FC Köln" && c.country.name === "Germany").setColors('rgb(197,94,96)', 'white');
		Context.game.clubs.find(c => c.name === "FC Twente" && c.country.name === "Netherlands").setColors('rgb(223,85,88)', 'black');
		Context.game.clubs.find(c => c.name === "FC Union Berlin" && c.country.name === "Germany").setColors('rgb(203,124,124)', 'black');
		Context.game.clubs.find(c => c.name === "FC Utrecht" && c.country.name === "Netherlands").setColors('rgb(187,120,123)', 'black');
		Context.game.clubs.find(c => c.name === "FC Volendam" && c.country.name === "Netherlands").setColors('rgb(174,117,79)', 'black');
		Context.game.clubs.find(c => c.name === "FCSB" && c.country.name === "Romania").setColors('rgb(239,59,72)', 'white');
		Context.game.clubs.find(c => c.name === "Fenerbahçe" && c.country.name === "Turkey").setColors('rgb(145,143,84)', 'black');
		Context.game.clubs.find(c => c.name === "Ferencváros" && c.country.name === "Hungary").setColors('rgb(141,155,144)', 'black');
		Context.game.clubs.find(c => c.name === "Feyenoord" && c.country.name === "Netherlands").setColors('rgb(177,120,122)', 'black');
		Context.game.clubs.find(c => c.name === "Finn Harps" && c.country.name === "Republic of Ireland").setColors('rgb(53,113,191)', 'white');
		Context.game.clubs.find(c => c.name === "Fiorentina" && c.country.name === "Italy").setColors('rgb(75,54,95)', 'white');
		Context.game.clubs.find(c => c.name === "Flamengo" && c.country.name === "Brazil").setColors('rgb(114,58,61)', 'white');
		Context.game.clubs.find(c => c.name === "Fleetwood Town" && c.country.name === "England").setColors('rgb(177,60,68)', 'white');
		Context.game.clubs.find(c => c.name === "Fluminense" && c.country.name === "Brazil").setColors('rgb(113,91,96)', 'white');
		Context.game.clubs.find(c => c.name === "Forest Green Rovers" && c.country.name === "England").setColors('rgb(119,154,64)', 'black');
		Context.game.clubs.find(c => c.name === "Fortaleza" && c.country.name === "Brazil").setColors('rgb(131,84,113)', 'white');
		Context.game.clubs.find(c => c.name === "Fortuna Düsseldorf" && c.country.name === "Germany").setColors('rgb(149,47,55)', 'white');
		Context.game.clubs.find(c => c.name === "Fortuna Sittard" && c.country.name === "Netherlands").setColors('rgb(223,212,34)', 'black');
		Context.game.clubs.find(c => c.name === "Freiburg II" && c.country.name === "Germany").setColors('rgb(169,79,82)', 'white');
		Context.game.clubs.find(c => c.name === "Frosinone" && c.country.name === "Italy").setColors('rgb(201,175,42)', 'black');
		Context.game.clubs.find(c => c.name === "FSV Mainz 05" && c.country.name === "Germany").setColors('rgb(175,45,57)', 'white');
		Context.game.clubs.find(c => c.name === "Fulham" && c.country.name === "England").setColors('rgb(214,212,211)', 'black');
		Context.game.clubs.find(c => c.name === "Galatasaray" && c.country.name === "Turkey").setColors('rgb(157,89,57)', 'white');
		Context.game.clubs.find(c => c.name === "Gangwon" && c.country.name === "Korea Republic").setColors('rgb(232,97,67)', 'black');
		Context.game.clubs.find(c => c.name === "Gaziantep F.K." && c.country.name === "Turkey").setColors('rgb(123,49,59)', 'white');
		Context.game.clubs.find(c => c.name === "General Caballero JLM" && c.country.name === "Paraguay").setColors('rgb(212,64,71)', 'white');
		Context.game.clubs.find(c => c.name === "Genk" && c.country.name === "Belgium").setColors('rgb(42,87,175)', 'white');
		Context.game.clubs.find(c => c.name === "Genoa" && c.country.name === "Italy").setColors('rgb(123,61,64)', 'white');
		Context.game.clubs.find(c => c.name === "Gent" && c.country.name === "Belgium").setColors('rgb(141,150,176)', 'black');
		Context.game.clubs.find(c => c.name === "Getafe" && c.country.name === "Spain").setColors('rgb(46,72,156)', 'white');
		Context.game.clubs.find(c => c.name === "GIF Sundsvall" && c.country.name === "Sweden").setColors('rgb(52,82,155)', 'white');
		Context.game.clubs.find(c => c.name === "Gil Vicente" && c.country.name === "Portugal").setColors('rgb(193,52,54)', 'white');
		Context.game.clubs.find(c => c.name === "Gillingham" && c.country.name === "England").setColors('rgb(56,110,172)', 'white');
		Context.game.clubs.find(c => c.name === "Gimcheon Sangmu" && c.country.name === "Korea Republic").setColors('rgb(167,65,74)', 'white');
		Context.game.clubs.find(c => c.name === "Gimnasia La Plata" && c.country.name === "Argentina").setColors('rgb(193,193,199)', 'black');
		Context.game.clubs.find(c => c.name === "Giresunspor" && c.country.name === "Turkey").setColors('rgb(117,147,138)', 'black');
		Context.game.clubs.find(c => c.name === "Girona" && c.country.name === "Spain").setColors('rgb(195,113,115)', 'black');
		Context.game.clubs.find(c => c.name === "Go Ahead Eagles" && c.country.name === "Netherlands").setColors('rgb(206,129,40)', 'black');
		Context.game.clubs.find(c => c.name === "Goa" && c.country.name === "India").setColors('rgb(230,107,52)', 'black');
		Context.game.clubs.find(c => c.name === "Godoy Cruz" && c.country.name === "Argentina").setColors('rgb(82,115,180)', 'white');
		Context.game.clubs.find(c => c.name === "Goiás" && c.country.name === "Brazil").setColors('rgb(45,75,73)', 'white');
		Context.game.clubs.find(c => c.name === "Górnik Zabrze" && c.country.name === "Poland").setColors('rgb(185,185,186)', 'black');
		Context.game.clubs.find(c => c.name === "Granada" && c.country.name === "Spain").setColors('rgb(190,127,136)', 'black');
		Context.game.clubs.find(c => c.name === "Grasshopper" && c.country.name === "Switzerland").setColors('rgb(130,139,172)', 'black');
		Context.game.clubs.find(c => c.name === "Grenoble Foot 38" && c.country.name === "France").setColors('rgb(49,88,152)', 'white');
		Context.game.clubs.find(c => c.name === "Grimsby Town" && c.country.name === "England").setColors('rgb(123,122,121)', 'white');
		Context.game.clubs.find(c => c.name === "Guabirá" && c.country.name === "Bolivia").setColors('rgb(189,44,52)', 'white');
		Context.game.clubs.find(c => c.name === "Guangzhou" && c.country.name === "China PR").setColors('rgb(174,61,65)', 'white');
		Context.game.clubs.find(c => c.name === "Guangzhou City" && c.country.name === "China PR").setColors('rgb(166,174,184)', 'black');
		Context.game.clubs.find(c => c.name === "Guaraní" && c.country.name === "Paraguay").setColors('rgb(136,117,39)', 'white');
		Context.game.clubs.find(c => c.name === "Guingamp" && c.country.name === "France").setColors('rgb(192,39,41)', 'white');
		Context.game.clubs.find(c => c.name === "Häcken" && c.country.name === "Sweden").setColors('rgb(122,106,45)', 'white');
		Context.game.clubs.find(c => c.name === "Hajduk Split" && c.country.name === "Croatia").setColors('rgb(229,219,220)', 'black');
		Context.game.clubs.find(c => c.name === "Hallescher FC" && c.country.name === "Germany").setColors('rgb(202,43,52)', 'white');
		Context.game.clubs.find(c => c.name === "Hamburger SV" && c.country.name === "Germany").setColors('rgb(176,181,187)', 'black');
		Context.game.clubs.find(c => c.name === "HamKam" && c.country.name === "Norway").setColors('rgb(229,233,230)', 'black');
		Context.game.clubs.find(c => c.name === "Hammarby" && c.country.name === "Sweden").setColors('rgb(211,219,209)', 'black');
		Context.game.clubs.find(c => c.name === "Hannover 96" && c.country.name === "Germany").setColors('rgb(179,67,69)', 'white');
		Context.game.clubs.find(c => c.name === "Hansa Rostock" && c.country.name === "Germany").setColors('rgb(44,66,107)', 'white');
		Context.game.clubs.find(c => c.name === "Harrogate Town" && c.country.name === "England").setColors('rgb(199,153,60)', 'black');
		Context.game.clubs.find(c => c.name === "Hartberg" && c.country.name === "Austria").setColors('rgb(78,99,143)', 'white');
		Context.game.clubs.find(c => c.name === "Hartlepool United" && c.country.name === "England").setColors('rgb(127,144,172)', 'black');
		Context.game.clubs.find(c => c.name === "Hatayspor" && c.country.name === "Turkey").setColors('rgb(161,122,125)', 'black');
		Context.game.clubs.find(c => c.name === "Haugesund" && c.country.name === "Norway").setColors('rgb(176,195,208)', 'black');
		Context.game.clubs.find(c => c.name === "Hearts" && c.country.name === "Scotland").setColors('rgb(82,56,61)', 'white');
		Context.game.clubs.find(c => c.name === "Hebei" && c.country.name === "China PR").setColors('rgb(151,51,42)', 'white');
		Context.game.clubs.find(c => c.name === "Heidenheim" && c.country.name === "Germany").setColors('rgb(139,59,89)', 'white');
		Context.game.clubs.find(c => c.name === "Hellas Verona" && c.country.name === "Italy").setColors('rgb(50,72,112)', 'white');
		Context.game.clubs.find(c => c.name === "Helsingborg" && c.country.name === "Sweden").setColors('rgb(229,38,41)', 'white');
		Context.game.clubs.find(c => c.name === "Henan" && c.country.name === "China PR").setColors('rgb(136,53,61)', 'white');
		Context.game.clubs.find(c => c.name === "Hermannstadt" && c.country.name === "Romania").setColors('rgb(201,201,198)', 'black');
		Context.game.clubs.find(c => c.name === "Hertha BSC" && c.country.name === "Germany").setColors('rgb(131,136,158)', 'black');
		Context.game.clubs.find(c => c.name === "Hibernian" && c.country.name === "Scotland").setColors('rgb(48,101,67)', 'white');
		Context.game.clubs.find(c => c.name === "HJK" && c.country.name === "Finland").setColors('rgb(159,149,172)', 'black');
		Context.game.clubs.find(c => c.name === "Holstein Kiel" && c.country.name === "Germany").setColors('rgb(105,106,142)', 'white');
		Context.game.clubs.find(c => c.name === "Horsens" && c.country.name === "Denmark").setColors('rgb(194,158,47)', 'black');
		Context.game.clubs.find(c => c.name === "Houston Dynamo" && c.country.name === "United States").setColors('rgb(186,69,49)', 'white');
		Context.game.clubs.find(c => c.name === "Huddersfield Town" && c.country.name === "England").setColors('rgb(125,148,180)', 'black');
		Context.game.clubs.find(c => c.name === "Huesca" && c.country.name === "Spain").setColors('rgb(113,57,78)', 'white');
		Context.game.clubs.find(c => c.name === "Hull City" && c.country.name === "England").setColors('rgb(132,85,50)', 'white');
		Context.game.clubs.find(c => c.name === "Huracán" && c.country.name === "Argentina").setColors('rgb(206,200,200)', 'black');
		Context.game.clubs.find(c => c.name === "Hyderabad" && c.country.name === "India").setColors('rgb(224,187,32)', 'black');
		Context.game.clubs.find(c => c.name === "IFK Göteborg" && c.country.name === "Sweden").setColors('rgb(121,122,177)', 'white');
		Context.game.clubs.find(c => c.name === "Incheon United" && c.country.name === "Korea Republic").setColors('rgb(57,71,140)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente" && c.country.name === "Argentina").setColors('rgb(206,32,32)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente del Valle" && c.country.name === "Ecuador").setColors('rgb(48,50,55)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente Medellín" && c.country.name === "Colombia").setColors('rgb(146,57,58)', 'white');
		Context.game.clubs.find(c => c.name === "Ingolstadt" && c.country.name === "Germany").setColors('rgb(116,41,51)', 'white');
		Context.game.clubs.find(c => c.name === "Inter" && c.country.name === "Italy").setColors('rgb(55,63,97)', 'white');
		Context.game.clubs.find(c => c.name === "Inter Miami" && c.country.name === "United States").setColors('rgb(188,151,172)', 'black');
		Context.game.clubs.find(c => c.name === "Internacional" && c.country.name === "Brazil").setColors('rgb(203,55,63)', 'white');
		Context.game.clubs.find(c => c.name === "Ipswich Town" && c.country.name === "England").setColors('rgb(59,70,115)', 'white');
		Context.game.clubs.find(c => c.name === "İstanbul Başakşehir" && c.country.name === "Turkey").setColors('rgb(232,90,46)', 'black');
		Context.game.clubs.find(c => c.name === "İstanbulspor" && c.country.name === "Turkey").setColors('rgb(199,172,28)', 'black');
		Context.game.clubs.find(c => c.name === "Jagiellonia Białystok" && c.country.name === "Poland").setColors('rgb(195,107,79)', 'black');
		Context.game.clubs.find(c => c.name === "Jahn Regensburg" && c.country.name === "Germany").setColors('rgb(213,202,194)', 'black');
		Context.game.clubs.find(c => c.name === "Jamshedpur" && c.country.name === "India").setColors('rgb(162,69,75)', 'white');
		Context.game.clubs.find(c => c.name === "Jeju United" && c.country.name === "Korea Republic").setColors('rgb(240,122,62)', 'black');
		Context.game.clubs.find(c => c.name === "Jeonbuk Motors" && c.country.name === "Korea Republic").setColors('rgb(56,110,79)', 'white');
		Context.game.clubs.find(c => c.name === "Jerv" && c.country.name === "Norway").setColors('rgb(224,166,79)', 'black');
		Context.game.clubs.find(c => c.name === "Junior" && c.country.name === "Colombia").setColors('rgb(184,126,139)', 'black');
		Context.game.clubs.find(c => c.name === "Juventus" && c.country.name === "Italy").setColors('rgb(151,151,150)', 'black');
		Context.game.clubs.find(c => c.name === "Kaiserslautern" && c.country.name === "Germany").setColors('rgb(168,48,49)', 'white');
		Context.game.clubs.find(c => c.name === "Kaizer Chiefs" && c.country.name === "South Africa").setColors('rgb(198,140,57)', 'black');
		Context.game.clubs.find(c => c.name === "Kalmar" && c.country.name === "Sweden").setColors('rgb(227,67,80)', 'white');
		Context.game.clubs.find(c => c.name === "Karlsruher SC" && c.country.name === "Germany").setColors('rgb(47,69,127)', 'white');
		Context.game.clubs.find(c => c.name === "Kasımpaşa" && c.country.name === "Turkey").setColors('rgb(120,123,131)', 'white');
		Context.game.clubs.find(c => c.name === "Kayserispor" && c.country.name === "Turkey").setColors('rgb(189,87,48)', 'white');
		Context.game.clubs.find(c => c.name === "Kerala Blasters" && c.country.name === "India").setColors('rgb(200,183,53)', 'black');
		Context.game.clubs.find(c => c.name === "Kilmarnock" && c.country.name === "Scotland").setColors('rgb(91,126,176)', 'white');
		Context.game.clubs.find(c => c.name === "København" && c.country.name === "Denmark").setColors('rgb(198,200,205)', 'black');
		Context.game.clubs.find(c => c.name === "Konyaspor" && c.country.name === "Turkey").setColors('rgb(114,149,137)', 'black');
		Context.game.clubs.find(c => c.name === "Korona Kielce" && c.country.name === "Poland").setColors('rgb(220,114,46)', 'black');
		Context.game.clubs.find(c => c.name === "Kortrijk" && c.country.name === "Belgium").setColors('rgb(197,70,75)', 'white');
		Context.game.clubs.find(c => c.name === "Kristiansund" && c.country.name === "Norway").setColors('rgb(59,62,79)', 'white');
		Context.game.clubs.find(c => c.name === "KV Oostende" && c.country.name === "Belgium").setColors('rgb(168,76,69)', 'white');
		Context.game.clubs.find(c => c.name === "LA Galaxy" && c.country.name === "United States").setColors('rgb(192,191,190)', 'black');
		Context.game.clubs.find(c => c.name === "Lanús" && c.country.name === "Argentina").setColors('rgb(132,71,82)', 'white');
		Context.game.clubs.find(c => c.name === "Las Palmas" && c.country.name === "Spain").setColors('rgb(214,185,41)', 'black');
		Context.game.clubs.find(c => c.name === "LASK Linz" && c.country.name === "Austria").setColors('rgb(139,131,130)', 'black');
		Context.game.clubs.find(c => c.name === "Laval" && c.country.name === "France").setColors('rgb(198,109,68)', 'black');
		Context.game.clubs.find(c => c.name === "Lazio" && c.country.name === "Italy").setColors('rgb(101,202,212)', 'black');
		Context.game.clubs.find(c => c.name === "LDU Quito" && c.country.name === "Ecuador").setColors('rgb(192,191,188)', 'black');
		Context.game.clubs.find(c => c.name === "Le Havre" && c.country.name === "France").setColors('rgb(83,111,132)', 'white');
		Context.game.clubs.find(c => c.name === "Lecce" && c.country.name === "Italy").setColors('rgb(201,114,58)', 'black');
		Context.game.clubs.find(c => c.name === "Lech Poznań" && c.country.name === "Poland").setColors('rgb(50,73,128)', 'white');
		Context.game.clubs.find(c => c.name === "Lechia Gdańsk" && c.country.name === "Poland").setColors('rgb(83,133,109)', 'white');
		Context.game.clubs.find(c => c.name === "Leeds United" && c.country.name === "England").setColors('rgb(195,194,193)', 'black');
		Context.game.clubs.find(c => c.name === "Leganés" && c.country.name === "Spain").setColors('rgb(166,187,216)', 'black');
		Context.game.clubs.find(c => c.name === "Legia Warszawa" && c.country.name === "Poland").setColors('rgb(204,203,202)', 'black');
		Context.game.clubs.find(c => c.name === "Leicester City" && c.country.name === "England").setColors('rgb(63,91,143)', 'white');
		Context.game.clubs.find(c => c.name === "Lens" && c.country.name === "France").setColors('rgb(215,168,47)', 'black');
		Context.game.clubs.find(c => c.name === "Levante" && c.country.name === "Spain").setColors('rgb(82,45,63)', 'white');
		Context.game.clubs.find(c => c.name === "Leyton Orient" && c.country.name === "England").setColors('rgb(158,46,49)', 'white');
		Context.game.clubs.find(c => c.name === "Libertad" && c.country.name === "Paraguay").setColors('rgb(150,149,149)', 'black');
		Context.game.clubs.find(c => c.name === "Lille" && c.country.name === "France").setColors('rgb(171,72,79)', 'white');
		Context.game.clubs.find(c => c.name === "Lillestrøm" && c.country.name === "Norway").setColors('rgb(223,195,31)', 'black');
		Context.game.clubs.find(c => c.name === "Lincoln City" && c.country.name === "England").setColors('rgb(195,120,127)', 'black');
		Context.game.clubs.find(c => c.name === "Liverpool" && c.country.name === "England").setColors('rgb(152,46,48)', 'white');
		Context.game.clubs.find(c => c.name === "Liverpool" && c.country.name === "Uruguay").setColors('rgb(58,86,132)', 'white');
		Context.game.clubs.find(c => c.name === "Livingston" && c.country.name === "Scotland").setColors('rgb(210,169,33)', 'black');
		Context.game.clubs.find(c => c.name === "Lorient" && c.country.name === "France").setColors('rgb(203,106,49)', 'black');
		Context.game.clubs.find(c => c.name === "Los Angeles FC" && c.country.name === "United States").setColors('rgb(53,52,50)', 'white');
		Context.game.clubs.find(c => c.name === "Lugano" && c.country.name === "Switzerland").setColors('rgb(87,70,69)', 'white');
		Context.game.clubs.find(c => c.name === "Lugo" && c.country.name === "Spain").setColors('rgb(192,121,121)', 'black');
		Context.game.clubs.find(c => c.name === "Luton Town" && c.country.name === "England").setColors('rgb(193,90,77)', 'white');
		Context.game.clubs.find(c => c.name === "Luzern" && c.country.name === "Switzerland").setColors('rgb(84,63,83)', 'white');
		Context.game.clubs.find(c => c.name === "Lyngby" && c.country.name === "Denmark").setColors('rgb(60,74,132)', 'white');
		Context.game.clubs.find(c => c.name === "Macarthur" && c.country.name === "Australia").setColors('rgb(130,126,97)', 'white');
		Context.game.clubs.find(c => c.name === "Magallanes" && c.country.name === "Chile").setColors('rgb(152,186,204)', 'black');
		Context.game.clubs.find(c => c.name === "Magdeburg" && c.country.name === "Germany").setColors('rgb(51,101,179)', 'white');
		Context.game.clubs.find(c => c.name === "Málaga" && c.country.name === "Spain").setColors('rgb(115,169,197)', 'black');
		Context.game.clubs.find(c => c.name === "Mallorca" && c.country.name === "Spain").setColors('rgb(131,44,45)', 'white');
		Context.game.clubs.find(c => c.name === "Malmö FF" && c.country.name === "Sweden").setColors('rgb(107,170,217)', 'black');
		Context.game.clubs.find(c => c.name === "Mamelodi Sundowns" && c.country.name === "South Africa").setColors('rgb(216,187,36)', 'black');
		Context.game.clubs.find(c => c.name === "Manchester City" && c.country.name === "England").setColors('rgb(104,155,197)', 'black');
		Context.game.clubs.find(c => c.name === "Manchester United" && c.country.name === "England").setColors('rgb(191,47,67)', 'white');
		Context.game.clubs.find(c => c.name === "Mansfield Town" && c.country.name === "England").setColors('rgb(213,143,38)', 'black');
		Context.game.clubs.find(c => c.name === "Marítimo" && c.country.name === "Portugal").setColors('rgb(110,86,70)', 'white');
		Context.game.clubs.find(c => c.name === "Mechelen" && c.country.name === "Belgium").setColors('rgb(193,130,55)', 'black');
		Context.game.clubs.find(c => c.name === "Meizhou Hakka" && c.country.name === "China PR").setColors('rgb(144,50,58)', 'white');
		Context.game.clubs.find(c => c.name === "Melbourne City" && c.country.name === "Australia").setColors('rgb(111,151,180)', 'black');
		Context.game.clubs.find(c => c.name === "Melbourne Victory" && c.country.name === "Australia").setColors('rgb(50,56,66)', 'white');
		Context.game.clubs.find(c => c.name === "Melgar" && c.country.name === "Peru").setColors('rgb(123,44,46)', 'white');
		Context.game.clubs.find(c => c.name === "Meppen" && c.country.name === "Germany").setColors('rgb(65,101,161)', 'white');
		Context.game.clubs.find(c => c.name === "Metropolitanos" && c.country.name === "Venezuela").setColors('rgb(75,73,140)', 'white');
		Context.game.clubs.find(c => c.name === "Metz" && c.country.name === "France").setColors('rgb(96,43,43)', 'white');
		Context.game.clubs.find(c => c.name === "Middlesbrough" && c.country.name === "England").setColors('rgb(204,65,81)', 'white');
		Context.game.clubs.find(c => c.name === "Midtjylland" && c.country.name === "Denmark").setColors('rgb(48,46,46)', 'white');
		Context.game.clubs.find(c => c.name === "Miedź Legnica" && c.country.name === "Poland").setColors('rgb(49,68,161)', 'white');
		Context.game.clubs.find(c => c.name === "Milan" && c.country.name === "Italy").setColors('rgb(99,44,44)', 'white');
		Context.game.clubs.find(c => c.name === "Millonarios" && c.country.name === "Colombia").setColors('rgb(52,74,144)', 'white');
		Context.game.clubs.find(c => c.name === "Millwall" && c.country.name === "England").setColors('rgb(58,62,80)', 'white');
		Context.game.clubs.find(c => c.name === "Milton Keynes Dons" && c.country.name === "England").setColors('rgb(182,181,180)', 'black');
		Context.game.clubs.find(c => c.name === "Minnesota United" && c.country.name === "United States").setColors('rgb(69,69,69)', 'white');
		Context.game.clubs.find(c => c.name === "Mioveni" && c.country.name === "Romania").setColors('rgb(208,180,83)', 'black');
		Context.game.clubs.find(c => c.name === "Mirandés" && c.country.name === "Spain").setColors('rgb(127,46,54)', 'white');
		Context.game.clubs.find(c => c.name === "Mjällby" && c.country.name === "Sweden").setColors('rgb(229,201,49)', 'black');
		Context.game.clubs.find(c => c.name === "Modena" && c.country.name === "Italy").setColors('rgb(208,176,43)', 'black');
		Context.game.clubs.find(c => c.name === "Molde" && c.country.name === "Norway").setColors('rgb(58,85,151)', 'white');
		Context.game.clubs.find(c => c.name === "Monaco" && c.country.name === "France").setColors('rgb(189,111,122)', 'black');
		Context.game.clubs.find(c => c.name === "Monagas" && c.country.name === "Venezuela").setColors('rgb(91,73,87)', 'white');
		Context.game.clubs.find(c => c.name === "Montpellier" && c.country.name === "France").setColors('rgb(81,69,79)', 'white');
		Context.game.clubs.find(c => c.name === "Monza" && c.country.name === "Italy").setColors('rgb(197,73,79)', 'white');
		Context.game.clubs.find(c => c.name === "Morecambe" && c.country.name === "England").setColors('rgb(150,62,66)', 'white');
		Context.game.clubs.find(c => c.name === "Motherwell" && c.country.name === "Scotland").setColors('rgb(199,127,63)', 'black');
		Context.game.clubs.find(c => c.name === "MSV Duisburg" && c.country.name === "Germany").setColors('rgb(145,142,146)', 'black');
		Context.game.clubs.find(c => c.name === "Mumbai City" && c.country.name === "India").setColors('rgb(85,139,183)', 'black');
		Context.game.clubs.find(c => c.name === "Nacional" && c.country.name === "Uruguay").setColors('rgb(220,219,221)', 'black');
		Context.game.clubs.find(c => c.name === "Nantes" && c.country.name === "France").setColors('rgb(227,190,52)', 'black');
		Context.game.clubs.find(c => c.name === "Napoli" && c.country.name === "Italy").setColors('rgb(44,103,197)', 'white');
		Context.game.clubs.find(c => c.name === "Nashville SC" && c.country.name === "United States").setColors('rgb(204,201,72)', 'black');
		Context.game.clubs.find(c => c.name === "NEC" && c.country.name === "Netherlands").setColors('rgb(168,59,65)', 'white');
		Context.game.clubs.find(c => c.name === "New England" && c.country.name === "United States").setColors('rgb(57,62,79)', 'white');
		Context.game.clubs.find(c => c.name === "New York City" && c.country.name === "United States").setColors('rgb(112,134,163)', 'black');
		Context.game.clubs.find(c => c.name === "New York RB" && c.country.name === "United States").setColors('rgb(160,49,59)', 'white');
		Context.game.clubs.find(c => c.name === "Newcastle Jets" && c.country.name === "Australia").setColors('rgb(184,162,118)', 'black');
		Context.game.clubs.find(c => c.name === "Newcastle United" && c.country.name === "England").setColors('rgb(125,134,137)', 'black');
		Context.game.clubs.find(c => c.name === "Newell's Old Boys" && c.country.name === "Argentina").setColors('rgb(126,59,58)', 'white');
		Context.game.clubs.find(c => c.name === "Newport County" && c.country.name === "England").setColors('rgb(210,140,49)', 'black');
		Context.game.clubs.find(c => c.name === "Nice" && c.country.name === "France").setColors('rgb(86,50,49)', 'white');
		Context.game.clubs.find(c => c.name === "Nîmes" && c.country.name === "France").setColors('rgb(209,54,66)', 'white');
		Context.game.clubs.find(c => c.name === "Niort" && c.country.name === "France").setColors('rgb(53,83,148)', 'white');
		Context.game.clubs.find(c => c.name === "Nordsjælland" && c.country.name === "Denmark").setColors('rgb(191,49,42)', 'white');
		Context.game.clubs.find(c => c.name === "Norrköping" && c.country.name === "Sweden").setColors('rgb(204,206,207)', 'black');
		Context.game.clubs.find(c => c.name === "Northampton Town" && c.country.name === "England").setColors('rgb(189,176,174)', 'black');
		Context.game.clubs.find(c => c.name === "NorthEast United" && c.country.name === "India").setColors('rgb(198,197,198)', 'black');
		Context.game.clubs.find(c => c.name === "Norwich City" && c.country.name === "England").setColors('rgb(213,208,62)', 'black');
		Context.game.clubs.find(c => c.name === "Nottingham Forest" && c.country.name === "England").setColors('rgb(183,35,36)', 'white');
		Context.game.clubs.find(c => c.name === "Ñublense" && c.country.name === "Chile").setColors('rgb(170,51,63)', 'white');
		Context.game.clubs.find(c => c.name === "Nürnberg" && c.country.name === "Germany").setColors('rgb(90,49,53)', 'white');
		Context.game.clubs.find(c => c.name === "OB" && c.country.name === "Denmark").setColors('rgb(151,156,193)', 'black');
		Context.game.clubs.find(c => c.name === "Odd" && c.country.name === "Norway").setColors('rgb(203,183,184)', 'black');
		Context.game.clubs.find(c => c.name === "Odisha FC" && c.country.name === "India").setColors('rgb(51,48,53)', 'white');
		Context.game.clubs.find(c => c.name === "OH Leuven" && c.country.name === "Belgium").setColors('rgb(208,205,204)', 'black');
		Context.game.clubs.find(c => c.name === "Olimpia" && c.country.name === "Paraguay").setColors('rgb(170,169,168)', 'black');
		Context.game.clubs.find(c => c.name === "Olympique de Marseille" && c.country.name === "France").setColors('rgb(207,207,209)', 'black');
		Context.game.clubs.find(c => c.name === "Olympique Lyonnais" && c.country.name === "France").setColors('rgb(189,174,178)', 'black');
		Context.game.clubs.find(c => c.name === "Oriente Petrolero" && c.country.name === "Bolivia").setColors('rgb(152,171,154)', 'black');
		Context.game.clubs.find(c => c.name === "Orlando City" && c.country.name === "United States").setColors('rgb(68,63,136)', 'white');
		Context.game.clubs.find(c => c.name === "Orlando Pirates" && c.country.name === "South Africa").setColors('rgb(59,54,56)', 'white');
		Context.game.clubs.find(c => c.name === "Osasuna" && c.country.name === "Spain").setColors('rgb(137,45,53)', 'white');
		Context.game.clubs.find(c => c.name === "Osnabrück" && c.country.name === "Germany").setColors('rgb(106,73,134)', 'white');
		Context.game.clubs.find(c => c.name === "Oxford United" && c.country.name === "England").setColors('rgb(216,187,109)', 'black');
		Context.game.clubs.find(c => c.name === "Paços de Ferreira" && c.country.name === "Portugal").setColors('rgb(225,197,28)', 'black');
		Context.game.clubs.find(c => c.name === "Paderborn" && c.country.name === "Germany").setColors('rgb(50,68,103)', 'white');
		Context.game.clubs.find(c => c.name === "Palermo" && c.country.name === "Italy").setColors('rgb(174,129,148)', 'black');
		Context.game.clubs.find(c => c.name === "Palestino" && c.country.name === "Chile").setColors('rgb(167,114,111)', 'white');
		Context.game.clubs.find(c => c.name === "Palmaflor del Trópico" && c.country.name === "Bolivia").setColors('rgb(221,206,84)', 'black');
		Context.game.clubs.find(c => c.name === "Palmeiras" && c.country.name === "Brazil").setColors('rgb(59,113,95)', 'white');
		Context.game.clubs.find(c => c.name === "Panathinaikos" && c.country.name === "Greece").setColors('rgb(134,155,140)', 'black');
		Context.game.clubs.find(c => c.name === "PAOK" && c.country.name === "Greece").setColors('rgb(151,150,150)', 'black');
		Context.game.clubs.find(c => c.name === "Paris" && c.country.name === "France").setColors('rgb(43,47,57)', 'white');
		Context.game.clubs.find(c => c.name === "Paris Saint Germain" && c.country.name === "France").setColors('rgb(117,108,120)', 'white');
		Context.game.clubs.find(c => c.name === "Parma" && c.country.name === "Italy").setColors('rgb(152,151,149)', 'black');
		Context.game.clubs.find(c => c.name === "Patronato" && c.country.name === "Argentina").setColors('rgb(137,71,76)', 'white');
		Context.game.clubs.find(c => c.name === "Pau" && c.country.name === "France").setColors('rgb(164,148,48)', 'black');
		Context.game.clubs.find(c => c.name === "Peñarol" && c.country.name === "Uruguay").setColors('rgb(151,132,46)', 'black');
		Context.game.clubs.find(c => c.name === "Perth Glory" && c.country.name === "Australia").setColors('rgb(104,64,90)', 'white');
		Context.game.clubs.find(c => c.name === "Perugia" && c.country.name === "Italy").setColors('rgb(175,48,52)', 'white');
		Context.game.clubs.find(c => c.name === "Peterborough United" && c.country.name === "England").setColors('rgb(46,95,150)', 'white');
		Context.game.clubs.find(c => c.name === "Petrolul 52" && c.country.name === "Romania").setColors('rgb(211,191,40)', 'black');
		Context.game.clubs.find(c => c.name === "Philadelphia Union" && c.country.name === "United States").setColors('rgb(58,66,66)', 'white');
		Context.game.clubs.find(c => c.name === "Piast Gliwice" && c.country.name === "Poland").setColors('rgb(144,67,93)', 'white');
		Context.game.clubs.find(c => c.name === "Pisa" && c.country.name === "Italy").setColors('rgb(46,53,80)', 'white');
		Context.game.clubs.find(c => c.name === "Platense" && c.country.name === "Argentina").setColors('rgb(182,181,179)', 'black');
		Context.game.clubs.find(c => c.name === "Plymouth Argyle" && c.country.name === "England").setColors('rgb(58,75,68)', 'white');
		Context.game.clubs.find(c => c.name === "Pogoń Szczecin" && c.country.name === "Poland").setColors('rgb(66,40,52)', 'white');
		Context.game.clubs.find(c => c.name === "Pohang Steelers" && c.country.name === "Korea Republic").setColors('rgb(113,71,63)', 'white');
		Context.game.clubs.find(c => c.name === "Ponferradina" && c.country.name === "Spain").setColors('rgb(125,133,160)', 'black');
		Context.game.clubs.find(c => c.name === "Port Vale" && c.country.name === "England").setColors('rgb(196,196,195)', 'black');
		Context.game.clubs.find(c => c.name === "Portimonense" && c.country.name === "Portugal").setColors('rgb(140,138,138)', 'black');
		Context.game.clubs.find(c => c.name === "Portland Timbers" && c.country.name === "United States").setColors('rgb(60,85,74)', 'white');
		Context.game.clubs.find(c => c.name === "Porto" && c.country.name === "Portugal").setColors('rgb(125,141,172)', 'black');
		Context.game.clubs.find(c => c.name === "Portsmouth" && c.country.name === "England").setColors('rgb(46,84,150)', 'white');
		Context.game.clubs.find(c => c.name === "Preston North End" && c.country.name === "England").setColors('rgb(200,201,205)', 'black');
		Context.game.clubs.find(c => c.name === "PSV" && c.country.name === "Netherlands").setColors('rgb(189,132,132)', 'black');
		Context.game.clubs.find(c => c.name === "Queens Park Rangers" && c.country.name === "England").setColors('rgb(121,153,184)', 'black');
		Context.game.clubs.find(c => c.name === "Quevilly Rouen" && c.country.name === "France").setColors('rgb(212,47,48)', 'white');
		Context.game.clubs.find(c => c.name === "Racing Club" && c.country.name === "Argentina").setColors('rgb(136,179,199)', 'black');
		Context.game.clubs.find(c => c.name === "Racing Santander" && c.country.name === "Spain").setColors('rgb(202,205,197)', 'black');
		Context.game.clubs.find(c => c.name === "Radomiak Radom" && c.country.name === "Poland").setColors('rgb(51,87,62)', 'white');
		Context.game.clubs.find(c => c.name === "Raków Częstochowa" && c.country.name === "Poland").setColors('rgb(132,66,109)', 'white');
		Context.game.clubs.find(c => c.name === "Randers" && c.country.name === "Denmark").setColors('rgb(144,181,205)', 'black');
		Context.game.clubs.find(c => c.name === "Rangers" && c.country.name === "Scotland").setColors('rgb(44,76,160)', 'white');
		Context.game.clubs.find(c => c.name === "Rapid Bucuresti" && c.country.name === "Romania").setColors('rgb(134,61,81)', 'white');
		Context.game.clubs.find(c => c.name === "Rapid Wien" && c.country.name === "Austria").setColors('rgb(135,157,138)', 'black');
		Context.game.clubs.find(c => c.name === "Rayo Vallecano" && c.country.name === "Spain").setColors('rgb(194,151,150)', 'black');
		Context.game.clubs.find(c => c.name === "RB Leipzig" && c.country.name === "Germany").setColors('rgb(218,191,189)', 'black');
		Context.game.clubs.find(c => c.name === "Reading" && c.country.name === "England").setColors('rgb(125,145,178)', 'black');
		Context.game.clubs.find(c => c.name === "Real Betis" && c.country.name === "Spain").setColors('rgb(135,173,150)', 'black');
		Context.game.clubs.find(c => c.name === "Real Madrid" && c.country.name === "Spain").setColors('rgb(205,204,202)', 'black');
		Context.game.clubs.find(c => c.name === "Real Oviedo" && c.country.name === "Spain").setColors('rgb(62,71,105)', 'white');
		Context.game.clubs.find(c => c.name === "Real Salt Lake" && c.country.name === "United States").setColors('rgb(121,58,66)', 'white');
		Context.game.clubs.find(c => c.name === "Real Sociedad" && c.country.name === "Spain").setColors('rgb(130,141,167)', 'black');
		Context.game.clubs.find(c => c.name === "Real Valladolid" && c.country.name === "Spain").setColors('rgb(162,147,162)', 'black');
		Context.game.clubs.find(c => c.name === "Real Zaragoza" && c.country.name === "Spain").setColors('rgb(199,199,204)', 'black');
		Context.game.clubs.find(c => c.name === "Reggina" && c.country.name === "Italy").setColors('rgb(108,42,51)', 'white');
		Context.game.clubs.find(c => c.name === "Rennes" && c.country.name === "France").setColors('rgb(198,58,61)', 'white');
		Context.game.clubs.find(c => c.name === "RFC Seraing" && c.country.name === "Belgium").setColors('rgb(170,69,69)', 'white');
		Context.game.clubs.find(c => c.name === "Rheindorf Altach" && c.country.name === "Austria").setColors('rgb(175,174,170)', 'black');
		Context.game.clubs.find(c => c.name === "Ried" && c.country.name === "Austria").setColors('rgb(85,107,96)', 'white');
		Context.game.clubs.find(c => c.name === "Rio Ave" && c.country.name === "Portugal").setColors('rgb(102,152,140)', 'black');
		Context.game.clubs.find(c => c.name === "Rionegro Águilas" && c.country.name === "Colombia").setColors('rgb(201,179,124)', 'black');
		Context.game.clubs.find(c => c.name === "River Plate" && c.country.name === "Argentina").setColors('rgb(191,151,151)', 'black');
		Context.game.clubs.find(c => c.name === "River Plate" && c.country.name === "Uruguay").setColors('rgb(151,130,132)', 'black');
		Context.game.clubs.find(c => c.name === "RKC Waalwijk" && c.country.name === "Netherlands").setColors('rgb(213,204,43)', 'black');
		Context.game.clubs.find(c => c.name === "Rochdale" && c.country.name === "England").setColors('rgb(50,68,101)', 'white');
		Context.game.clubs.find(c => c.name === "Rodez" && c.country.name === "France").setColors('rgb(133,45,40)', 'white');
		Context.game.clubs.find(c => c.name === "Roma" && c.country.name === "Italy").setColors('rgb(140,37,47)', 'white');
		Context.game.clubs.find(c => c.name === "Rosario Central" && c.country.name === "Argentina").setColors('rgb(141,144,99)', 'black');
		Context.game.clubs.find(c => c.name === "Rosenborg" && c.country.name === "Norway").setColors('rgb(207,206,205)', 'black');
		Context.game.clubs.find(c => c.name === "Ross County" && c.country.name === "Scotland").setColors('rgb(88,51,61)', 'white');
		Context.game.clubs.find(c => c.name === "Rot-Weiss Essen" && c.country.name === "Germany").setColors('rgb(205,195,191)', 'black');
		Context.game.clubs.find(c => c.name === "Rotherham United" && c.country.name === "England").setColors('rgb(170,40,48)', 'white');
		Context.game.clubs.find(c => c.name === "Saarbrücken" && c.country.name === "Germany").setColors('rgb(54,59,81)', 'white');
		Context.game.clubs.find(c => c.name === "Saint-Étienne" && c.country.name === "France").setColors('rgb(41,124,90)', 'white');
		Context.game.clubs.find(c => c.name === "Salernitana" && c.country.name === "Italy").setColors('rgb(91,51,52)', 'white');
		Context.game.clubs.find(c => c.name === "Salford City" && c.country.name === "England").setColors('rgb(205,52,55)', 'white');
		Context.game.clubs.find(c => c.name === "Salzburg" && c.country.name === "Austria").setColors('rgb(210,187,177)', 'black');
		Context.game.clubs.find(c => c.name === "Sampdoria" && c.country.name === "Italy").setColors('rgb(75,99,147)', 'white');
		Context.game.clubs.find(c => c.name === "San Jose Earthquakes" && c.country.name === "United States").setColors('rgb(48,60,91)', 'white');
		Context.game.clubs.find(c => c.name === "San Lorenzo" && c.country.name === "Argentina").setColors('rgb(119,60,95)', 'white');
		Context.game.clubs.find(c => c.name === "Sandefjord" && c.country.name === "Norway").setColors('rgb(66,77,151)', 'white');
		Context.game.clubs.find(c => c.name === "Sandhausen" && c.country.name === "Germany").setColors('rgb(202,202,201)', 'black');
		Context.game.clubs.find(c => c.name === "Santa Clara" && c.country.name === "Portugal").setColors('rgb(177,37,36)', 'white');
		Context.game.clubs.find(c => c.name === "Santa Fe" && c.country.name === "Colombia").setColors('rgb(185,67,68)', 'white');
		Context.game.clubs.find(c => c.name === "Santos" && c.country.name === "Brazil").setColors('rgb(215,215,214)', 'black');
		Context.game.clubs.find(c => c.name === "São Paulo" && c.country.name === "Brazil").setColors('rgb(188,177,177)', 'black');
		Context.game.clubs.find(c => c.name === "Sarmiento" && c.country.name === "Argentina").setColors('rgb(78,117,106)', 'white');
		Context.game.clubs.find(c => c.name === "Sarpsborg 08" && c.country.name === "Norway").setColors('rgb(60,84,167)', 'white');
		Context.game.clubs.find(c => c.name === "Sassuolo" && c.country.name === "Italy").setColors('rgb(50,107,76)', 'white');
		Context.game.clubs.find(c => c.name === "SC Cambuur" && c.country.name === "Netherlands").setColors('rgb(207,194,38)', 'black');
		Context.game.clubs.find(c => c.name === "SC Freiburg" && c.country.name === "Germany").setColors('rgb(170,79,82)', 'white');
		Context.game.clubs.find(c => c.name === "SC Heerenveen" && c.country.name === "Netherlands").setColors('rgb(134,147,191)', 'black');
		Context.game.clubs.find(c => c.name === "Schalke 04" && c.country.name === "Germany").setColors('rgb(48,60,116)', 'white');
		Context.game.clubs.find(c => c.name === "SD Eibar" && c.country.name === "Spain").setColors('rgb(77,52,79)', 'white');
		Context.game.clubs.find(c => c.name === "Seattle Sounders" && c.country.name === "United States").setColors('rgb(77,125,89)', 'white');
		Context.game.clubs.find(c => c.name === "Seongnam" && c.country.name === "Korea Republic").setColors('rgb(59,58,59)', 'white');
		Context.game.clubs.find(c => c.name === "Seoul" && c.country.name === "Korea Republic").setColors('rgb(130,64,64)', 'white');
		Context.game.clubs.find(c => c.name === "Sepsi" && c.country.name === "Romania").setColors('rgb(196,110,117)', 'black');
		Context.game.clubs.find(c => c.name === "Servette" && c.country.name === "Switzerland").setColors('rgb(100,54,60)', 'white');
		Context.game.clubs.find(c => c.name === "Sevilla" && c.country.name === "Spain").setColors('rgb(221,220,219)', 'black');
		Context.game.clubs.find(c => c.name === "Shakhtar Donetsk" && c.country.name === "Ukraine").setColors('rgb(127,77,35)', 'white');
		Context.game.clubs.find(c => c.name === "Shamrock Rovers" && c.country.name === "Republic of Ireland").setColors('rgb(135,148,133)', 'black');
		Context.game.clubs.find(c => c.name === "Shandong Taishan" && c.country.name === "China PR").setColors('rgb(211,106,60)', 'black');
		Context.game.clubs.find(c => c.name === "Shanghai Port" && c.country.name === "China PR").setColors('rgb(153,42,56)', 'white');
		Context.game.clubs.find(c => c.name === "Shanghai Shenhua" && c.country.name === "China PR").setColors('rgb(75,71,123)', 'white');
		Context.game.clubs.find(c => c.name === "Sheffield United" && c.country.name === "England").setColors('rgb(199,122,130)', 'black');
		Context.game.clubs.find(c => c.name === "Sheffield Wednesday" && c.country.name === "England").setColors('rgb(111,124,174)', 'white');
		Context.game.clubs.find(c => c.name === "Shelbourne" && c.country.name === "Republic of Ireland").setColors('rgb(213,47,63)', 'white');
		Context.game.clubs.find(c => c.name === "Shenzhen" && c.country.name === "China PR").setColors('rgb(215,101,49)', 'black');
		Context.game.clubs.find(c => c.name === "Shrewsbury Town" && c.country.name === "England").setColors('rgb(125,117,102)', 'white');
		Context.game.clubs.find(c => c.name === "Silkeborg" && c.country.name === "Denmark").setColors('rgb(189,50,57)', 'white');
		Context.game.clubs.find(c => c.name === "Sint-Truiden" && c.country.name === "Belgium").setColors('rgb(172,156,79)', 'black');
		Context.game.clubs.find(c => c.name === "Sion" && c.country.name === "Switzerland").setColors('rgb(163,55,70)', 'white');
		Context.game.clubs.find(c => c.name === "Sirius" && c.country.name === "Sweden").setColors('rgb(61,86,135)', 'white');
		Context.game.clubs.find(c => c.name === "Sivasspor" && c.country.name === "Turkey").setColors('rgb(165,120,119)', 'black');
		Context.game.clubs.find(c => c.name === "Śląsk Wrocław" && c.country.name === "Poland").setColors('rgb(52,101,68)', 'white');
		Context.game.clubs.find(c => c.name === "Slavia Praha" && c.country.name === "Czech Republic").setColors('rgb(212,121,123)', 'black');
		Context.game.clubs.find(c => c.name === "Sligo Rovers" && c.country.name === "Republic of Ireland").setColors('rgb(150,44,47)', 'white');
		Context.game.clubs.find(c => c.name === "Sochaux" && c.country.name === "France").setColors('rgb(199,190,54)', 'black');
		Context.game.clubs.find(c => c.name === "Southampton" && c.country.name === "England").setColors('rgb(180,119,124)', 'black');
		Context.game.clubs.find(c => c.name === "SPAL" && c.country.name === "Italy").setColors('rgb(129,166,193)', 'black');
		Context.game.clubs.find(c => c.name === "Sparta Praha" && c.country.name === "Czech Republic").setColors('rgb(144,55,68)', 'white');
		Context.game.clubs.find(c => c.name === "Sparta Rotterdam" && c.country.name === "Netherlands").setColors('rgb(212,142,143)', 'black');
		Context.game.clubs.find(c => c.name === "Spezia" && c.country.name === "Italy").setColors('rgb(190,193,190)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Braga" && c.country.name === "Portugal").setColors('rgb(200,44,53)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting Charleroi" && c.country.name === "Belgium").setColors('rgb(103,102,101)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting CP" && c.country.name === "Portugal").setColors('rgb(122,162,144)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Cristal" && c.country.name === "Peru").setColors('rgb(81,166,211)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Gijón" && c.country.name === "Spain").setColors('rgb(193,119,123)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting KC" && c.country.name === "United States").setColors('rgb(129,143,171)', 'black');
		Context.game.clubs.find(c => c.name === "Sportivo Ameliano" && c.country.name === "Paraguay").setColors('rgb(146,151,187)', 'black');
		Context.game.clubs.find(c => c.name === "SpVgg Greuther Fürth" && c.country.name === "Germany").setColors('rgb(106,172,138)', 'black');
		Context.game.clubs.find(c => c.name === "SSC Farul" && c.country.name === "Romania").setColors('rgb(46,100,171)', 'white');
		Context.game.clubs.find(c => c.name === "St Patrick's" && c.country.name === "Republic of Ireland").setColors('rgb(201,52,63)', 'white');
		Context.game.clubs.find(c => c.name === "St. Gallen" && c.country.name === "Switzerland").setColors('rgb(48,97,63)', 'white');
		Context.game.clubs.find(c => c.name === "St. Johnstone" && c.country.name === "Scotland").setColors('rgb(59,80,153)', 'white');
		Context.game.clubs.find(c => c.name === "St. Mirren" && c.country.name === "Scotland").setColors('rgb(135,133,132)', 'black');
		Context.game.clubs.find(c => c.name === "St. Pauli" && c.country.name === "Germany").setColors('rgb(80,69,60)', 'white');
		Context.game.clubs.find(c => c.name === "Stade de Reims" && c.country.name === "France").setColors('rgb(168,55,55)', 'white');
		Context.game.clubs.find(c => c.name === "Stal Mielec" && c.country.name === "Poland").setColors('rgb(196,197,199)', 'black');
		Context.game.clubs.find(c => c.name === "Standard Liège" && c.country.name === "Belgium").setColors('rgb(180,63,68)', 'white');
		Context.game.clubs.find(c => c.name === "Stevenage" && c.country.name === "England").setColors('rgb(137,58,62)', 'white');
		Context.game.clubs.find(c => c.name === "Stockport County" && c.country.name === "England").setColors('rgb(46,91,146)', 'white');
		Context.game.clubs.find(c => c.name === "Stoke City" && c.country.name === "England").setColors('rgb(208,125,129)', 'black');
		Context.game.clubs.find(c => c.name === "Strasbourg" && c.country.name === "France").setColors('rgb(65,86,151)', 'white');
		Context.game.clubs.find(c => c.name === "Strømsgodset" && c.country.name === "Norway").setColors('rgb(65,72,91)', 'white');
		Context.game.clubs.find(c => c.name === "Sturm Graz" && c.country.name === "Austria").setColors('rgb(127,130,138)', 'white');
		Context.game.clubs.find(c => c.name === "Südtirol" && c.country.name === "Italy").setColors('rgb(198,195,192)', 'black');
		Context.game.clubs.find(c => c.name === "Sunderland" && c.country.name === "England").setColors('rgb(188,120,130)', 'black');
		Context.game.clubs.find(c => c.name === "Sutton United" && c.country.name === "England").setColors('rgb(191,156,63)', 'black');
		Context.game.clubs.find(c => c.name === "Suwon" && c.country.name === "Korea Republic").setColors('rgb(117,56,66)', 'white');
		Context.game.clubs.find(c => c.name === "Suwon Bluewings" && c.country.name === "Korea Republic").setColors('rgb(60,74,166)', 'white');
		Context.game.clubs.find(c => c.name === "Swansea City" && c.country.name === "England").setColors('rgb(206,205,204)', 'black');
		Context.game.clubs.find(c => c.name === "Swindon Town" && c.country.name === "England").setColors('rgb(169,44,53)', 'white');
		Context.game.clubs.find(c => c.name === "Sydney" && c.country.name === "Australia").setColors('rgb(82,142,191)', 'black');
		Context.game.clubs.find(c => c.name === "Tacuary" && c.country.name === "Paraguay").setColors('rgb(142,140,134)', 'black');
		Context.game.clubs.find(c => c.name === "Talleres Córdoba" && c.country.name === "Argentina").setColors('rgb(128,128,135)', 'white');
		Context.game.clubs.find(c => c.name === "Tenerife" && c.country.name === "Spain").setColors('rgb(183,189,200)', 'black');
		Context.game.clubs.find(c => c.name === "Ternana" && c.country.name === "Italy").setColors('rgb(116,87,73)', 'white');
		Context.game.clubs.find(c => c.name === "The Strongest" && c.country.name === "Bolivia").setColors('rgb(125,102,58)', 'white');
		Context.game.clubs.find(c => c.name === "Tianjin Jinmen Tiger" && c.country.name === "China PR").setColors('rgb(201,205,212)', 'black');
		Context.game.clubs.find(c => c.name === "Tigre" && c.country.name === "Argentina").setColors('rgb(85,53,114)', 'white');
		Context.game.clubs.find(c => c.name === "Torino" && c.country.name === "Italy").setColors('rgb(124,75,82)', 'white');
		Context.game.clubs.find(c => c.name === "Toronto" && c.country.name === "United States").setColors('rgb(82,77,78)', 'white');
		Context.game.clubs.find(c => c.name === "Tottenham Hotspur" && c.country.name === "England").setColors('rgb(234,227,226)', 'black');
		Context.game.clubs.find(c => c.name === "Toulouse" && c.country.name === "France").setColors('rgb(189,186,195)', 'black');
		Context.game.clubs.find(c => c.name === "Trabzonspor" && c.country.name === "Turkey").setColors('rgb(116,117,141)', 'white');
		Context.game.clubs.find(c => c.name === "Tranmere Rovers" && c.country.name === "England").setColors('rgb(199,200,199)', 'black');
		Context.game.clubs.find(c => c.name === "Tromsø" && c.country.name === "Norway").setColors('rgb(194,135,138)', 'black');
		Context.game.clubs.find(c => c.name === "Troyes" && c.country.name === "France").setColors('rgb(49,78,174)', 'white');
		Context.game.clubs.find(c => c.name === "TSG Hoffenheim" && c.country.name === "Germany").setColors('rgb(51,85,153)', 'white');
		Context.game.clubs.find(c => c.name === "U Craiova 1948" && c.country.name === "Romania").setColors('rgb(40,64,135)', 'white');
		Context.game.clubs.find(c => c.name === "UCD" && c.country.name === "Republic of Ireland").setColors('rgb(79,155,201)', 'black');
		Context.game.clubs.find(c => c.name === "UD Ibiza" && c.country.name === "Spain").setColors('rgb(100,141,189)', 'black');
		Context.game.clubs.find(c => c.name === "Udinese" && c.country.name === "Italy").setColors('rgb(133,134,132)', 'black');
		Context.game.clubs.find(c => c.name === "Ulsan" && c.country.name === "Korea Republic").setColors('rgb(91,86,106)', 'white');
		Context.game.clubs.find(c => c.name === "Ümraniyespor" && c.country.name === "Turkey").setColors('rgb(157,58,55)', 'white');
		Context.game.clubs.find(c => c.name === "Union Saint-Gilloise" && c.country.name === "Belgium").setColors('rgb(213,169,40)', 'black');
		Context.game.clubs.find(c => c.name === "Unión Santa Fe" && c.country.name === "Argentina").setColors('rgb(209,135,135)', 'black');
		Context.game.clubs.find(c => c.name === "Universidad Católica" && c.country.name === "Chile").setColors('rgb(183,190,197)', 'black');
		Context.game.clubs.find(c => c.name === "Universitario" && c.country.name === "Peru").setColors('rgb(200,186,187)', 'black');
		Context.game.clubs.find(c => c.name === "Universitatea Cluj" && c.country.name === "Romania").setColors('rgb(207,202,204)', 'black');
		Context.game.clubs.find(c => c.name === "Universitatea Craiova" && c.country.name === "Romania").setColors('rgb(138,150,170)', 'black');
		Context.game.clubs.find(c => c.name === "UTA Arad" && c.country.name === "Romania").setColors('rgb(219,53,63)', 'white');
		Context.game.clubs.find(c => c.name === "Valencia" && c.country.name === "Spain").setColors('rgb(204,203,201)', 'black');
		Context.game.clubs.find(c => c.name === "Valenciennes" && c.country.name === "France").setColors('rgb(199,56,74)', 'white');
		Context.game.clubs.find(c => c.name === "Vålerenga" && c.country.name === "Norway").setColors('rgb(61,80,169)', 'white');
		Context.game.clubs.find(c => c.name === "Vancouver Whitecaps" && c.country.name === "United States").setColors('rgb(179,176,178)', 'black');
		Context.game.clubs.find(c => c.name === "Varberg BoIS" && c.country.name === "Sweden").setColors('rgb(81,108,89)', 'white');
		Context.game.clubs.find(c => c.name === "Värnamo" && c.country.name === "Sweden").setColors('rgb(221,218,219)', 'black');
		Context.game.clubs.find(c => c.name === "Vélez Sarsfield" && c.country.name === "Argentina").setColors('rgb(186,189,199)', 'black');
		Context.game.clubs.find(c => c.name === "Venezia" && c.country.name === "Italy").setColors('rgb(45,45,42)', 'white');
		Context.game.clubs.find(c => c.name === "Verl" && c.country.name === "Germany").setColors('rgb(124,117,117)', 'white');
		Context.game.clubs.find(c => c.name === "VfB Oldenburg" && c.country.name === "Germany").setColors('rgb(60,63,89)', 'white');
		Context.game.clubs.find(c => c.name === "VfB Stuttgart" && c.country.name === "Germany").setColors('rgb(218,193,195)', 'black');
		Context.game.clubs.find(c => c.name === "VfL Bochum 1848" && c.country.name === "Germany").setColors('rgb(38,65,95)', 'white');
		Context.game.clubs.find(c => c.name === "VfL Wolfsburg" && c.country.name === "Germany").setColors('rgb(119,180,91)', 'black');
		Context.game.clubs.find(c => c.name === "Viborg" && c.country.name === "Denmark").setColors('rgb(40,76,53)', 'white');
		Context.game.clubs.find(c => c.name === "Viking" && c.country.name === "Norway").setColors('rgb(60,63,83)', 'white');
		Context.game.clubs.find(c => c.name === "Viktoria Köln" && c.country.name === "Germany").setColors('rgb(117,50,53)', 'white');
		Context.game.clubs.find(c => c.name === "Viktoria Plzeň" && c.country.name === "Czech Republic").setColors('rgb(157,66,85)', 'white');
		Context.game.clubs.find(c => c.name === "Villarreal" && c.country.name === "Spain").setColors('rgb(208,209,34)', 'black');
		Context.game.clubs.find(c => c.name === "Villarreal II" && c.country.name === "Spain").setColors('rgb(207,209,33)', 'black');
		Context.game.clubs.find(c => c.name === "Vitesse" && c.country.name === "Netherlands").setColors('rgb(132,116,51)', 'white');
		Context.game.clubs.find(c => c.name === "Vitória SC" && c.country.name === "Portugal").setColors('rgb(205,203,198)', 'black');
		Context.game.clubs.find(c => c.name === "Vizela" && c.country.name === "Portugal").setColors('rgb(103,186,208)', 'black');
		Context.game.clubs.find(c => c.name === "Voluntari" && c.country.name === "Romania").setColors('rgb(94,165,230)', 'black');
		Context.game.clubs.find(c => c.name === "Waldhof Mannheim" && c.country.name === "Germany").setColors('rgb(48,67,93)', 'white');
		Context.game.clubs.find(c => c.name === "Walsall" && c.country.name === "England").setColors('rgb(197,42,60)', 'white');
		Context.game.clubs.find(c => c.name === "Warta Poznań" && c.country.name === "Poland").setColors('rgb(40,83,64)', 'white');
		Context.game.clubs.find(c => c.name === "Watford" && c.country.name === "England").setColors('rgb(207,177,32)', 'black');
		Context.game.clubs.find(c => c.name === "Wehen Wiesbaden" && c.country.name === "Germany").setColors('rgb(82,52,53)', 'white');
		Context.game.clubs.find(c => c.name === "Wellington Phoenix" && c.country.name === "Australia").setColors('rgb(136,126,37)', 'white');
		Context.game.clubs.find(c => c.name === "Werder Bremen" && c.country.name === "Germany").setColors('rgb(103,151,132)', 'black');
		Context.game.clubs.find(c => c.name === "West Bromwich Albion" && c.country.name === "England").setColors('rgb(128,133,146)', 'black');
		Context.game.clubs.find(c => c.name === "West Ham United" && c.country.name === "England").setColors('rgb(124,67,81)', 'white');
		Context.game.clubs.find(c => c.name === "Westerlo" && c.country.name === "Belgium").setColors('rgb(207,175,44)', 'black');
		Context.game.clubs.find(c => c.name === "Western Sydney Wanderers" && c.country.name === "Australia").setColors('rgb(98,45,50)', 'white');
		Context.game.clubs.find(c => c.name === "Western United" && c.country.name === "Australia").setColors('rgb(47,76,62)', 'white');
		Context.game.clubs.find(c => c.name === "Widzew Lodz" && c.country.name === "Poland").setColors('rgb(149,54,57)', 'white');
		Context.game.clubs.find(c => c.name === "Wigan Athletic" && c.country.name === "England").setColors('rgb(99,115,150)', 'white');
		Context.game.clubs.find(c => c.name === "Winterthur" && c.country.name === "Switzerland").setColors('rgb(159,45,46)', 'white');
		Context.game.clubs.find(c => c.name === "Wisła Płock" && c.country.name === "Poland").setColors('rgb(44,80,149)', 'white');
		Context.game.clubs.find(c => c.name === "Wolfsberger AC" && c.country.name === "Austria").setColors('rgb(195,193,190)', 'black');
		Context.game.clubs.find(c => c.name === "Wolverhampton Wanderers" && c.country.name === "England").setColors('rgb(218,163,31)', 'black');
		Context.game.clubs.find(c => c.name === "Wrexham" && c.country.name === "England").setColors('rgb(190,40,55)', 'white');
		Context.game.clubs.find(c => c.name === "WSG Tirol" && c.country.name === "Austria").setColors('rgb(132,176,166)', 'black');
		Context.game.clubs.find(c => c.name === "Wuhan Three Towns" && c.country.name === "China PR").setColors('rgb(71,84,132)', 'white');
		Context.game.clubs.find(c => c.name === "Wuhan Zall" && c.country.name === "China PR").setColors('rgb(227,147,71)', 'black');
		Context.game.clubs.find(c => c.name === "Wycombe Wanderers" && c.country.name === "England").setColors('rgb(55,103,139)', 'white');
		Context.game.clubs.find(c => c.name === "Young Boys" && c.country.name === "Switzerland").setColors('rgb(186,166,64)', 'black');
		Context.game.clubs.find(c => c.name === "Zagłębie Lubin" && c.country.name === "Poland").setColors('rgb(199,75,40)', 'white');
		Context.game.clubs.find(c => c.name === "Zhejiang" && c.country.name === "China PR").setColors('rgb(49,102,63)', 'white');
		Context.game.clubs.find(c => c.name === "Zulte-Waregem" && c.country.name === "Belgium").setColors('rgb(204,179,178)', 'black');
		Context.game.clubs.find(c => c.name === "Zürich" && c.country.name === "Switzerland").setColors('rgb(194,196,201)', 'black');
		Context.game.clubs.find(c => c.name === "Zwickau" && c.country.name === "Germany").setColors('rgb(219,102,106)', 'black');
	}

}