class ColorManager {
	static setClubsColors() {
		Context.game.clubs.find(c => c.name === "Aalesund" && c.country.name === "Norway").setColors('rgb(197,88,59)', 'white');
		Context.game.clubs.find(c => c.name === "Abha" && c.country.name === "Saudi Arabia").setColors('rgb(162,184,202)', 'black');
		Context.game.clubs.find(c => c.name === "AFC Bournemouth" && c.country.name === "England").setColors('rgb(130,48,52)', 'white');
		Context.game.clubs.find(c => c.name === "Accrington Stanley" && c.country.name === "England").setColors('rgb(191,52,66)', 'white');
		Context.game.clubs.find(c => c.name === "Adana Demirspor" && c.country.name === "Turkey").setColors('rgb(59,102,151)', 'white');
		Context.game.clubs.find(c => c.name === "Adelaide United" && c.country.name === "Australia").setColors('rgb(152,46,57)', 'white');
		Context.game.clubs.find(c => c.name === "1860 München" && c.country.name === "Germany").setColors('rgb(187,196,204)', 'black');
		Context.game.clubs.find(c => c.name === "Aberdeen" && c.country.name === "Scotland").setColors('rgb(147,50,60)', 'white');
		Context.game.clubs.find(c => c.name === "AaB" && c.country.name === "Denmark").setColors('rgb(218,130,133)', 'black');
		Context.game.clubs.find(c => c.name === "AEK Athens" && c.country.name === "Greece").setColors('rgb(136,114,47)', 'white');
		Context.game.clubs.find(c => c.name === "Academia Puerto Cabello" && c.country.name === "Venezuela").setColors('rgb(152,91,93)', 'white');
		Context.game.clubs.find(c => c.name === "AFC Wimbledon" && c.country.name === "England").setColors('rgb(74,107,147)', 'white');
		Context.game.clubs.find(c => c.name === "AGF" && c.country.name === "Denmark").setColors('rgb(202,189,190)', 'black');
		Context.game.clubs.find(c => c.name === "AIK" && c.country.name === "Sweden").setColors('rgb(60,59,49)', 'white');
		Context.game.clubs.find(c => c.name === "Ajaccio" && c.country.name === "France").setColors('rgb(168,127,130)', 'black');
		Context.game.clubs.find(c => c.name === "Al Adalah" && c.country.name === "Saudi Arabia").setColors('rgb(195,195,199)', 'black');
		Context.game.clubs.find(c => c.name === "Ajax" && c.country.name === "Netherlands").setColors('rgb(165,105,115)', 'white');
		Context.game.clubs.find(c => c.name === "Al Feiha" && c.country.name === "Saudi Arabia").setColors('rgb(203,80,43)', 'white');
		Context.game.clubs.find(c => c.name === "Al Fateh" && c.country.name === "Saudi Arabia").setColors('rgb(46,66,124)', 'white');
		Context.game.clubs.find(c => c.name === "Al Batin" && c.country.name === "Saudi Arabia").setColors('rgb(99,169,225)', 'black');
		Context.game.clubs.find(c => c.name === "Al Hilal" && c.country.name === "Saudi Arabia").setColors('rgb(59,67,153)', 'white');
		Context.game.clubs.find(c => c.name === "Al Ittihad" && c.country.name === "Saudi Arabia").setColors('rgb(128,115,54)', 'white');
		Context.game.clubs.find(c => c.name === "Al Ain" && c.country.name === "United Arab Emirates").setColors('rgb(60,52,68)', 'white');
		Context.game.clubs.find(c => c.name === "Al Nassr" && c.country.name === "Saudi Arabia").setColors('rgb(191,191,108)', 'black');
		Context.game.clubs.find(c => c.name === "Al Khaleej" && c.country.name === "Saudi Arabia").setColors('rgb(216,193,37)', 'black');
		Context.game.clubs.find(c => c.name === "Al Ettifaq" && c.country.name === "Saudi Arabia").setColors('rgb(64,131,97)', 'white');
		Context.game.clubs.find(c => c.name === "Al Raed" && c.country.name === "Saudi Arabia").setColors('rgb(148,65,68)', 'white');
		Context.game.clubs.find(c => c.name === "Al Shabab" && c.country.name === "Saudi Arabia").setColors('rgb(198,193,191)', 'black');
		Context.game.clubs.find(c => c.name === "Al Taawon" && c.country.name === "Saudi Arabia").setColors('rgb(208,187,41)', 'black');
		Context.game.clubs.find(c => c.name === "Al Tai" && c.country.name === "Saudi Arabia").setColors('rgb(167,171,176)', 'black');
		Context.game.clubs.find(c => c.name === "Al Wahda" && c.country.name === "Saudi Arabia").setColors('rgb(190,60,62)', 'white');
		Context.game.clubs.find(c => c.name === "Albacete" && c.country.name === "Spain").setColors('rgb(197,191,191)', 'black');
		Context.game.clubs.find(c => c.name === "Aldosivi" && c.country.name === "Argentina").setColors('rgb(129,158,68)', 'black');
		Context.game.clubs.find(c => c.name === "Alanyaspor" && c.country.name === "Turkey").setColors('rgb(91,85,57)', 'white');
		Context.game.clubs.find(c => c.name === "Almería" && c.country.name === "Spain").setColors('rgb(201,104,104)', 'black');
		Context.game.clubs.find(c => c.name === "Alianza Lima" && c.country.name === "Peru").setColors('rgb(133,133,148)', 'black');
		Context.game.clubs.find(c => c.name === "América Mineiro" && c.country.name === "Brazil").setColors('rgb(48,101,66)', 'white');
		Context.game.clubs.find(c => c.name === "Amiens SC" && c.country.name === "France").setColors('rgb(193,190,192)', 'black');
		Context.game.clubs.find(c => c.name === "Anderlecht" && c.country.name === "Belgium").setColors('rgb(69,56,112)', 'white');
		Context.game.clubs.find(c => c.name === "Annecy" && c.country.name === "France").setColors('rgb(106,38,42)', 'white');
		Context.game.clubs.find(c => c.name === "Angers SCO" && c.country.name === "France").setColors('rgb(86,84,83)', 'white');
		Context.game.clubs.find(c => c.name === "Antwerp" && c.country.name === "Belgium").setColors('rgb(174,57,61)', 'white');
		Context.game.clubs.find(c => c.name === "Argentinos Juniors" && c.country.name === "Argentina").setColors('rgb(204,83,78)', 'white');
		Context.game.clubs.find(c => c.name === "Arouca" && c.country.name === "Portugal").setColors('rgb(205,192,45)', 'black');
		Context.game.clubs.find(c => c.name === "Atalanta" && c.country.name === "Italy").setColors('rgb(69,91,106)', 'white');
		Context.game.clubs.find(c => c.name === "Arsenal de Sarandi" && c.country.name === "Argentina").setColors('rgb(156,155,174)', 'black');
		Context.game.clubs.find(c => c.name === "Atlanta United" && c.country.name === "United States").setColors('rgb(88,50,51)', 'white');
		Context.game.clubs.find(c => c.name === "Ascoli" && c.country.name === "Italy").setColors('rgb(128,128,127)', 'white');
		Context.game.clubs.find(c => c.name === "Athletico Paranaense" && c.country.name === "Brazil").setColors('rgb(141,53,53)', 'white');
		Context.game.clubs.find(c => c.name === "Audax Italiano" && c.country.name === "Chile").setColors('rgb(61,119,89)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Tucumán" && c.country.name === "Argentina").setColors('rgb(172,195,211)', 'black');
		Context.game.clubs.find(c => c.name === "Ankaragücü" && c.country.name === "Turkey").setColors('rgb(115,112,60)', 'white');
		Context.game.clubs.find(c => c.name === "Antalyaspor" && c.country.name === "Turkey").setColors('rgb(207,133,135)', 'black');
		Context.game.clubs.find(c => c.name === "APOEL" && c.country.name === "Cyprus").setColors('rgb(151,146,98)', 'black');
		Context.game.clubs.find(c => c.name === "Atlético Mineiro" && c.country.name === "Brazil").setColors('rgb(120,118,116)', 'white');
		Context.game.clubs.find(c => c.name === "Argeş" && c.country.name === "Romania").setColors('rgb(90,61,118)', 'white');
		Context.game.clubs.find(c => c.name === "Atlético Madrid" && c.country.name === "Spain").setColors('rgb(191,130,134)', 'black');
		Context.game.clubs.find(c => c.name === "Athletic Club" && c.country.name === "Spain").setColors('rgb(182,111,114)', 'black');
		Context.game.clubs.find(c => c.name === "Arsenal" && c.country.name === "England").setColors('rgb(168,65,74)', 'white');
		Context.game.clubs.find(c => c.name === "AS Eupen" && c.country.name === "Belgium").setColors('rgb(216,216,214)', 'black');
		Context.game.clubs.find(c => c.name === "ATK Mohun Bagan" && c.country.name === "India").setColors('rgb(116,104,92)', 'white');
		Context.game.clubs.find(c => c.name === "Austin" && c.country.name === "United States").setColors('rgb(42,98,64)', 'white');
		Context.game.clubs.find(c => c.name === "Aston Villa" && c.country.name === "England").setColors('rgb(105,67,93)', 'white');
		Context.game.clubs.find(c => c.name === "AZ Alkmaar" && c.country.name === "Netherlands").setColors('rgb(180,46,47)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Wien" && c.country.name === "Austria").setColors('rgb(78,55,114)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Klagenfurt" && c.country.name === "Austria").setColors('rgb(104,48,141)', 'white');
		Context.game.clubs.find(c => c.name === "Aucas" && c.country.name === "Ecuador").setColors('rgb(206,166,47)', 'black');
		Context.game.clubs.find(c => c.name === "Atlético Nacional" && c.country.name === "Colombia").setColors('rgb(137,161,147)', 'black');
		Context.game.clubs.find(c => c.name === "Barcelona Guayaquil" && c.country.name === "Ecuador").setColors('rgb(213,170,41)', 'black');
		Context.game.clubs.find(c => c.name === "Bastia" && c.country.name === "France").setColors('rgb(64,74,124)', 'white');
		Context.game.clubs.find(c => c.name === "Bayreuth" && c.country.name === "Germany").setColors('rgb(222,178,47)', 'black');
		Context.game.clubs.find(c => c.name === "Barrow" && c.country.name === "England").setColors('rgb(129,164,184)', 'black');
		Context.game.clubs.find(c => c.name === "Barnsley" && c.country.name === "England").setColors('rgb(191,43,58)', 'white');
		Context.game.clubs.find(c => c.name === "Benevento" && c.country.name === "Italy").setColors('rgb(175,113,44)', 'white');
		Context.game.clubs.find(c => c.name === "Bengaluru" && c.country.name === "India").setColors('rgb(76,69,126)', 'white');
		Context.game.clubs.find(c => c.name === "Austria Lustenau" && c.country.name === "Austria").setColors('rgb(60,163,98)', 'black');
		Context.game.clubs.find(c => c.name === "Birmingham City" && c.country.name === "England").setColors('rgb(57,88,143)', 'white');
		Context.game.clubs.find(c => c.name === "Auxerre" && c.country.name === "France").setColors('rgb(192,195,200)', 'black');
		Context.game.clubs.find(c => c.name === "Banfield" && c.country.name === "Argentina").setColors('rgb(115,138,129)', 'black');
		Context.game.clubs.find(c => c.name === "Blackpool" && c.country.name === "England").setColors('rgb(211,94,54)', 'white');
		Context.game.clubs.find(c => c.name === "Bari 1908" && c.country.name === "Italy").setColors('rgb(205,187,188)', 'black');
		Context.game.clubs.find(c => c.name === "Boavista" && c.country.name === "Portugal").setColors('rgb(128,123,122)', 'white');
		Context.game.clubs.find(c => c.name === "Bayer 04 Leverkusen" && c.country.name === "Germany").setColors('rgb(165,54,66)', 'white');
		Context.game.clubs.find(c => c.name === "Beijing Guoan" && c.country.name === "China PR").setColors('rgb(48,72,50)', 'white');
		Context.game.clubs.find(c => c.name === "Bodø / Glimt" && c.country.name === "Norway").setColors('rgb(198,154,80)', 'black');
		Context.game.clubs.find(c => c.name === "Basel" && c.country.name === "Switzerland").setColors('rgb(131,64,102)', 'white');
		Context.game.clubs.find(c => c.name === "Bolton Wanderers" && c.country.name === "England").setColors('rgb(193,193,191)', 'black');
		Context.game.clubs.find(c => c.name === "Blackburn Rovers" && c.country.name === "England").setColors('rgb(140,153,186)', 'black');
		Context.game.clubs.find(c => c.name === "Barracas Central" && c.country.name === "Argentina").setColors('rgb(210,152,151)', 'black');
		Context.game.clubs.find(c => c.name === "Bolívar" && c.country.name === "Bolivia").setColors('rgb(85,133,186)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Dortmund" && c.country.name === "Germany").setColors('rgb(162,140,41)', 'black');
		Context.game.clubs.find(c => c.name === "Benfica" && c.country.name === "Portugal").setColors('rgb(213,49,59)', 'white');
		Context.game.clubs.find(c => c.name === "Beşiktaş" && c.country.name === "Turkey").setColors('rgb(209,207,206)', 'black');
		Context.game.clubs.find(c => c.name === "Blooming" && c.country.name === "Bolivia").setColors('rgb(85,120,174)', 'white');
		Context.game.clubs.find(c => c.name === "Boca Juniors" && c.country.name === "Argentina").setColors('rgb(98,106,115)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Mönchengladbach" && c.country.name === "Germany").setColors('rgb(176,183,179)', 'black');
		Context.game.clubs.find(c => c.name === "Bohemians" && c.country.name === "Republic of Ireland").setColors('rgb(91,56,55)', 'white');
		Context.game.clubs.find(c => c.name === "Bordeaux" && c.country.name === "France").setColors('rgb(81,82,87)', 'white');
		Context.game.clubs.find(c => c.name === "Botoşani" && c.country.name === "Romania").setColors('rgb(202,200,201)', 'black');
		Context.game.clubs.find(c => c.name === "Bragantino" && c.country.name === "Brazil").setColors('rgb(213,196,197)', 'black');
		Context.game.clubs.find(c => c.name === "Bologna" && c.country.name === "Italy").setColors('rgb(107,57,67)', 'white');
		Context.game.clubs.find(c => c.name === "Borussia Dortmund II" && c.country.name === "Germany").setColors('rgb(162,140,43)', 'black');
		Context.game.clubs.find(c => c.name === "Bristol City" && c.country.name === "England").setColors('rgb(182,72,77)', 'white');
		Context.game.clubs.find(c => c.name === "Brescia" && c.country.name === "Italy").setColors('rgb(75,112,160)', 'white');
		Context.game.clubs.find(c => c.name === "Brighton & Hove Albion" && c.country.name === "England").setColors('rgb(118,146,173)', 'black');
		Context.game.clubs.find(c => c.name === "Burnley" && c.country.name === "England").setColors('rgb(121,86,103)', 'white');
		Context.game.clubs.find(c => c.name === "Brøndby" && c.country.name === "Denmark").setColors('rgb(208,178,45)', 'black');
		Context.game.clubs.find(c => c.name === "Cádiz" && c.country.name === "Spain").setColors('rgb(218,205,53)', 'black');
		Context.game.clubs.find(c => c.name === "Cardiff City" && c.country.name === "England").setColors('rgb(46,79,162)', 'white');
		Context.game.clubs.find(c => c.name === "Cagliari" && c.country.name === "Italy").setColors('rgb(123,52,76)', 'white');
		Context.game.clubs.find(c => c.name === "Botafogo" && c.country.name === "Brazil").setColors('rgb(108,108,107)', 'white');
		Context.game.clubs.find(c => c.name === "Bradford City" && c.country.name === "England").setColors('rgb(165,93,58)', 'white');
		Context.game.clubs.find(c => c.name === "Celtic" && c.country.name === "Scotland").setColors('rgb(129,154,135)', 'black');
		Context.game.clubs.find(c => c.name === "Brentford" && c.country.name === "England").setColors('rgb(193,119,122)', 'black');
		Context.game.clubs.find(c => c.name === "Cerro Porteño" && c.country.name === "Paraguay").setColors('rgb(122,64,113)', 'white');
		Context.game.clubs.find(c => c.name === "Bristol Rovers" && c.country.name === "England").setColors('rgb(113,128,154)', 'white');
		Context.game.clubs.find(c => c.name === "Brisbane Roar" && c.country.name === "Australia").setColors('rgb(173,80,44)', 'white');
		Context.game.clubs.find(c => c.name === "Brest" && c.country.name === "France").setColors('rgb(200,56,60)', 'white');
		Context.game.clubs.find(c => c.name === "Burton Albion" && c.country.name === "England").setColors('rgb(213,196,37)', 'black');
		Context.game.clubs.find(c => c.name === "Burgos" && c.country.name === "Spain").setColors('rgb(206,206,205)', 'black');
		Context.game.clubs.find(c => c.name === "Caen" && c.country.name === "France").setColors('rgb(89,78,107)', 'white');
		Context.game.clubs.find(c => c.name === "Cambridge United" && c.country.name === "England").setColors('rgb(202,132,56)', 'black');
		Context.game.clubs.find(c => c.name === "Carlisle United" && c.country.name === "England").setColors('rgb(50,56,75)', 'white');
		Context.game.clubs.find(c => c.name === "Central Coast Mariners" && c.country.name === "Australia").setColors('rgb(164,136,68)', 'black');
		Context.game.clubs.find(c => c.name === "Changchun Yatai" && c.country.name === "China PR").setColors('rgb(175,60,70)', 'white');
		Context.game.clubs.find(c => c.name === "Chelsea" && c.country.name === "England").setColors('rgb(61,72,116)', 'white');
		Context.game.clubs.find(c => c.name === "César Vallejo" && c.country.name === "Peru").setColors('rgb(227,103,64)', 'black');
		Context.game.clubs.find(c => c.name === "Chicago Fire" && c.country.name === "United States").setColors('rgb(48,55,81)', 'white');
		Context.game.clubs.find(c => c.name === "Colchester United" && c.country.name === "England").setColors('rgb(149,155,191)', 'black');
		Context.game.clubs.find(c => c.name === "Columbus Crew" && c.country.name === "United States").setColors('rgb(210,188,37)', 'black');
		Context.game.clubs.find(c => c.name === "Cittadella" && c.country.name === "Italy").setColors('rgb(160,46,74)', 'white');
		Context.game.clubs.find(c => c.name === "Coventry City" && c.country.name === "England").setColors('rgb(147,173,190)', 'black');
		Context.game.clubs.find(c => c.name === "Crewe Alexandra" && c.country.name === "England").setColors('rgb(200,48,48)', 'white');
		Context.game.clubs.find(c => c.name === "Cangzhou Mighty Lions" && c.country.name === "China PR").setColors('rgb(47,77,148)', 'white');
		Context.game.clubs.find(c => c.name === "Dallas" && c.country.name === "United States").setColors('rgb(152,60,85)', 'white');
		Context.game.clubs.find(c => c.name === "Casa Pia" && c.country.name === "Portugal").setColors('rgb(52,51,49)', 'white');
		Context.game.clubs.find(c => c.name === "Central Cordoba SdE" && c.country.name === "Argentina").setColors('rgb(136,136,139)', 'black');
		Context.game.clubs.find(c => c.name === "CF Montréal" && c.country.name === "United States").setColors('rgb(55,55,56)', 'white');
		Context.game.clubs.find(c => c.name === "Cheltenham Town" && c.country.name === "England").setColors('rgb(185,47,63)', 'white');
		Context.game.clubs.find(c => c.name === "Charlotte" && c.country.name === "United States").setColors('rgb(80,147,190)', 'black');
		Context.game.clubs.find(c => c.name === "Chindia Târgovişte" && c.country.name === "Romania").setColors('rgb(178,74,77)', 'white');
		Context.game.clubs.find(c => c.name === "Colo-Colo" && c.country.name === "Chile").setColors('rgb(197,194,193)', 'black');
		Context.game.clubs.find(c => c.name === "Como" && c.country.name === "Italy").setColors('rgb(84,141,179)', 'black');
		Context.game.clubs.find(c => c.name === "Cracovia Kraków" && c.country.name === "Poland").setColors('rgb(194,122,125)', 'black');
		Context.game.clubs.find(c => c.name === "Clermont" && c.country.name === "France").setColors('rgb(148,41,65)', 'white');
		Context.game.clubs.find(c => c.name === "Crystal Palace" && c.country.name === "England").setColors('rgb(122,68,87)', 'white');
		Context.game.clubs.find(c => c.name === "Caracas" && c.country.name === "Venezuela").setColors('rgb(167,63,49)', 'white');
		Context.game.clubs.find(c => c.name === "Celta de Vigo" && c.country.name === "Spain").setColors('rgb(118,164,175)', 'black');
		Context.game.clubs.find(c => c.name === "Damac" && c.country.name === "Saudi Arabia").setColors('rgb(180,47,48)', 'white');
		Context.game.clubs.find(c => c.name === "Cercle Brugge" && c.country.name === "Belgium").setColors('rgb(64,87,69)', 'white');
		Context.game.clubs.find(c => c.name === "CFR Cluj" && c.country.name === "Romania").setColors('rgb(117,49,48)', 'white');
		Context.game.clubs.find(c => c.name === "Chengdu Rongcheng" && c.country.name === "China PR").setColors('rgb(150,55,64)', 'white');
		Context.game.clubs.find(c => c.name === "Cienciano" && c.country.name === "Peru").setColors('rgb(186,53,51)', 'white');
		Context.game.clubs.find(c => c.name === "Corinthians" && c.country.name === "Brazil").setColors('rgb(207,206,204)', 'black');
		Context.game.clubs.find(c => c.name === "Colón" && c.country.name === "Argentina").setColors('rgb(122,69,65)', 'white');
		Context.game.clubs.find(c => c.name === "Charlton Athletic" && c.country.name === "England").setColors('rgb(181,59,61)', 'white');
		Context.game.clubs.find(c => c.name === "Club Brugge" && c.country.name === "Belgium").setColors('rgb(45,85,124)', 'white');
		Context.game.clubs.find(c => c.name === "Crawley Town" && c.country.name === "England").setColors('rgb(174,54,56)', 'white');
		Context.game.clubs.find(c => c.name === "DC United" && c.country.name === "United States").setColors('rgb(63,61,60)', 'white');
		Context.game.clubs.find(c => c.name === "Daegu" && c.country.name === "Korea Republic").setColors('rgb(134,179,198)', 'black');
		Context.game.clubs.find(c => c.name === "Delfin" && c.country.name === "Ecuador").setColors('rgb(75,85,147)', 'white');
		Context.game.clubs.find(c => c.name === "Derry City" && c.country.name === "Republic of Ireland").setColors('rgb(204,77,80)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Cuenca" && c.country.name === "Ecuador").setColors('rgb(155,74,69)', 'white');
		Context.game.clubs.find(c => c.name === "Danubio" && c.country.name === "Uruguay").setColors('rgb(157,156,155)', 'black');
		Context.game.clubs.find(c => c.name === "Chennaiyin" && c.country.name === "India").setColors('rgb(59,64,141)', 'white');
		Context.game.clubs.find(c => c.name === "Colorado Rapids" && c.country.name === "United States").setColors('rgb(84,53,61)', 'white');
		Context.game.clubs.find(c => c.name === "Cincinnati" && c.country.name === "United States").setColors('rgb(56,75,119)', 'white');
		Context.game.clubs.find(c => c.name === "Cosenza" && c.country.name === "Italy").setColors('rgb(116,50,60)', 'white');
		Context.game.clubs.find(c => c.name === "Chaves" && c.country.name === "Portugal").setColors('rgb(77,83,140)', 'white');
		Context.game.clubs.find(c => c.name === "Defensa y Justicia" && c.country.name === "Argentina").setColors('rgb(214,185,64)', 'black');
		Context.game.clubs.find(c => c.name === "Dalian Professional" && c.country.name === "China PR").setColors('rgb(49,152,206)', 'black');
		Context.game.clubs.find(c => c.name === "Cremonese" && c.country.name === "Italy").setColors('rgb(177,79,88)', 'white');
		Context.game.clubs.find(c => c.name === "Deportes Tolima" && c.country.name === "Colombia").setColors('rgb(188,117,89)', 'black');
		Context.game.clubs.find(c => c.name === "Cobresal" && c.country.name === "Chile").setColors('rgb(200,151,141)', 'black');
		Context.game.clubs.find(c => c.name === "Dijon" && c.country.name === "France").setColors('rgb(172,61,66)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Pereira" && c.country.name === "Colombia").setColors('rgb(190,116,45)', 'black');
		Context.game.clubs.find(c => c.name === "Darmstadt 98" && c.country.name === "Germany").setColors('rgb(52,74,118)', 'white');
		Context.game.clubs.find(c => c.name === "Doncaster Rovers" && c.country.name === "England").setColors('rgb(197,130,134)', 'black');
		Context.game.clubs.find(c => c.name === "Dundee United" && c.country.name === "Scotland").setColors('rgb(206,93,41)', 'white');
		Context.game.clubs.find(c => c.name === "Eintracht Braunschweig" && c.country.name === "Germany").setColors('rgb(160,153,83)', 'black');
		Context.game.clubs.find(c => c.name === "Espanyol" && c.country.name === "Spain").setColors('rgb(99,144,196)', 'black');
		Context.game.clubs.find(c => c.name === "Defensor Sporting" && c.country.name === "Uruguay").setColors('rgb(111,88,150)', 'white');
		Context.game.clubs.find(c => c.name === "Elversberg" && c.country.name === "Germany").setColors('rgb(186,185,182)', 'black');
		Context.game.clubs.find(c => c.name === "Fatih Karagümrük" && c.country.name === "Turkey").setColors('rgb(101,43,50)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Alavés" && c.country.name === "Spain").setColors('rgb(129,147,171)', 'black');
		Context.game.clubs.find(c => c.name === "FC Bayern München" && c.country.name === "Germany").setColors('rgb(197,56,58)', 'white');
		Context.game.clubs.find(c => c.name === "Dinamo Zagreb" && c.country.name === "Croatia").setColors('rgb(59,68,118)', 'white');
		Context.game.clubs.find(c => c.name === "Everton" && c.country.name === "England").setColors('rgb(51,81,122)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Táchira" && c.country.name === "Venezuela").setColors('rgb(141,120,61)', 'white');
		Context.game.clubs.find(c => c.name === "FC Köln" && c.country.name === "Germany").setColors('rgb(198,120,121)', 'black');
		Context.game.clubs.find(c => c.name === "Drogheda United" && c.country.name === "Republic of Ireland").setColors('rgb(156,79,98)', 'white');
		Context.game.clubs.find(c => c.name === "Dynamo Dresden" && c.country.name === "Germany").setColors('rgb(186,131,52)', 'black');
		Context.game.clubs.find(c => c.name === "Eintracht Frankfurt" && c.country.name === "Germany").setColors('rgb(200,199,198)', 'black');
		Context.game.clubs.find(c => c.name === "Degerfors" && c.country.name === "Sweden").setColors('rgb(211,64,68)', 'white');
		Context.game.clubs.find(c => c.name === "Estoril" && c.country.name === "Portugal").setColors('rgb(207,167,47)', 'black');
		Context.game.clubs.find(c => c.name === "FC Andorra" && c.country.name === "Spain").setColors('rgb(144,112,103)', 'white');
		Context.game.clubs.find(c => c.name === "Emelec" && c.country.name === "Ecuador").setColors('rgb(78,92,142)', 'white');
		Context.game.clubs.find(c => c.name === "Deportivo Binacional" && c.country.name === "Peru").setColors('rgb(73,139,220)', 'black');
		Context.game.clubs.find(c => c.name === "Djurgården" && c.country.name === "Sweden").setColors('rgb(76,115,145)', 'white');
		Context.game.clubs.find(c => c.name === "Derby County" && c.country.name === "England").setColors('rgb(182,181,180)', 'black');
		Context.game.clubs.find(c => c.name === "FC Cartagena" && c.country.name === "Spain").setColors('rgb(121,120,119)', 'white');
		Context.game.clubs.find(c => c.name === "Excelsior" && c.country.name === "Netherlands").setColors('rgb(64,51,52)', 'white');
		Context.game.clubs.find(c => c.name === "DSC Arminia Bielefeld" && c.country.name === "Germany").setColors('rgb(55,79,125)', 'white');
		Context.game.clubs.find(c => c.name === "FC Twente" && c.country.name === "Netherlands").setColors('rgb(219,77,80)', 'white');
		Context.game.clubs.find(c => c.name === "FC Volendam" && c.country.name === "Netherlands").setColors('rgb(176,113,74)', 'white');
		Context.game.clubs.find(c => c.name === "Dynamo Kyiv" && c.country.name === "Ukraine").setColors('rgb(172,180,197)', 'black');
		Context.game.clubs.find(c => c.name === "Elche" && c.country.name === "Spain").setColors('rgb(199,202,196)', 'black');
		Context.game.clubs.find(c => c.name === "Empoli" && c.country.name === "Italy").setColors('rgb(53,106,157)', 'white');
		Context.game.clubs.find(c => c.name === "Estudiantes" && c.country.name === "Argentina").setColors('rgb(206,126,127)', 'black');
		Context.game.clubs.find(c => c.name === "Feyenoord" && c.country.name === "Netherlands").setColors('rgb(178,122,124)', 'black');
		Context.game.clubs.find(c => c.name === "FC Augsburg" && c.country.name === "Germany").setColors('rgb(165,92,90)', 'white');
		Context.game.clubs.find(c => c.name === "Fortuna Düsseldorf" && c.country.name === "Germany").setColors('rgb(149,49,57)', 'white');
		Context.game.clubs.find(c => c.name === "Fleetwood Town" && c.country.name === "England").setColors('rgb(184,87,94)', 'white');
		Context.game.clubs.find(c => c.name === "FC Emmen" && c.country.name === "Netherlands").setColors('rgb(213,124,132)', 'black');
		Context.game.clubs.find(c => c.name === "Exeter City" && c.country.name === "England").setColors('rgb(207,113,112)', 'black');
		Context.game.clubs.find(c => c.name === "FC Union Berlin" && c.country.name === "Germany").setColors('rgb(200,107,107)', 'black');
		Context.game.clubs.find(c => c.name === "Dundalk" && c.country.name === "Republic of Ireland").setColors('rgb(188,185,184)', 'black');
		Context.game.clubs.find(c => c.name === "FCSB" && c.country.name === "Romania").setColors('rgb(230,60,72)', 'white');
		Context.game.clubs.find(c => c.name === "East Bengal" && c.country.name === "India").setColors('rgb(202,94,49)', 'white');
		Context.game.clubs.find(c => c.name === "Elfsborg" && c.country.name === "Sweden").setColors('rgb(198,148,34)', 'black');
		Context.game.clubs.find(c => c.name === "Finn Harps" && c.country.name === "Republic of Ireland").setColors('rgb(51,112,189)', 'white');
		Context.game.clubs.find(c => c.name === "Estudiantes Mérida" && c.country.name === "Venezuela").setColors('rgb(191,144,149)', 'black');
		Context.game.clubs.find(c => c.name === "FC Barcelona" && c.country.name === "Spain").setColors('rgb(79,57,85)', 'white');
		Context.game.clubs.find(c => c.name === "Fluminense" && c.country.name === "Brazil").setColors('rgb(113,88,95)', 'white');
		Context.game.clubs.find(c => c.name === "Fortuna Sittard" && c.country.name === "Netherlands").setColors('rgb(219,209,38)', 'black');
		Context.game.clubs.find(c => c.name === "Erzgebirge Aue" && c.country.name === "Germany").setColors('rgb(83,66,121)', 'white');
		Context.game.clubs.find(c => c.name === "FC Groningen" && c.country.name === "Netherlands").setColors('rgb(147,177,155)', 'black');
		Context.game.clubs.find(c => c.name === "Famalicão" && c.country.name === "Portugal").setColors('rgb(197,197,197)', 'black');
		Context.game.clubs.find(c => c.name === "FC Utrecht" && c.country.name === "Netherlands").setColors('rgb(187,135,137)', 'black');
		Context.game.clubs.find(c => c.name === "Fenerbahçe" && c.country.name === "Turkey").setColors('rgb(140,139,84)', 'black');
		Context.game.clubs.find(c => c.name === "FSV Mainz 05" && c.country.name === "Germany").setColors('rgb(175,46,57)', 'white');
		Context.game.clubs.find(c => c.name === "Gaziantep F.K." && c.country.name === "Turkey").setColors('rgb(125,48,58)', 'white');
		Context.game.clubs.find(c => c.name === "Forest Green Rovers" && c.country.name === "England").setColors('rgb(117,150,64)', 'black');
		Context.game.clubs.find(c => c.name === "Fiorentina" && c.country.name === "Italy").setColors('rgb(76,54,97)', 'white');
		Context.game.clubs.find(c => c.name === "Gillingham" && c.country.name === "England").setColors('rgb(56,110,171)', 'white');
		Context.game.clubs.find(c => c.name === "Gent" && c.country.name === "Belgium").setColors('rgb(119,132,164)', 'black');
		Context.game.clubs.find(c => c.name === "Freiburg II" && c.country.name === "Germany").setColors('rgb(168,78,81)', 'white');
		Context.game.clubs.find(c => c.name === "Goiás" && c.country.name === "Brazil").setColors('rgb(49,79,77)', 'white');
		Context.game.clubs.find(c => c.name === "Girona" && c.country.name === "Spain").setColors('rgb(186,101,104)', 'white');
		Context.game.clubs.find(c => c.name === "Hajduk Split" && c.country.name === "Croatia").setColors('rgb(228,220,221)', 'black');
		Context.game.clubs.find(c => c.name === "Ferencváros" && c.country.name === "Hungary").setColors('rgb(139,154,144)', 'black');
		Context.game.clubs.find(c => c.name === "Guangzhou City" && c.country.name === "China PR").setColors('rgb(154,173,184)', 'black');
		Context.game.clubs.find(c => c.name === "Grenoble Foot 38" && c.country.name === "France").setColors('rgb(61,97,156)', 'white');
		Context.game.clubs.find(c => c.name === "Hallescher FC" && c.country.name === "Germany").setColors('rgb(203,41,50)', 'white');
		Context.game.clubs.find(c => c.name === "General Caballero JLM" && c.country.name === "Paraguay").setColors('rgb(211,69,75)', 'white');
		Context.game.clubs.find(c => c.name === "Fortaleza" && c.country.name === "Brazil").setColors('rgb(126,87,118)', 'white');
		Context.game.clubs.find(c => c.name === "Fulham" && c.country.name === "England").setColors('rgb(207,204,203)', 'black');
		Context.game.clubs.find(c => c.name === "Gimcheon Sangmu" && c.country.name === "Korea Republic").setColors('rgb(163,68,77)', 'white');
		Context.game.clubs.find(c => c.name === "Frosinone" && c.country.name === "Italy").setColors('rgb(167,152,57)', 'black');
		Context.game.clubs.find(c => c.name === "Flamengo" && c.country.name === "Brazil").setColors('rgb(128,59,62)', 'white');
		Context.game.clubs.find(c => c.name === "Getafe" && c.country.name === "Spain").setColors('rgb(45,74,153)', 'white');
		Context.game.clubs.find(c => c.name === "Go Ahead Eagles" && c.country.name === "Netherlands").setColors('rgb(202,109,43)', 'black');
		Context.game.clubs.find(c => c.name === "Górnik Zabrze" && c.country.name === "Poland").setColors('rgb(189,188,189)', 'black');
		Context.game.clubs.find(c => c.name === "Hannover 96" && c.country.name === "Germany").setColors('rgb(178,65,67)', 'white');
		Context.game.clubs.find(c => c.name === "Hansa Rostock" && c.country.name === "Germany").setColors('rgb(51,72,112)', 'white');
		Context.game.clubs.find(c => c.name === "Grimsby Town" && c.country.name === "England").setColors('rgb(128,125,124)', 'white');
		Context.game.clubs.find(c => c.name === "Hamburger SV" && c.country.name === "Germany").setColors('rgb(175,180,184)', 'black');
		Context.game.clubs.find(c => c.name === "Guaraní" && c.country.name === "Paraguay").setColors('rgb(113,99,42)', 'white');
		Context.game.clubs.find(c => c.name === "Heidenheim" && c.country.name === "Germany").setColors('rgb(149,59,86)', 'white');
		Context.game.clubs.find(c => c.name === "Genk" && c.country.name === "Belgium").setColors('rgb(47,90,175)', 'white');
		Context.game.clubs.find(c => c.name === "Holstein Kiel" && c.country.name === "Germany").setColors('rgb(98,101,139)', 'white');
		Context.game.clubs.find(c => c.name === "IFK Göteborg" && c.country.name === "Sweden").setColors('rgb(109,110,172)', 'white');
		Context.game.clubs.find(c => c.name === "Galatasaray" && c.country.name === "Turkey").setColors('rgb(158,91,59)', 'white');
		Context.game.clubs.find(c => c.name === "GIF Sundsvall" && c.country.name === "Sweden").setColors('rgb(50,81,154)', 'white');
		Context.game.clubs.find(c => c.name === "Gimnasia La Plata" && c.country.name === "Argentina").setColors('rgb(186,185,193)', 'black');
		Context.game.clubs.find(c => c.name === "Granada" && c.country.name === "Spain").setColors('rgb(179,106,120)', 'white');
		Context.game.clubs.find(c => c.name === "Internacional" && c.country.name === "Brazil").setColors('rgb(201,61,68)', 'white');
		Context.game.clubs.find(c => c.name === "Harrogate Town" && c.country.name === "England").setColors('rgb(200,159,61)', 'black');
		Context.game.clubs.find(c => c.name === "Goa" && c.country.name === "India").setColors('rgb(229,106,55)', 'black');
		Context.game.clubs.find(c => c.name === "HamKam" && c.country.name === "Norway").setColors('rgb(222,229,225)', 'black');
		Context.game.clubs.find(c => c.name === "Guabirá" && c.country.name === "Bolivia").setColors('rgb(187,41,50)', 'white');
		Context.game.clubs.find(c => c.name === "Hellas Verona" && c.country.name === "Italy").setColors('rgb(52,73,108)', 'white');
		Context.game.clubs.find(c => c.name === "Guingamp" && c.country.name === "France").setColors('rgb(169,39,41)', 'white');
		Context.game.clubs.find(c => c.name === "Genoa" && c.country.name === "Italy").setColors('rgb(121,59,63)', 'white');
		Context.game.clubs.find(c => c.name === "Horsens" && c.country.name === "Denmark").setColors('rgb(169,141,50)', 'black');
		Context.game.clubs.find(c => c.name === "Incheon United" && c.country.name === "Korea Republic").setColors('rgb(59,72,131)', 'white');
		Context.game.clubs.find(c => c.name === "Giresunspor" && c.country.name === "Turkey").setColors('rgb(107,140,131)', 'black');
		Context.game.clubs.find(c => c.name === "Hartberg" && c.country.name === "Austria").setColors('rgb(70,95,145)', 'white');
		Context.game.clubs.find(c => c.name === "Gil Vicente" && c.country.name === "Portugal").setColors('rgb(192,50,52)', 'white');
		Context.game.clubs.find(c => c.name === "Gangwon" && c.country.name === "Korea Republic").setColors('rgb(227,100,72)', 'black');
		Context.game.clubs.find(c => c.name === "Ipswich Town" && c.country.name === "England").setColors('rgb(60,71,117)', 'white');
		Context.game.clubs.find(c => c.name === "Godoy Cruz" && c.country.name === "Argentina").setColors('rgb(74,108,177)', 'white');
		Context.game.clubs.find(c => c.name === "Helsingborg" && c.country.name === "Sweden").setColors('rgb(221,39,45)', 'white');
		Context.game.clubs.find(c => c.name === "Grasshopper" && c.country.name === "Switzerland").setColors('rgb(132,140,171)', 'black');
		Context.game.clubs.find(c => c.name === "Guangzhou" && c.country.name === "China PR").setColors('rgb(170,59,63)', 'white');
		Context.game.clubs.find(c => c.name === "Hammarby" && c.country.name === "Sweden").setColors('rgb(212,219,210)', 'black');
		Context.game.clubs.find(c => c.name === "Houston Dynamo" && c.country.name === "United States").setColors('rgb(185,71,50)', 'white');
		Context.game.clubs.find(c => c.name === "İstanbulspor" && c.country.name === "Turkey").setColors('rgb(199,173,30)', 'black');
		Context.game.clubs.find(c => c.name === "Häcken" && c.country.name === "Sweden").setColors('rgb(106,94,46)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente" && c.country.name === "Argentina").setColors('rgb(205,38,37)', 'white');
		Context.game.clubs.find(c => c.name === "Hartlepool United" && c.country.name === "England").setColors('rgb(138,150,175)', 'black');
		Context.game.clubs.find(c => c.name === "Kilmarnock" && c.country.name === "Scotland").setColors('rgb(84,121,174)', 'white');
		Context.game.clubs.find(c => c.name === "İstanbul Başakşehir" && c.country.name === "Turkey").setColors('rgb(217,89,50)', 'white');
		Context.game.clubs.find(c => c.name === "Lanús" && c.country.name === "Argentina").setColors('rgb(125,67,78)', 'white');
		Context.game.clubs.find(c => c.name === "Juventus" && c.country.name === "Italy").setColors('rgb(149,149,148)', 'black');
		Context.game.clubs.find(c => c.name === "Henan" && c.country.name === "China PR").setColors('rgb(135,49,58)', 'white');
		Context.game.clubs.find(c => c.name === "Leyton Orient" && c.country.name === "England").setColors('rgb(157,45,49)', 'white');
		Context.game.clubs.find(c => c.name === "Lech Poznań" && c.country.name === "Poland").setColors('rgb(48,75,131)', 'white');
		Context.game.clubs.find(c => c.name === "Lorient" && c.country.name === "France").setColors('rgb(196,103,47)', 'white');
		Context.game.clubs.find(c => c.name === "Huddersfield Town" && c.country.name === "England").setColors('rgb(116,143,178)', 'black');
		Context.game.clubs.find(c => c.name === "Magallanes" && c.country.name === "Chile").setColors('rgb(143,182,205)', 'black');
		Context.game.clubs.find(c => c.name === "Mansfield Town" && c.country.name === "England").setColors('rgb(184,130,56)', 'black');
		Context.game.clubs.find(c => c.name === "Jagiellonia Białystok" && c.country.name === "Poland").setColors('rgb(194,96,75)', 'white');
		Context.game.clubs.find(c => c.name === "Independiente del Valle" && c.country.name === "Ecuador").setColors('rgb(47,49,53)', 'white');
		Context.game.clubs.find(c => c.name === "Hatayspor" && c.country.name === "Turkey").setColors('rgb(168,133,135)', 'black');
		Context.game.clubs.find(c => c.name === "København" && c.country.name === "Denmark").setColors('rgb(199,201,205)', 'black');
		Context.game.clubs.find(c => c.name === "Las Palmas" && c.country.name === "Spain").setColors('rgb(215,186,40)', 'black');
		Context.game.clubs.find(c => c.name === "Metropolitanos" && c.country.name === "Venezuela").setColors('rgb(76,73,142)', 'white');
		Context.game.clubs.find(c => c.name === "Hermannstadt" && c.country.name === "Romania").setColors('rgb(203,202,200)', 'black');
		Context.game.clubs.find(c => c.name === "Lechia Gdańsk" && c.country.name === "Poland").setColors('rgb(102,144,124)', 'black');
		Context.game.clubs.find(c => c.name === "Libertad" && c.country.name === "Paraguay").setColors('rgb(155,154,153)', 'black');
		Context.game.clubs.find(c => c.name === "Magdeburg" && c.country.name === "Germany").setColors('rgb(75,118,184)', 'white');
		Context.game.clubs.find(c => c.name === "Los Angeles FC" && c.country.name === "United States").setColors('rgb(55,54,52)', 'white');
		Context.game.clubs.find(c => c.name === "Kaiserslautern" && c.country.name === "Germany").setColors('rgb(171,51,53)', 'white');
		Context.game.clubs.find(c => c.name === "Huesca" && c.country.name === "Spain").setColors('rgb(101,58,80)', 'white');
		Context.game.clubs.find(c => c.name === "Jahn Regensburg" && c.country.name === "Germany").setColors('rgb(211,197,191)', 'black');
		Context.game.clubs.find(c => c.name === "Independiente Medellín" && c.country.name === "Colombia").setColors('rgb(136,50,52)', 'white');
		Context.game.clubs.find(c => c.name === "Haugesund" && c.country.name === "Norway").setColors('rgb(177,192,205)', 'black');
		Context.game.clubs.find(c => c.name === "Marítimo" && c.country.name === "Portugal").setColors('rgb(111,87,71)', 'white');
		Context.game.clubs.find(c => c.name === "Konyaspor" && c.country.name === "Turkey").setColors('rgb(103,142,129)', 'black');
		Context.game.clubs.find(c => c.name === "LASK Linz" && c.country.name === "Austria").setColors('rgb(157,148,123)', 'black');
		Context.game.clubs.find(c => c.name === "Metz" && c.country.name === "France").setColors('rgb(95,42,42)', 'white');
		Context.game.clubs.find(c => c.name === "Hertha BSC" && c.country.name === "Germany").setColors('rgb(141,145,162)', 'black');
		Context.game.clubs.find(c => c.name === "Leeds United" && c.country.name === "England").setColors('rgb(192,192,191)', 'black');
		Context.game.clubs.find(c => c.name === "Lille" && c.country.name === "France").setColors('rgb(165,66,74)', 'white');
		Context.game.clubs.find(c => c.name === "Hull City" && c.country.name === "England").setColors('rgb(122,81,49)', 'white');
		Context.game.clubs.find(c => c.name === "Lugano" && c.country.name === "Switzerland").setColors('rgb(85,73,73)', 'white');
		Context.game.clubs.find(c => c.name === "Málaga" && c.country.name === "Spain").setColors('rgb(103,162,194)', 'black');
		Context.game.clubs.find(c => c.name === "Kaizer Chiefs" && c.country.name === "South Africa").setColors('rgb(192,137,58)', 'black');
		Context.game.clubs.find(c => c.name === "Jamshedpur" && c.country.name === "India").setColors('rgb(143,65,76)', 'white');
		Context.game.clubs.find(c => c.name === "Hearts" && c.country.name === "Scotland").setColors('rgb(85,58,64)', 'white');
		Context.game.clubs.find(c => c.name === "Ingolstadt" && c.country.name === "Germany").setColors('rgb(121,41,52)', 'white');
		Context.game.clubs.find(c => c.name === "Mechelen" && c.country.name === "Belgium").setColors('rgb(190,132,56)', 'black');
		Context.game.clubs.find(c => c.name === "Hibernian" && c.country.name === "Scotland").setColors('rgb(77,121,92)', 'white');
		Context.game.clubs.find(c => c.name === "Korona Kielce" && c.country.name === "Poland").setColors('rgb(217,103,47)', 'black');
		Context.game.clubs.find(c => c.name === "Middlesbrough" && c.country.name === "England").setColors('rgb(206,70,86)', 'white');
		Context.game.clubs.find(c => c.name === "Laval" && c.country.name === "France").setColors('rgb(195,107,63)', 'black');
		Context.game.clubs.find(c => c.name === "Leganés" && c.country.name === "Spain").setColors('rgb(170,189,216)', 'black');
		Context.game.clubs.find(c => c.name === "Huracán" && c.country.name === "Argentina").setColors('rgb(204,197,197)', 'black');
		Context.game.clubs.find(c => c.name === "Lillestrøm" && c.country.name === "Norway").setColors('rgb(222,196,33)', 'black');
		Context.game.clubs.find(c => c.name === "Hebei" && c.country.name === "China PR").setColors('rgb(160,56,45)', 'white');
		Context.game.clubs.find(c => c.name === "Mallorca" && c.country.name === "Spain").setColors('rgb(134,43,45)', 'white');
		Context.game.clubs.find(c => c.name === "Inter" && c.country.name === "Italy").setColors('rgb(54,63,95)', 'white');
		Context.game.clubs.find(c => c.name === "Lugo" && c.country.name === "Spain").setColors('rgb(188,111,113)', 'black');
		Context.game.clubs.find(c => c.name === "Kalmar" && c.country.name === "Sweden").setColors('rgb(224,67,79)', 'white');
		Context.game.clubs.find(c => c.name === "Meizhou Hakka" && c.country.name === "China PR").setColors('rgb(146,55,63)', 'white');
		Context.game.clubs.find(c => c.name === "Jeju United" && c.country.name === "Korea Republic").setColors('rgb(236,122,63)', 'black');
		Context.game.clubs.find(c => c.name === "HJK" && c.country.name === "Finland").setColors('rgb(159,155,176)', 'black');
		Context.game.clubs.find(c => c.name === "Midtjylland" && c.country.name === "Denmark").setColors('rgb(54,46,46)', 'white');
		Context.game.clubs.find(c => c.name === "Lazio" && c.country.name === "Italy").setColors('rgb(105,202,210)', 'black');
		Context.game.clubs.find(c => c.name === "Kortrijk" && c.country.name === "Belgium").setColors('rgb(199,62,66)', 'white');
		Context.game.clubs.find(c => c.name === "Hyderabad" && c.country.name === "India").setColors('rgb(189,160,36)', 'black');
		Context.game.clubs.find(c => c.name === "Inter Miami" && c.country.name === "United States").setColors('rgb(188,153,173)', 'black');
		Context.game.clubs.find(c => c.name === "Miedź Legnica" && c.country.name === "Poland").setColors('rgb(50,68,157)', 'white');
		Context.game.clubs.find(c => c.name === "Lincoln City" && c.country.name === "England").setColors('rgb(193,116,124)', 'black');
		Context.game.clubs.find(c => c.name === "Legia Warszawa" && c.country.name === "Poland").setColors('rgb(203,203,202)', 'black');
		Context.game.clubs.find(c => c.name === "Malmö FF" && c.country.name === "Sweden").setColors('rgb(106,169,215)', 'black');
		Context.game.clubs.find(c => c.name === "Karlsruher SC" && c.country.name === "Germany").setColors('rgb(47,69,127)', 'white');
		Context.game.clubs.find(c => c.name === "Jeonbuk Motors" && c.country.name === "Korea Republic").setColors('rgb(62,111,82)', 'white');
		Context.game.clubs.find(c => c.name === "Mjällby" && c.country.name === "Sweden").setColors('rgb(230,203,51)', 'black');
		Context.game.clubs.find(c => c.name === "Luton Town" && c.country.name === "England").setColors('rgb(184,83,71)', 'white');
		Context.game.clubs.find(c => c.name === "Melbourne City" && c.country.name === "Australia").setColors('rgb(113,152,179)', 'black');
		Context.game.clubs.find(c => c.name === "Nantes" && c.country.name === "France").setColors('rgb(219,191,58)', 'black');
		Context.game.clubs.find(c => c.name === "Motherwell" && c.country.name === "Scotland").setColors('rgb(182,105,59)', 'white');
		Context.game.clubs.find(c => c.name === "Kristiansund" && c.country.name === "Norway").setColors('rgb(69,71,88)', 'white');
		Context.game.clubs.find(c => c.name === "Milan" && c.country.name === "Italy").setColors('rgb(86,45,44)', 'white');
		Context.game.clubs.find(c => c.name === "Newcastle United" && c.country.name === "England").setColors('rgb(129,135,137)', 'black');
		Context.game.clubs.find(c => c.name === "LDU Quito" && c.country.name === "Ecuador").setColors('rgb(191,191,188)', 'black');
		Context.game.clubs.find(c => c.name === "Liverpool" && c.country.name === "England").setColors('rgb(150,45,48)', 'white');
		Context.game.clubs.find(c => c.name === "Mamelodi Sundowns" && c.country.name === "South Africa").setColors('rgb(212,187,40)', 'black');
		Context.game.clubs.find(c => c.name === "Kasımpaşa" && c.country.name === "Turkey").setColors('rgb(107,110,118)', 'white');
		Context.game.clubs.find(c => c.name === "Leicester City" && c.country.name === "England").setColors('rgb(68,95,145)', 'white');
		Context.game.clubs.find(c => c.name === "Modena" && c.country.name === "Italy").setColors('rgb(205,174,44)', 'black');
		Context.game.clubs.find(c => c.name === "Jerv" && c.country.name === "Norway").setColors('rgb(224,169,81)', 'black');
		Context.game.clubs.find(c => c.name === "Luzern" && c.country.name === "Switzerland").setColors('rgb(74,61,84)', 'white');
		Context.game.clubs.find(c => c.name === "Napoli" && c.country.name === "Italy").setColors('rgb(51,107,191)', 'white');
		Context.game.clubs.find(c => c.name === "Millonarios" && c.country.name === "Colombia").setColors('rgb(55,78,147)', 'white');
		Context.game.clubs.find(c => c.name === "Melbourne Victory" && c.country.name === "Australia").setColors('rgb(48,54,64)', 'white');
		Context.game.clubs.find(c => c.name === "Newell's Old Boys" && c.country.name === "Argentina").setColors('rgb(116,56,55)', 'white');
		Context.game.clubs.find(c => c.name === "MSV Duisburg" && c.country.name === "Germany").setColors('rgb(139,138,144)', 'black');
		Context.game.clubs.find(c => c.name === "KV Oostende" && c.country.name === "Belgium").setColors('rgb(167,68,62)', 'white');
		Context.game.clubs.find(c => c.name === "Le Havre" && c.country.name === "France").setColors('rgb(90,119,140)', 'white');
		Context.game.clubs.find(c => c.name === "Liverpool" && c.country.name === "Uruguay").setColors('rgb(60,86,127)', 'white');
		Context.game.clubs.find(c => c.name === "Molde" && c.country.name === "Norway").setColors('rgb(60,86,149)', 'white');
		Context.game.clubs.find(c => c.name === "Lens" && c.country.name === "France").setColors('rgb(209,145,47)', 'black');
		Context.game.clubs.find(c => c.name === "Manchester City" && c.country.name === "England").setColors('rgb(106,154,194)', 'black');
		Context.game.clubs.find(c => c.name === "Nashville SC" && c.country.name === "United States").setColors('rgb(197,194,74)', 'black');
		Context.game.clubs.find(c => c.name === "Lyngby" && c.country.name === "Denmark").setColors('rgb(81,93,142)', 'white');
		Context.game.clubs.find(c => c.name === "Millwall" && c.country.name === "England").setColors('rgb(61,65,85)', 'white');
		Context.game.clubs.find(c => c.name === "Newport County" && c.country.name === "England").setColors('rgb(178,123,51)', 'black');
		Context.game.clubs.find(c => c.name === "Junior" && c.country.name === "Colombia").setColors('rgb(187,133,142)', 'black');
		Context.game.clubs.find(c => c.name === "Kayserispor" && c.country.name === "Turkey").setColors('rgb(185,77,47)', 'white');
		Context.game.clubs.find(c => c.name === "LA Galaxy" && c.country.name === "United States").setColors('rgb(189,188,188)', 'black');
		Context.game.clubs.find(c => c.name === "Melgar" && c.country.name === "Peru").setColors('rgb(120,45,48)', 'white');
		Context.game.clubs.find(c => c.name === "Mumbai City" && c.country.name === "India").setColors('rgb(84,137,180)', 'white');
		Context.game.clubs.find(c => c.name === "Livingston" && c.country.name === "Scotland").setColors('rgb(201,163,38)', 'black');
		Context.game.clubs.find(c => c.name === "Lecce" && c.country.name === "Italy").setColors('rgb(200,103,56)', 'black');
		Context.game.clubs.find(c => c.name === "Monaco" && c.country.name === "France").setColors('rgb(191,126,135)', 'black');
		Context.game.clubs.find(c => c.name === "Manchester United" && c.country.name === "England").setColors('rgb(189,50,70)', 'white');
		Context.game.clubs.find(c => c.name === "Levante" && c.country.name === "Spain").setColors('rgb(78,47,66)', 'white');
		Context.game.clubs.find(c => c.name === "Milton Keynes Dons" && c.country.name === "England").setColors('rgb(187,186,185)', 'black');
		Context.game.clubs.find(c => c.name === "Nice" && c.country.name === "France").setColors('rgb(80,49,49)', 'white');
		Context.game.clubs.find(c => c.name === "NEC" && c.country.name === "Netherlands").setColors('rgb(170,55,62)', 'white');
		Context.game.clubs.find(c => c.name === "Macarthur" && c.country.name === "Australia").setColors('rgb(145,140,114)', 'black');
		Context.game.clubs.find(c => c.name === "Kerala Blasters" && c.country.name === "India").setColors('rgb(202,186,51)', 'black');
		Context.game.clubs.find(c => c.name === "Northampton Town" && c.country.name === "England").setColors('rgb(173,149,147)', 'black');
		Context.game.clubs.find(c => c.name === "Osasuna" && c.country.name === "Spain").setColors('rgb(129,47,56)', 'white');
		Context.game.clubs.find(c => c.name === "Monagas" && c.country.name === "Venezuela").setColors('rgb(85,70,83)', 'white');
		Context.game.clubs.find(c => c.name === "Nacional" && c.country.name === "Uruguay").setColors('rgb(216,215,216)', 'black');
		Context.game.clubs.find(c => c.name === "Meppen" && c.country.name === "Germany").setColors('rgb(70,104,161)', 'white');
		Context.game.clubs.find(c => c.name === "Palmeiras" && c.country.name === "Brazil").setColors('rgb(58,114,92)', 'white');
		Context.game.clubs.find(c => c.name === "Odisha FC" && c.country.name === "India").setColors('rgb(51,48,53)', 'white');
		Context.game.clubs.find(c => c.name === "Peñarol" && c.country.name === "Uruguay").setColors('rgb(125,111,47)', 'white');
		Context.game.clubs.find(c => c.name === "Minnesota United" && c.country.name === "United States").setColors('rgb(67,69,69)', 'white');
		Context.game.clubs.find(c => c.name === "New England" && c.country.name === "United States").setColors('rgb(60,63,80)', 'white');
		Context.game.clubs.find(c => c.name === "Platense" && c.country.name === "Argentina").setColors('rgb(188,186,185)', 'black');
		Context.game.clubs.find(c => c.name === "Nîmes" && c.country.name === "France").setColors('rgb(206,60,71)', 'white');
		Context.game.clubs.find(c => c.name === "Porto" && c.country.name === "Portugal").setColors('rgb(110,129,165)', 'white');
		Context.game.clubs.find(c => c.name === "Radomiak Radom" && c.country.name === "Poland").setColors('rgb(55,92,66)', 'white');
		Context.game.clubs.find(c => c.name === "Montpellier" && c.country.name === "France").setColors('rgb(75,66,78)', 'white');
		Context.game.clubs.find(c => c.name === "NorthEast United" && c.country.name === "India").setColors('rgb(201,199,199)', 'black');
		Context.game.clubs.find(c => c.name === "Osnabrück" && c.country.name === "Germany").setColors('rgb(111,79,137)', 'white');
		Context.game.clubs.find(c => c.name === "Reading" && c.country.name === "England").setColors('rgb(128,145,175)', 'black');
		Context.game.clubs.find(c => c.name === "OH Leuven" && c.country.name === "Belgium").setColors('rgb(206,202,200)', 'black');
		Context.game.clubs.find(c => c.name === "Real Salt Lake" && c.country.name === "United States").setColors('rgb(117,60,69)', 'white');
		Context.game.clubs.find(c => c.name === "Mioveni" && c.country.name === "Romania").setColors('rgb(205,179,85)', 'black');
		Context.game.clubs.find(c => c.name === "New York City" && c.country.name === "United States").setColors('rgb(114,133,161)', 'white');
		Context.game.clubs.find(c => c.name === "Plymouth Argyle" && c.country.name === "England").setColors('rgb(79,94,88)', 'white');
		Context.game.clubs.find(c => c.name === "Panathinaikos" && c.country.name === "Greece").setColors('rgb(124,148,133)', 'black');
		Context.game.clubs.find(c => c.name === "Niort" && c.country.name === "France").setColors('rgb(56,86,150)', 'white');
		Context.game.clubs.find(c => c.name === "Portsmouth" && c.country.name === "England").setColors('rgb(59,94,154)', 'white');
		Context.game.clubs.find(c => c.name === "Perth Glory" && c.country.name === "Australia").setColors('rgb(99,62,93)', 'white');
		Context.game.clubs.find(c => c.name === "Raków Częstochowa" && c.country.name === "Poland").setColors('rgb(126,64,110)', 'white');
		Context.game.clubs.find(c => c.name === "Monza" && c.country.name === "Italy").setColors('rgb(195,66,73)', 'white');
		Context.game.clubs.find(c => c.name === "Norwich City" && c.country.name === "England").setColors('rgb(208,207,65)', 'black');
		Context.game.clubs.find(c => c.name === "Real Betis" && c.country.name === "Spain").setColors('rgb(112,161,132)', 'black');
		Context.game.clubs.find(c => c.name === "Mirandés" && c.country.name === "Spain").setColors('rgb(116,48,55)', 'white');
		Context.game.clubs.find(c => c.name === "Oxford United" && c.country.name === "England").setColors('rgb(190,166,104)', 'black');
		Context.game.clubs.find(c => c.name === "Olimpia" && c.country.name === "Paraguay").setColors('rgb(174,173,172)', 'black');
		Context.game.clubs.find(c => c.name === "New York RB" && c.country.name === "United States").setColors('rgb(164,52,62)', 'white');
		Context.game.clubs.find(c => c.name === "Nordsjælland" && c.country.name === "Denmark").setColors('rgb(190,53,49)', 'white');
		Context.game.clubs.find(c => c.name === "Real Sociedad" && c.country.name === "Spain").setColors('rgb(137,147,171)', 'black');
		Context.game.clubs.find(c => c.name === "PAOK" && c.country.name === "Greece").setColors('rgb(142,141,140)', 'black');
		Context.game.clubs.find(c => c.name === "Pogoń Szczecin" && c.country.name === "Poland").setColors('rgb(71,45,54)', 'white');
		Context.game.clubs.find(c => c.name === "Preston North End" && c.country.name === "England").setColors('rgb(199,199,202)', 'black');
		Context.game.clubs.find(c => c.name === "Morecambe" && c.country.name === "England").setColors('rgb(152,68,72)', 'white');
		Context.game.clubs.find(c => c.name === "Perugia" && c.country.name === "Italy").setColors('rgb(175,53,57)', 'white');
		Context.game.clubs.find(c => c.name === "Ried" && c.country.name === "Austria").setColors('rgb(73,94,84)', 'white');
		Context.game.clubs.find(c => c.name === "Real Madrid" && c.country.name === "Spain").setColors('rgb(206,205,204)', 'black');
		Context.game.clubs.find(c => c.name === "Randers" && c.country.name === "Denmark").setColors('rgb(133,177,207)', 'black');
		Context.game.clubs.find(c => c.name === "Norrköping" && c.country.name === "Sweden").setColors('rgb(199,201,204)', 'black');
		Context.game.clubs.find(c => c.name === "Nottingham Forest" && c.country.name === "England").setColors('rgb(178,36,37)', 'white');
		Context.game.clubs.find(c => c.name === "Newcastle Jets" && c.country.name === "Australia").setColors('rgb(178,157,116)', 'black');
		Context.game.clubs.find(c => c.name === "Olympique de Marseille" && c.country.name === "France").setColors('rgb(205,205,207)', 'black');
		Context.game.clubs.find(c => c.name === "Paços de Ferreira" && c.country.name === "Portugal").setColors('rgb(216,194,32)', 'black');
		Context.game.clubs.find(c => c.name === "Paris" && c.country.name === "France").setColors('rgb(44,48,57)', 'white');
		Context.game.clubs.find(c => c.name === "Real Valladolid" && c.country.name === "Spain").setColors('rgb(149,129,147)', 'black');
		Context.game.clubs.find(c => c.name === "Pohang Steelers" && c.country.name === "Korea Republic").setColors('rgb(118,73,66)', 'white');
		Context.game.clubs.find(c => c.name === "Roma" && c.country.name === "Italy").setColors('rgb(154,70,75)', 'white');
		Context.game.clubs.find(c => c.name === "PSV" && c.country.name === "Netherlands").setColors('rgb(192,139,139)', 'black');
		Context.game.clubs.find(c => c.name === "Real Oviedo" && c.country.name === "Spain").setColors('rgb(60,68,99)', 'white');
		Context.game.clubs.find(c => c.name === "Salernitana" && c.country.name === "Italy").setColors('rgb(90,50,50)', 'white');
		Context.game.clubs.find(c => c.name === "Peterborough United" && c.country.name === "England").setColors('rgb(49,98,152)', 'white');
		Context.game.clubs.find(c => c.name === "Rio Ave" && c.country.name === "Portugal").setColors('rgb(96,149,137)', 'black');
		Context.game.clubs.find(c => c.name === "Santa Clara" && c.country.name === "Portugal").setColors('rgb(181,38,38)', 'white');
		Context.game.clubs.find(c => c.name === "Olympique Lyonnais" && c.country.name === "France").setColors('rgb(194,183,185)', 'black');
		Context.game.clubs.find(c => c.name === "Ñublense" && c.country.name === "Chile").setColors('rgb(174,59,71)', 'white');
		Context.game.clubs.find(c => c.name === "Rangers" && c.country.name === "Scotland").setColors('rgb(47,77,158)', 'white');
		Context.game.clubs.find(c => c.name === "Paris Saint Germain" && c.country.name === "France").setColors('rgb(101,96,110)', 'white');
		Context.game.clubs.find(c => c.name === "Paderborn" && c.country.name === "Germany").setColors('rgb(50,68,100)', 'white');
		Context.game.clubs.find(c => c.name === "Real Zaragoza" && c.country.name === "Spain").setColors('rgb(188,190,200)', 'black');
		Context.game.clubs.find(c => c.name === "Ponferradina" && c.country.name === "Spain").setColors('rgb(113,120,150)', 'white');
		Context.game.clubs.find(c => c.name === "Rosario Central" && c.country.name === "Argentina").setColors('rgb(150,151,93)', 'black');
		Context.game.clubs.find(c => c.name === "Salford City" && c.country.name === "England").setColors('rgb(203,50,53)', 'white');
		Context.game.clubs.find(c => c.name === "Rionegro Águilas" && c.country.name === "Colombia").setColors('rgb(195,176,125)', 'black');
		Context.game.clubs.find(c => c.name === "Queens Park Rangers" && c.country.name === "England").setColors('rgb(131,159,186)', 'black');
		Context.game.clubs.find(c => c.name === "Petrolul 52" && c.country.name === "Romania").setColors('rgb(212,193,46)', 'black');
		Context.game.clubs.find(c => c.name === "Santa Fe" && c.country.name === "Colombia").setColors('rgb(188,94,95)', 'white');
		Context.game.clubs.find(c => c.name === "SC Freiburg" && c.country.name === "Germany").setColors('rgb(169,78,81)', 'white');
		Context.game.clubs.find(c => c.name === "Parma" && c.country.name === "Italy").setColors('rgb(158,158,156)', 'black');
		Context.game.clubs.find(c => c.name === "Rosenborg" && c.country.name === "Norway").setColors('rgb(197,196,195)', 'black');
		Context.game.clubs.find(c => c.name === "Nürnberg" && c.country.name === "Germany").setColors('rgb(85,52,55)', 'white');
		Context.game.clubs.find(c => c.name === "Reggina" && c.country.name === "Italy").setColors('rgb(109,42,51)', 'white');
		Context.game.clubs.find(c => c.name === "Palermo" && c.country.name === "Italy").setColors('rgb(172,129,146)', 'black');
		Context.game.clubs.find(c => c.name === "Rapid Bucuresti" && c.country.name === "Romania").setColors('rgb(133,59,79)', 'white');
		Context.game.clubs.find(c => c.name === "Oriente Petrolero" && c.country.name === "Bolivia").setColors('rgb(162,179,163)', 'black');
		Context.game.clubs.find(c => c.name === "Port Vale" && c.country.name === "England").setColors('rgb(182,182,181)', 'black');
		Context.game.clubs.find(c => c.name === "Salzburg" && c.country.name === "Austria").setColors('rgb(209,186,179)', 'black');
		Context.game.clubs.find(c => c.name === "River Plate" && c.country.name === "Argentina").setColors('rgb(194,162,162)', 'black');
		Context.game.clubs.find(c => c.name === "Santos" && c.country.name === "Brazil").setColors('rgb(215,215,214)', 'black');
		Context.game.clubs.find(c => c.name === "Philadelphia Union" && c.country.name === "United States").setColors('rgb(59,65,65)', 'white');
		Context.game.clubs.find(c => c.name === "Quevilly Rouen" && c.country.name === "France").setColors('rgb(211,47,48)', 'white');
		Context.game.clubs.find(c => c.name === "SC Heerenveen" && c.country.name === "Netherlands").setColors('rgb(133,148,191)', 'black');
		Context.game.clubs.find(c => c.name === "Ross County" && c.country.name === "Scotland").setColors('rgb(80,51,62)', 'white');
		Context.game.clubs.find(c => c.name === "Patronato" && c.country.name === "Argentina").setColors('rgb(121,65,69)', 'white');
		Context.game.clubs.find(c => c.name === "Rennes" && c.country.name === "France").setColors('rgb(196,53,56)', 'white');
		Context.game.clubs.find(c => c.name === "Palestino" && c.country.name === "Chile").setColors('rgb(150,115,110)', 'white');
		Context.game.clubs.find(c => c.name === "OB" && c.country.name === "Denmark").setColors('rgb(161,166,197)', 'black');
		Context.game.clubs.find(c => c.name === "Rapid Wien" && c.country.name === "Austria").setColors('rgb(124,153,135)', 'black');
		Context.game.clubs.find(c => c.name === "Sampdoria" && c.country.name === "Italy").setColors('rgb(68,95,146)', 'white');
		Context.game.clubs.find(c => c.name === "Orlando City" && c.country.name === "United States").setColors('rgb(71,67,140)', 'white');
		Context.game.clubs.find(c => c.name === "River Plate" && c.country.name === "Uruguay").setColors('rgb(154,132,135)', 'black');
		Context.game.clubs.find(c => c.name === "São Paulo" && c.country.name === "Brazil").setColors('rgb(191,181,180)', 'black');
		Context.game.clubs.find(c => c.name === "Portimonense" && c.country.name === "Portugal").setColors('rgb(119,118,118)', 'white');
		Context.game.clubs.find(c => c.name === "Piast Gliwice" && c.country.name === "Poland").setColors('rgb(115,71,111)', 'white');
		Context.game.clubs.find(c => c.name === "Schalke 04" && c.country.name === "Germany").setColors('rgb(51,62,118)', 'white');
		Context.game.clubs.find(c => c.name === "Rot-Weiss Essen" && c.country.name === "Germany").setColors('rgb(205,190,186)', 'black');
		Context.game.clubs.find(c => c.name === "Pau" && c.country.name === "France").setColors('rgb(173,156,50)', 'black');
		Context.game.clubs.find(c => c.name === "Palmaflor del Trópico" && c.country.name === "Bolivia").setColors('rgb(216,198,69)', 'black');
		Context.game.clubs.find(c => c.name === "Rayo Vallecano" && c.country.name === "Spain").setColors('rgb(190,157,156)', 'black');
		Context.game.clubs.find(c => c.name === "Odd" && c.country.name === "Norway").setColors('rgb(201,187,188)', 'black');
		Context.game.clubs.find(c => c.name === "San Jose Earthquakes" && c.country.name === "United States").setColors('rgb(48,59,85)', 'white');
		Context.game.clubs.find(c => c.name === "RFC Seraing" && c.country.name === "Belgium").setColors('rgb(145,63,63)', 'white');
		Context.game.clubs.find(c => c.name === "Sarmiento" && c.country.name === "Argentina").setColors('rgb(75,113,103)', 'white');
		Context.game.clubs.find(c => c.name === "Orlando Pirates" && c.country.name === "South Africa").setColors('rgb(63,57,58)', 'white');
		Context.game.clubs.find(c => c.name === "RKC Waalwijk" && c.country.name === "Netherlands").setColors('rgb(208,201,47)', 'black');
		Context.game.clubs.find(c => c.name === "Portland Timbers" && c.country.name === "United States").setColors('rgb(63,87,75)', 'white');
		Context.game.clubs.find(c => c.name === "Rotherham United" && c.country.name === "England").setColors('rgb(172,63,70)', 'white');
		Context.game.clubs.find(c => c.name === "Pisa" && c.country.name === "Italy").setColors('rgb(47,55,84)', 'white');
		Context.game.clubs.find(c => c.name === "SD Eibar" && c.country.name === "Spain").setColors('rgb(73,58,84)', 'white');
		Context.game.clubs.find(c => c.name === "Seattle Sounders" && c.country.name === "United States").setColors('rgb(80,128,88)', 'white');
		Context.game.clubs.find(c => c.name === "Silkeborg" && c.country.name === "Denmark").setColors('rgb(193,56,59)', 'white');
		Context.game.clubs.find(c => c.name === "San Lorenzo" && c.country.name === "Argentina").setColors('rgb(117,59,94)', 'white');
		Context.game.clubs.find(c => c.name === "Shandong Taishan" && c.country.name === "China PR").setColors('rgb(211,106,59)', 'black');
		Context.game.clubs.find(c => c.name === "RB Leipzig" && c.country.name === "Germany").setColors('rgb(214,192,190)', 'black');
		Context.game.clubs.find(c => c.name === "Sarpsborg 08" && c.country.name === "Norway").setColors('rgb(91,110,176)', 'white');
		Context.game.clubs.find(c => c.name === "Racing Santander" && c.country.name === "Spain").setColors('rgb(199,204,196)', 'black');
		Context.game.clubs.find(c => c.name === "Rheindorf Altach" && c.country.name === "Austria").setColors('rgb(181,181,178)', 'black');
		Context.game.clubs.find(c => c.name === "Rochdale" && c.country.name === "England").setColors('rgb(58,76,106)', 'white');
		Context.game.clubs.find(c => c.name === "Sochaux" && c.country.name === "France").setColors('rgb(172,169,66)', 'black');
		Context.game.clubs.find(c => c.name === "Saarbrücken" && c.country.name === "Germany").setColors('rgb(56,60,77)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting CP" && c.country.name === "Portugal").setColors('rgb(110,153,134)', 'black');
		Context.game.clubs.find(c => c.name === "St. Gallen" && c.country.name === "Switzerland").setColors('rgb(53,107,69)', 'white');
		Context.game.clubs.find(c => c.name === "Stockport County" && c.country.name === "England").setColors('rgb(47,94,149)', 'white');
		Context.game.clubs.find(c => c.name === "Seongnam" && c.country.name === "Korea Republic").setColors('rgb(61,60,61)', 'white');
		Context.game.clubs.find(c => c.name === "Sint-Truiden" && c.country.name === "Belgium").setColors('rgb(177,160,74)', 'black');
		Context.game.clubs.find(c => c.name === "Sandefjord" && c.country.name === "Norway").setColors('rgb(60,75,158)', 'white');
		Context.game.clubs.find(c => c.name === "Sassuolo" && c.country.name === "Italy").setColors('rgb(46,108,75)', 'white');
		Context.game.clubs.find(c => c.name === "Rodez" && c.country.name === "France").setColors('rgb(139,47,42)', 'white');
		Context.game.clubs.find(c => c.name === "Shanghai Port" && c.country.name === "China PR").setColors('rgb(151,41,56)', 'white');
		Context.game.clubs.find(c => c.name === "Southampton" && c.country.name === "England").setColors('rgb(185,139,143)', 'black');
		Context.game.clubs.find(c => c.name === "Suwon" && c.country.name === "Korea Republic").setColors('rgb(113,56,66)', 'white');
		Context.game.clubs.find(c => c.name === "Ternana" && c.country.name === "Italy").setColors('rgb(111,90,76)', 'white');
		Context.game.clubs.find(c => c.name === "Trabzonspor" && c.country.name === "Turkey").setColors('rgb(114,114,137)', 'white');
		Context.game.clubs.find(c => c.name === "Saint-Étienne" && c.country.name === "France").setColors('rgb(46,128,95)', 'white');
		Context.game.clubs.find(c => c.name === "St. Johnstone" && c.country.name === "Scotland").setColors('rgb(59,80,152)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting Cristal" && c.country.name === "Peru").setColors('rgb(80,167,213)', 'black');
		Context.game.clubs.find(c => c.name === "Stoke City" && c.country.name === "England").setColors('rgb(208,136,139)', 'black');
		Context.game.clubs.find(c => c.name === "Sandhausen" && c.country.name === "Germany").setColors('rgb(199,198,197)', 'black');
		Context.game.clubs.find(c => c.name === "SC Cambuur" && c.country.name === "Netherlands").setColors('rgb(198,190,46)', 'black');
		Context.game.clubs.find(c => c.name === "Sion" && c.country.name === "Switzerland").setColors('rgb(167,57,72)', 'white');
		Context.game.clubs.find(c => c.name === "Udinese" && c.country.name === "Italy").setColors('rgb(130,130,129)', 'white');
		Context.game.clubs.find(c => c.name === "Seoul" && c.country.name === "Korea Republic").setColors('rgb(111,63,63)', 'white');
		Context.game.clubs.find(c => c.name === "Shanghai Shenhua" && c.country.name === "China PR").setColors('rgb(68,72,127)', 'white');
		Context.game.clubs.find(c => c.name === "Suwon Bluewings" && c.country.name === "Korea Republic").setColors('rgb(60,74,163)', 'white');
		Context.game.clubs.find(c => c.name === "SPAL" && c.country.name === "Italy").setColors('rgb(135,169,194)', 'black');
		Context.game.clubs.find(c => c.name === "Vélez Sarsfield" && c.country.name === "Argentina").setColors('rgb(188,190,200)', 'black');
		Context.game.clubs.find(c => c.name === "The Strongest" && c.country.name === "Bolivia").setColors('rgb(109,91,55)', 'white');
		Context.game.clubs.find(c => c.name === "St. Mirren" && c.country.name === "Scotland").setColors('rgb(133,129,128)', 'white');
		Context.game.clubs.find(c => c.name === "Tranmere Rovers" && c.country.name === "England").setColors('rgb(197,199,198)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting Gijón" && c.country.name === "Spain").setColors('rgb(187,107,112)', 'black');
		Context.game.clubs.find(c => c.name === "Strasbourg" && c.country.name === "France").setColors('rgb(65,86,150)', 'white');
		Context.game.clubs.find(c => c.name === "Wisła Płock" && c.country.name === "Poland").setColors('rgb(45,81,148)', 'white');
		Context.game.clubs.find(c => c.name === "Voluntari" && c.country.name === "Romania").setColors('rgb(93,164,228)', 'black');
		Context.game.clubs.find(c => c.name === "Ulsan" && c.country.name === "Korea Republic").setColors('rgb(89,85,106)', 'white');
		Context.game.clubs.find(c => c.name === "Sirius" && c.country.name === "Sweden").setColors('rgb(66,89,134)', 'white');
		Context.game.clubs.find(c => c.name === "Sepsi" && c.country.name === "Romania").setColors('rgb(194,98,105)', 'white');
		Context.game.clubs.find(c => c.name === "Sparta Praha" && c.country.name === "Czech Republic").setColors('rgb(138,53,66)', 'white');
		Context.game.clubs.find(c => c.name === "Swansea City" && c.country.name === "England").setColors('rgb(203,202,201)', 'black');
		Context.game.clubs.find(c => c.name === "Venezia" && c.country.name === "Italy").setColors('rgb(47,47,45)', 'white');
		Context.game.clubs.find(c => c.name === "Sheffield United" && c.country.name === "England").setColors('rgb(196,126,134)', 'black');
		Context.game.clubs.find(c => c.name === "Sporting KC" && c.country.name === "United States").setColors('rgb(131,144,172)', 'black');
		Context.game.clubs.find(c => c.name === "Tromsø" && c.country.name === "Norway").setColors('rgb(195,138,142)', 'black');
		Context.game.clubs.find(c => c.name === "Strømsgodset" && c.country.name === "Norway").setColors('rgb(60,67,87)', 'white');
		Context.game.clubs.find(c => c.name === "Tianjin Jinmen Tiger" && c.country.name === "China PR").setColors('rgb(197,201,209)', 'black');
		Context.game.clubs.find(c => c.name === "Wolfsberger AC" && c.country.name === "Austria").setColors('rgb(191,189,186)', 'black');
		Context.game.clubs.find(c => c.name === "St. Pauli" && c.country.name === "Germany").setColors('rgb(80,69,60)', 'white');
		Context.game.clubs.find(c => c.name === "Waldhof Mannheim" && c.country.name === "Germany").setColors('rgb(47,67,92)', 'white');
		Context.game.clubs.find(c => c.name === "Ümraniyespor" && c.country.name === "Turkey").setColors('rgb(161,61,57)', 'white');
		Context.game.clubs.find(c => c.name === "Sivasspor" && c.country.name === "Turkey").setColors('rgb(151,96,95)', 'white');
		Context.game.clubs.find(c => c.name === "Verl" && c.country.name === "Germany").setColors('rgb(139,134,134)', 'black');
		Context.game.clubs.find(c => c.name === "Swindon Town" && c.country.name === "England").setColors('rgb(164,43,52)', 'white');
		Context.game.clubs.find(c => c.name === "Sparta Rotterdam" && c.country.name === "Netherlands").setColors('rgb(213,134,135)', 'black');
		Context.game.clubs.find(c => c.name === "Servette" && c.country.name === "Switzerland").setColors('rgb(98,55,65)', 'white');
		Context.game.clubs.find(c => c.name === "Sheffield Wednesday" && c.country.name === "England").setColors('rgb(115,128,173)', 'white');
		Context.game.clubs.find(c => c.name === "Troyes" && c.country.name === "France").setColors('rgb(51,82,176)', 'white');
		Context.game.clubs.find(c => c.name === "Sportivo Ameliano" && c.country.name === "Paraguay").setColors('rgb(155,159,188)', 'black');
		Context.game.clubs.find(c => c.name === "Wolverhampton Wanderers" && c.country.name === "England").setColors('rgb(219,166,33)', 'black');
		Context.game.clubs.find(c => c.name === "Walsall" && c.country.name === "England").setColors('rgb(198,45,63)', 'white');
		Context.game.clubs.find(c => c.name === "Tigre" && c.country.name === "Argentina").setColors('rgb(75,53,123)', 'white');
		Context.game.clubs.find(c => c.name === "Stade de Reims" && c.country.name === "France").setColors('rgb(176,81,80)', 'white');
		Context.game.clubs.find(c => c.name === "Union Saint-Gilloise" && c.country.name === "Belgium").setColors('rgb(193,157,47)', 'black');
		Context.game.clubs.find(c => c.name === "Sturm Graz" && c.country.name === "Austria").setColors('rgb(130,131,137)', 'black');
		Context.game.clubs.find(c => c.name === "VfB Oldenburg" && c.country.name === "Germany").setColors('rgb(59,62,87)', 'white');
		Context.game.clubs.find(c => c.name === "Śląsk Wrocław" && c.country.name === "Poland").setColors('rgb(49,100,66)', 'white');
		Context.game.clubs.find(c => c.name === "Sydney" && c.country.name === "Australia").setColors('rgb(83,141,187)', 'black');
		Context.game.clubs.find(c => c.name === "Spezia" && c.country.name === "Italy").setColors('rgb(193,195,193)', 'black');
		Context.game.clubs.find(c => c.name === "Shelbourne" && c.country.name === "Republic of Ireland").setColors('rgb(210,48,64)', 'white');
		Context.game.clubs.find(c => c.name === "Wrexham" && c.country.name === "England").setColors('rgb(190,41,57)', 'white');
		Context.game.clubs.find(c => c.name === "Sevilla" && c.country.name === "Spain").setColors('rgb(222,219,218)', 'black');
		Context.game.clubs.find(c => c.name === "SpVgg Greuther Fürth" && c.country.name === "Germany").setColors('rgb(99,170,132)', 'black');
		Context.game.clubs.find(c => c.name === "Warta Poznań" && c.country.name === "Poland").setColors('rgb(39,87,66)', 'white');
		Context.game.clubs.find(c => c.name === "Unión Santa Fe" && c.country.name === "Argentina").setColors('rgb(207,146,146)', 'black');
		Context.game.clubs.find(c => c.name === "Torino" && c.country.name === "Italy").setColors('rgb(122,72,79)', 'white');
		Context.game.clubs.find(c => c.name === "VfB Stuttgart" && c.country.name === "Germany").setColors('rgb(219,200,201)', 'black');
		Context.game.clubs.find(c => c.name === "Südtirol" && c.country.name === "Italy").setColors('rgb(196,191,189)', 'black');
		Context.game.clubs.find(c => c.name === "Stal Mielec" && c.country.name === "Poland").setColors('rgb(194,195,198)', 'black');
		Context.game.clubs.find(c => c.name === "TSG Hoffenheim" && c.country.name === "Germany").setColors('rgb(51,85,152)', 'white');
		Context.game.clubs.find(c => c.name === "Slavia Praha" && c.country.name === "Czech Republic").setColors('rgb(211,121,123)', 'black');
		Context.game.clubs.find(c => c.name === "WSG Tirol" && c.country.name === "Austria").setColors('rgb(145,181,172)', 'black');
		Context.game.clubs.find(c => c.name === "Tacuary" && c.country.name === "Paraguay").setColors('rgb(140,138,132)', 'black');
		Context.game.clubs.find(c => c.name === "Shenzhen" && c.country.name === "China PR").setColors('rgb(205,110,67)', 'black');
		Context.game.clubs.find(c => c.name === "Watford" && c.country.name === "England").setColors('rgb(207,177,34)', 'black');
		Context.game.clubs.find(c => c.name === "Universidad Católica" && c.country.name === "Chile").setColors('rgb(189,193,199)', 'black');
		Context.game.clubs.find(c => c.name === "SSC Farul" && c.country.name === "Romania").setColors('rgb(49,103,173)', 'white');
		Context.game.clubs.find(c => c.name === "Shakhtar Donetsk" && c.country.name === "Ukraine").setColors('rgb(151,87,35)', 'white');
		Context.game.clubs.find(c => c.name === "VfL Bochum 1848" && c.country.name === "Germany").setColors('rgb(40,67,96)', 'white');
		Context.game.clubs.find(c => c.name === "Sunderland" && c.country.name === "England").setColors('rgb(182,118,128)', 'black');
		Context.game.clubs.find(c => c.name === "Toronto" && c.country.name === "United States").setColors('rgb(89,72,74)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting Braga" && c.country.name === "Portugal").setColors('rgb(201,71,78)', 'white');
		Context.game.clubs.find(c => c.name === "Standard Liège" && c.country.name === "Belgium").setColors('rgb(182,64,70)', 'white');
		Context.game.clubs.find(c => c.name === "U Craiova 1948" && c.country.name === "Romania").setColors('rgb(41,66,137)', 'white');
		Context.game.clubs.find(c => c.name === "Wuhan Three Towns" && c.country.name === "China PR").setColors('rgb(75,88,134)', 'white');
		Context.game.clubs.find(c => c.name === "Wehen Wiesbaden" && c.country.name === "Germany").setColors('rgb(77,51,52)', 'white');
		Context.game.clubs.find(c => c.name === "Talleres Córdoba" && c.country.name === "Argentina").setColors('rgb(134,135,141)', 'black');
		Context.game.clubs.find(c => c.name === "Sligo Rovers" && c.country.name === "Republic of Ireland").setColors('rgb(152,50,53)', 'white');
		Context.game.clubs.find(c => c.name === "Universitario" && c.country.name === "Peru").setColors('rgb(187,162,162)', 'black');
		Context.game.clubs.find(c => c.name === "Shrewsbury Town" && c.country.name === "England").setColors('rgb(116,113,106)', 'white');
		Context.game.clubs.find(c => c.name === "VfL Wolfsburg" && c.country.name === "Germany").setColors('rgb(118,176,93)', 'black');
		Context.game.clubs.find(c => c.name === "Sutton United" && c.country.name === "England").setColors('rgb(189,155,63)', 'black');
		Context.game.clubs.find(c => c.name === "Shamrock Rovers" && c.country.name === "Republic of Ireland").setColors('rgb(132,150,136)', 'black');
		Context.game.clubs.find(c => c.name === "Tottenham Hotspur" && c.country.name === "England").setColors('rgb(228,223,221)', 'black');
		Context.game.clubs.find(c => c.name === "St Patrick's" && c.country.name === "Republic of Ireland").setColors('rgb(199,72,81)', 'white');
		Context.game.clubs.find(c => c.name === "Sporting Charleroi" && c.country.name === "Belgium").setColors('rgb(91,90,88)', 'white');
		Context.game.clubs.find(c => c.name === "Stevenage" && c.country.name === "England").setColors('rgb(142,61,65)', 'white');
		Context.game.clubs.find(c => c.name === "UCD" && c.country.name === "Republic of Ireland").setColors('rgb(73,136,178)', 'white');
		Context.game.clubs.find(c => c.name === "Wellington Phoenix" && c.country.name === "Australia").setColors('rgb(146,134,40)', 'black');
		Context.game.clubs.find(c => c.name === "Tenerife" && c.country.name === "Spain").setColors('rgb(189,192,201)', 'black');
		Context.game.clubs.find(c => c.name === "Wuhan Zall" && c.country.name === "China PR").setColors('rgb(223,140,68)', 'black');
		Context.game.clubs.find(c => c.name === "Universitatea Cluj" && c.country.name === "Romania").setColors('rgb(205,202,203)', 'black');
		Context.game.clubs.find(c => c.name === "Viborg" && c.country.name === "Denmark").setColors('rgb(45,81,59)', 'white');
		Context.game.clubs.find(c => c.name === "Toulouse" && c.country.name === "France").setColors('rgb(189,186,194)', 'black');
		Context.game.clubs.find(c => c.name === "UD Ibiza" && c.country.name === "Spain").setColors('rgb(104,143,189)', 'black');
		Context.game.clubs.find(c => c.name === "Werder Bremen" && c.country.name === "Germany").setColors('rgb(121,160,146)', 'black');
		Context.game.clubs.find(c => c.name === "Wycombe Wanderers" && c.country.name === "England").setColors('rgb(57,99,132)', 'white');
		Context.game.clubs.find(c => c.name === "Universitatea Craiova" && c.country.name === "Romania").setColors('rgb(118,137,166)', 'black');
		Context.game.clubs.find(c => c.name === "Viking" && c.country.name === "Norway").setColors('rgb(56,59,79)', 'white');
		Context.game.clubs.find(c => c.name === "West Bromwich Albion" && c.country.name === "England").setColors('rgb(127,131,145)', 'black');
		Context.game.clubs.find(c => c.name === "UTA Arad" && c.country.name === "Romania").setColors('rgb(215,55,64)', 'white');
		Context.game.clubs.find(c => c.name === "Young Boys" && c.country.name === "Switzerland").setColors('rgb(187,167,64)', 'black');
		Context.game.clubs.find(c => c.name === "Viktoria Köln" && c.country.name === "Germany").setColors('rgb(125,48,52)', 'white');
		Context.game.clubs.find(c => c.name === "West Ham United" && c.country.name === "England").setColors('rgb(128,76,90)', 'white');
		Context.game.clubs.find(c => c.name === "Valencia" && c.country.name === "Spain").setColors('rgb(205,204,202)', 'black');
		Context.game.clubs.find(c => c.name === "Zagłębie Lubin" && c.country.name === "Poland").setColors('rgb(176,72,42)', 'white');
		Context.game.clubs.find(c => c.name === "Viktoria Plzeň" && c.country.name === "Czech Republic").setColors('rgb(140,69,94)', 'white');
		Context.game.clubs.find(c => c.name === "Westerlo" && c.country.name === "Belgium").setColors('rgb(208,179,40)', 'black');
		Context.game.clubs.find(c => c.name === "Zhejiang" && c.country.name === "China PR").setColors('rgb(55,107,70)', 'white');
		Context.game.clubs.find(c => c.name === "Valenciennes" && c.country.name === "France").setColors('rgb(199,60,78)', 'white');
		Context.game.clubs.find(c => c.name === "Villarreal" && c.country.name === "Spain").setColors('rgb(207,208,35)', 'black');
		Context.game.clubs.find(c => c.name === "Western Sydney Wanderers" && c.country.name === "Australia").setColors('rgb(94,45,50)', 'white');
		Context.game.clubs.find(c => c.name === "Zulte-Waregem" && c.country.name === "Belgium").setColors('rgb(204,178,177)', 'black');
		Context.game.clubs.find(c => c.name === "Vålerenga" && c.country.name === "Norway").setColors('rgb(62,77,164)', 'white');
		Context.game.clubs.find(c => c.name === "Villarreal II" && c.country.name === "Spain").setColors('rgb(207,208,35)', 'black');
		Context.game.clubs.find(c => c.name === "Western United" && c.country.name === "Australia").setColors('rgb(47,74,61)', 'white');
		Context.game.clubs.find(c => c.name === "Zürich" && c.country.name === "Switzerland").setColors('rgb(197,199,202)', 'black');
		Context.game.clubs.find(c => c.name === "Vancouver Whitecaps" && c.country.name === "United States").setColors('rgb(185,183,184)', 'black');
		Context.game.clubs.find(c => c.name === "Vitesse" && c.country.name === "Netherlands").setColors('rgb(133,117,49)', 'white');
		Context.game.clubs.find(c => c.name === "Widzew Lodz" && c.country.name === "Poland").setColors('rgb(146,52,55)', 'white');
		Context.game.clubs.find(c => c.name === "Varberg BoIS" && c.country.name === "Sweden").setColors('rgb(73,103,85)', 'white');
		Context.game.clubs.find(c => c.name === "Zwickau" && c.country.name === "Germany").setColors('rgb(218,90,94)', 'black');
		Context.game.clubs.find(c => c.name === "Vitória SC" && c.country.name === "Portugal").setColors('rgb(209,207,203)', 'black');
		Context.game.clubs.find(c => c.name === "Värnamo" && c.country.name === "Sweden").setColors('rgb(224,221,221)', 'black');
		Context.game.clubs.find(c => c.name === "Wigan Athletic" && c.country.name === "England").setColors('rgb(116,129,159)', 'white');
		Context.game.clubs.find(c => c.name === "Vizela" && c.country.name === "Portugal").setColors('rgb(95,163,185)', 'black');
		Context.game.clubs.find(c => c.name === "Winterthur" && c.country.name === "Switzerland").setColors('rgb(158,44,45)', 'white');
	}

}